/*
MetaCopier API

Testing TradingAPIAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package metacopier

import (
	"context"
	openapiclient "github.com/metacopier/go-package"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
)

func Test_metacopier_TradingAPIAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test TradingAPIAPIService CloseAllPositions", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var accountId string

		httpRes, err := apiClient.TradingAPIAPI.CloseAllPositions(context.Background(), accountId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TradingAPIAPIService ClosePosition", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var accountId string
		var positionId string

		httpRes, err := apiClient.TradingAPIAPI.ClosePosition(context.Background(), accountId, positionId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TradingAPIAPIService GetHistoryPositions", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var accountId string

		resp, httpRes, err := apiClient.TradingAPIAPI.GetHistoryPositions(context.Background(), accountId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TradingAPIAPIService GetInformation", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var accountId string

		resp, httpRes, err := apiClient.TradingAPIAPI.GetInformation(context.Background(), accountId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TradingAPIAPIService GetPositions", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var accountId string

		resp, httpRes, err := apiClient.TradingAPIAPI.GetPositions(context.Background(), accountId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TradingAPIAPIService GetQuote", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var accountId string
		var symbol string

		resp, httpRes, err := apiClient.TradingAPIAPI.GetQuote(context.Background(), accountId, symbol).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TradingAPIAPIService GetSymbols", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var accountId string

		resp, httpRes, err := apiClient.TradingAPIAPI.GetSymbols(context.Background(), accountId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TradingAPIAPIService ModifyPosition", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var accountId string
		var positionId string

		httpRes, err := apiClient.TradingAPIAPI.ModifyPosition(context.Background(), accountId, positionId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TradingAPIAPIService OpenPosition", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var accountId string

		httpRes, err := apiClient.TradingAPIAPI.OpenPosition(context.Background(), accountId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test TradingAPIAPIService SendOrder", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var accountId string

		httpRes, err := apiClient.TradingAPIAPI.SendOrder(context.Background(), accountId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
