/*
MetaCopier API

Explore the power of the MetaCopier API! Our RESTful API offers scalable and secure access to accounts, projects, and more. Get started quickly with authentication, explore endpoints, and access code samples in various languages.<br/><br/>All dates are in ISO 8601<br/><br/>This API is not designed for real-time communication purposes. For instance, continuously polling account information such as open positions every second is not recommended.<br/><br/>Our frontend uses this API, so you can look at the requests on our frontend for examples.

API version: 1.2.5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package metacopier

import (
	"encoding/json"
	"fmt"
)

// checks if the FeatureMasanielloDTO type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FeatureMasanielloDTO{}

// FeatureMasanielloDTO DTO for the Masaniello money management feature (copier) (PRO)
type FeatureMasanielloDTO struct {
	// Expected point movement used to convert money stakes to lot sizes. Represents the typical price movement in points (MetaTrader minimal price change) for position sizing calculations. Larger values = more conservative lot sizes (smaller positions for the same stake).
	AssumedPointRisk *float32 `json:"assumedPointRisk,omitempty"`
	// Reset after completing all events.
	AutoResetOnSeriesComplete *bool `json:"autoResetOnSeriesComplete,omitempty"`
	AutoTuneBoundsValid       *bool `json:"autoTuneBoundsValid,omitempty"`
	// Defines the base used for bankroll percentage: BALANCE, EQUITY, FREE_MARGIN.
	BankrollBase string `json:"bankrollBase"`
	// Percentage of account base (balance/equity/free margin) used as bankroll for one series.
	BankrollPercentage *float32 `json:"bankrollPercentage,omitempty"`
	// Cooldown period in minutes before starting a new series after reset. 0 = no cooldown.
	CooldownAfterResetMinutes *int32 `json:"cooldownAfterResetMinutes,omitempty"`
	// If true, break-even trades do not consume an event in the series.
	ExcludeBreakEvenTrades *bool `json:"excludeBreakEvenTrades,omitempty"`
	// Expected loss per losing trade as R multiple. Default -1.0 means full risk is lost. For binary options use -1.0. For Forex with SL, typically -1.0. Use values like -0.5 if you expect partial losses on average.
	ExpectedLossRMultiple *float32 `json:"expectedLossRMultiple,omitempty"`
	// Expected payout factor for fixed payout systems (binary, etc). Example: 0.75 means +75% of risk on win. Used when payoutModel=PAYOUT_FACTOR.
	ExpectedPayoutFactor *float32 `json:"expectedPayoutFactor,omitempty"`
	// Expected average profit per win, expressed as R multiple. Example: 1.0 means +1R average win. Used when payoutModel=R_MULTIPLE.
	ExpectedRMultiple *float32 `json:"expectedRMultiple,omitempty"`
	// Expected number of wins in one series. Must be <= totalEvents.
	ExpectedWins      *int32 `json:"expectedWins,omitempty"`
	ExpectedWinsValid *bool  `json:"expectedWinsValid,omitempty"`
	// How to round the computed lot size to the lot step.
	LotRoundingMode string `json:"lotRoundingMode"`
	// Lot step to round lots to, e.g. 0.01 for Forex.
	LotStep *float32 `json:"lotStep,omitempty"`
	// Maximum consecutive losses allowed before forcing series reset as safety breaker. 0 = disabled.
	MaxConsecutiveLosses *int32 `json:"maxConsecutiveLosses,omitempty"`
	// Maximum expectedWins when auto-tuning is enabled. Null means no cap besides totalEvents.
	MaxExpectedWins *int32 `json:"maxExpectedWins,omitempty"`
	// Maximum lot size allowed.
	MaximumLotSize *float32 `json:"maximumLotSize,omitempty"`
	// Minimum expectedWins when auto-tuning is enabled.
	MinExpectedWins *int32 `json:"minExpectedWins,omitempty"`
	// Minimum lot size allowed.
	MinimumLotSize *float32 `json:"minimumLotSize,omitempty"`
	// Minimum number of historical trades required before using historical win rate. If fewer trades exist, falls back to manual expectedWins.
	MinimumTradesForHistoricalWinRate *int32 `json:"minimumTradesForHistoricalWinRate,omitempty"`
	// Defines how trades are classified (win/loss/breakeven).
	OutcomePolicy string `json:"outcomePolicy"`
	// Defines how partial closes (multiple TPs, manual partial close) are handled for outcome classification.
	PartialWinPolicy string `json:"partialWinPolicy"`
	// Defines how expected profit per win is modeled.
	PayoutModel string `json:"payoutModel"`
	// Reset series if bankroll is depleted.
	ResetOnBankrollDepleted *bool `json:"resetOnBankrollDepleted,omitempty"`
	// Reset series automatically when target profit is reached early.
	ResetOnTargetReached *bool `json:"resetOnTargetReached,omitempty"`
	// Look-back days for stats (0 = only current series).
	StatisticsLookBackDays *int32 `json:"statisticsLookBackDays,omitempty"`
	// Symbol-specific overrides for Masaniello settings. Only changed fields need to be provided.
	SymbolsConfiguration *map[string]FeatureMasanielloDTO `json:"symbolsConfiguration,omitempty"`
	// Target profit percentage relative to bankroll. Example: 50 means +50% of the bankroll.
	TargetProfitPercentage *float32 `json:"targetProfitPercentage,omitempty"`
	// Total number of trades (events) in one Masaniello series.
	TotalEvents *int32 `json:"totalEvents,omitempty"`
	// If true, system adjusts expectedWins based on historical win rate.
	UseHistoricalWinRate *bool `json:"useHistoricalWinRate,omitempty"`
	// Smoothing factor for historical win-rate adjustment (0..1). Higher means faster adaptation.
	WinRateSmoothingFactor *float32 `json:"winRateSmoothingFactor,omitempty"`
	// Defines what winThresholdPercentage is applied to.
	WinThresholdBase string `json:"winThresholdBase"`
	// Trade counts as WIN if profit >= winThresholdPercentage% of base (risk or notional), depending on winThresholdBase.
	WinThresholdPercentage *float32 `json:"winThresholdPercentage,omitempty"`
	AdditionalProperties   map[string]interface{}
}

type _FeatureMasanielloDTO FeatureMasanielloDTO

// NewFeatureMasanielloDTO instantiates a new FeatureMasanielloDTO object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFeatureMasanielloDTO(bankrollBase string, lotRoundingMode string, outcomePolicy string, partialWinPolicy string, payoutModel string, winThresholdBase string) *FeatureMasanielloDTO {
	this := FeatureMasanielloDTO{}
	var assumedPointRisk float32 = 100
	this.AssumedPointRisk = &assumedPointRisk
	var autoResetOnSeriesComplete bool = true
	this.AutoResetOnSeriesComplete = &autoResetOnSeriesComplete
	this.BankrollBase = bankrollBase
	var bankrollPercentage float32 = 5.0
	this.BankrollPercentage = &bankrollPercentage
	var cooldownAfterResetMinutes int32 = 0
	this.CooldownAfterResetMinutes = &cooldownAfterResetMinutes
	var excludeBreakEvenTrades bool = true
	this.ExcludeBreakEvenTrades = &excludeBreakEvenTrades
	var expectedLossRMultiple float32 = -1.0
	this.ExpectedLossRMultiple = &expectedLossRMultiple
	var expectedPayoutFactor float32 = 0.75
	this.ExpectedPayoutFactor = &expectedPayoutFactor
	var expectedRMultiple float32 = 1.0
	this.ExpectedRMultiple = &expectedRMultiple
	var expectedWins int32 = 6
	this.ExpectedWins = &expectedWins
	this.LotRoundingMode = lotRoundingMode
	var lotStep float32 = 0.01
	this.LotStep = &lotStep
	var maxConsecutiveLosses int32 = 0
	this.MaxConsecutiveLosses = &maxConsecutiveLosses
	var maximumLotSize float32 = 10.0
	this.MaximumLotSize = &maximumLotSize
	var minExpectedWins int32 = 1
	this.MinExpectedWins = &minExpectedWins
	var minimumLotSize float32 = 0.01
	this.MinimumLotSize = &minimumLotSize
	var minimumTradesForHistoricalWinRate int32 = 20
	this.MinimumTradesForHistoricalWinRate = &minimumTradesForHistoricalWinRate
	this.OutcomePolicy = outcomePolicy
	this.PartialWinPolicy = partialWinPolicy
	this.PayoutModel = payoutModel
	var resetOnBankrollDepleted bool = true
	this.ResetOnBankrollDepleted = &resetOnBankrollDepleted
	var resetOnTargetReached bool = true
	this.ResetOnTargetReached = &resetOnTargetReached
	var statisticsLookBackDays int32 = 30
	this.StatisticsLookBackDays = &statisticsLookBackDays
	var targetProfitPercentage float32 = 50.0
	this.TargetProfitPercentage = &targetProfitPercentage
	var totalEvents int32 = 10
	this.TotalEvents = &totalEvents
	var useHistoricalWinRate bool = false
	this.UseHistoricalWinRate = &useHistoricalWinRate
	var winRateSmoothingFactor float32 = 0.3
	this.WinRateSmoothingFactor = &winRateSmoothingFactor
	this.WinThresholdBase = winThresholdBase
	var winThresholdPercentage float32 = 0.0
	this.WinThresholdPercentage = &winThresholdPercentage
	return &this
}

// NewFeatureMasanielloDTOWithDefaults instantiates a new FeatureMasanielloDTO object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFeatureMasanielloDTOWithDefaults() *FeatureMasanielloDTO {
	this := FeatureMasanielloDTO{}
	var assumedPointRisk float32 = 100
	this.AssumedPointRisk = &assumedPointRisk
	var autoResetOnSeriesComplete bool = true
	this.AutoResetOnSeriesComplete = &autoResetOnSeriesComplete
	var bankrollBase string = "EQUITY"
	this.BankrollBase = bankrollBase
	var bankrollPercentage float32 = 5.0
	this.BankrollPercentage = &bankrollPercentage
	var cooldownAfterResetMinutes int32 = 0
	this.CooldownAfterResetMinutes = &cooldownAfterResetMinutes
	var excludeBreakEvenTrades bool = true
	this.ExcludeBreakEvenTrades = &excludeBreakEvenTrades
	var expectedLossRMultiple float32 = -1.0
	this.ExpectedLossRMultiple = &expectedLossRMultiple
	var expectedPayoutFactor float32 = 0.75
	this.ExpectedPayoutFactor = &expectedPayoutFactor
	var expectedRMultiple float32 = 1.0
	this.ExpectedRMultiple = &expectedRMultiple
	var expectedWins int32 = 6
	this.ExpectedWins = &expectedWins
	var lotRoundingMode string = "DOWN"
	this.LotRoundingMode = lotRoundingMode
	var lotStep float32 = 0.01
	this.LotStep = &lotStep
	var maxConsecutiveLosses int32 = 0
	this.MaxConsecutiveLosses = &maxConsecutiveLosses
	var maximumLotSize float32 = 10.0
	this.MaximumLotSize = &maximumLotSize
	var minExpectedWins int32 = 1
	this.MinExpectedWins = &minExpectedWins
	var minimumLotSize float32 = 0.01
	this.MinimumLotSize = &minimumLotSize
	var minimumTradesForHistoricalWinRate int32 = 20
	this.MinimumTradesForHistoricalWinRate = &minimumTradesForHistoricalWinRate
	var outcomePolicy string = "THRESHOLD"
	this.OutcomePolicy = outcomePolicy
	var partialWinPolicy string = "IGNORE"
	this.PartialWinPolicy = partialWinPolicy
	var payoutModel string = "R_MULTIPLE"
	this.PayoutModel = payoutModel
	var resetOnBankrollDepleted bool = true
	this.ResetOnBankrollDepleted = &resetOnBankrollDepleted
	var resetOnTargetReached bool = true
	this.ResetOnTargetReached = &resetOnTargetReached
	var statisticsLookBackDays int32 = 30
	this.StatisticsLookBackDays = &statisticsLookBackDays
	var targetProfitPercentage float32 = 50.0
	this.TargetProfitPercentage = &targetProfitPercentage
	var totalEvents int32 = 10
	this.TotalEvents = &totalEvents
	var useHistoricalWinRate bool = false
	this.UseHistoricalWinRate = &useHistoricalWinRate
	var winRateSmoothingFactor float32 = 0.3
	this.WinRateSmoothingFactor = &winRateSmoothingFactor
	var winThresholdBase string = "RISK"
	this.WinThresholdBase = winThresholdBase
	var winThresholdPercentage float32 = 0.0
	this.WinThresholdPercentage = &winThresholdPercentage
	return &this
}

// GetAssumedPointRisk returns the AssumedPointRisk field value if set, zero value otherwise.
func (o *FeatureMasanielloDTO) GetAssumedPointRisk() float32 {
	if o == nil || IsNil(o.AssumedPointRisk) {
		var ret float32
		return ret
	}
	return *o.AssumedPointRisk
}

// GetAssumedPointRiskOk returns a tuple with the AssumedPointRisk field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FeatureMasanielloDTO) GetAssumedPointRiskOk() (*float32, bool) {
	if o == nil || IsNil(o.AssumedPointRisk) {
		return nil, false
	}
	return o.AssumedPointRisk, true
}

// HasAssumedPointRisk returns a boolean if a field has been set.
func (o *FeatureMasanielloDTO) HasAssumedPointRisk() bool {
	if o != nil && !IsNil(o.AssumedPointRisk) {
		return true
	}

	return false
}

// SetAssumedPointRisk gets a reference to the given float32 and assigns it to the AssumedPointRisk field.
func (o *FeatureMasanielloDTO) SetAssumedPointRisk(v float32) {
	o.AssumedPointRisk = &v
}

// GetAutoResetOnSeriesComplete returns the AutoResetOnSeriesComplete field value if set, zero value otherwise.
func (o *FeatureMasanielloDTO) GetAutoResetOnSeriesComplete() bool {
	if o == nil || IsNil(o.AutoResetOnSeriesComplete) {
		var ret bool
		return ret
	}
	return *o.AutoResetOnSeriesComplete
}

// GetAutoResetOnSeriesCompleteOk returns a tuple with the AutoResetOnSeriesComplete field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FeatureMasanielloDTO) GetAutoResetOnSeriesCompleteOk() (*bool, bool) {
	if o == nil || IsNil(o.AutoResetOnSeriesComplete) {
		return nil, false
	}
	return o.AutoResetOnSeriesComplete, true
}

// HasAutoResetOnSeriesComplete returns a boolean if a field has been set.
func (o *FeatureMasanielloDTO) HasAutoResetOnSeriesComplete() bool {
	if o != nil && !IsNil(o.AutoResetOnSeriesComplete) {
		return true
	}

	return false
}

// SetAutoResetOnSeriesComplete gets a reference to the given bool and assigns it to the AutoResetOnSeriesComplete field.
func (o *FeatureMasanielloDTO) SetAutoResetOnSeriesComplete(v bool) {
	o.AutoResetOnSeriesComplete = &v
}

// GetAutoTuneBoundsValid returns the AutoTuneBoundsValid field value if set, zero value otherwise.
func (o *FeatureMasanielloDTO) GetAutoTuneBoundsValid() bool {
	if o == nil || IsNil(o.AutoTuneBoundsValid) {
		var ret bool
		return ret
	}
	return *o.AutoTuneBoundsValid
}

// GetAutoTuneBoundsValidOk returns a tuple with the AutoTuneBoundsValid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FeatureMasanielloDTO) GetAutoTuneBoundsValidOk() (*bool, bool) {
	if o == nil || IsNil(o.AutoTuneBoundsValid) {
		return nil, false
	}
	return o.AutoTuneBoundsValid, true
}

// HasAutoTuneBoundsValid returns a boolean if a field has been set.
func (o *FeatureMasanielloDTO) HasAutoTuneBoundsValid() bool {
	if o != nil && !IsNil(o.AutoTuneBoundsValid) {
		return true
	}

	return false
}

// SetAutoTuneBoundsValid gets a reference to the given bool and assigns it to the AutoTuneBoundsValid field.
func (o *FeatureMasanielloDTO) SetAutoTuneBoundsValid(v bool) {
	o.AutoTuneBoundsValid = &v
}

// GetBankrollBase returns the BankrollBase field value
func (o *FeatureMasanielloDTO) GetBankrollBase() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BankrollBase
}

// GetBankrollBaseOk returns a tuple with the BankrollBase field value
// and a boolean to check if the value has been set.
func (o *FeatureMasanielloDTO) GetBankrollBaseOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BankrollBase, true
}

// SetBankrollBase sets field value
func (o *FeatureMasanielloDTO) SetBankrollBase(v string) {
	o.BankrollBase = v
}

// GetBankrollPercentage returns the BankrollPercentage field value if set, zero value otherwise.
func (o *FeatureMasanielloDTO) GetBankrollPercentage() float32 {
	if o == nil || IsNil(o.BankrollPercentage) {
		var ret float32
		return ret
	}
	return *o.BankrollPercentage
}

// GetBankrollPercentageOk returns a tuple with the BankrollPercentage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FeatureMasanielloDTO) GetBankrollPercentageOk() (*float32, bool) {
	if o == nil || IsNil(o.BankrollPercentage) {
		return nil, false
	}
	return o.BankrollPercentage, true
}

// HasBankrollPercentage returns a boolean if a field has been set.
func (o *FeatureMasanielloDTO) HasBankrollPercentage() bool {
	if o != nil && !IsNil(o.BankrollPercentage) {
		return true
	}

	return false
}

// SetBankrollPercentage gets a reference to the given float32 and assigns it to the BankrollPercentage field.
func (o *FeatureMasanielloDTO) SetBankrollPercentage(v float32) {
	o.BankrollPercentage = &v
}

// GetCooldownAfterResetMinutes returns the CooldownAfterResetMinutes field value if set, zero value otherwise.
func (o *FeatureMasanielloDTO) GetCooldownAfterResetMinutes() int32 {
	if o == nil || IsNil(o.CooldownAfterResetMinutes) {
		var ret int32
		return ret
	}
	return *o.CooldownAfterResetMinutes
}

// GetCooldownAfterResetMinutesOk returns a tuple with the CooldownAfterResetMinutes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FeatureMasanielloDTO) GetCooldownAfterResetMinutesOk() (*int32, bool) {
	if o == nil || IsNil(o.CooldownAfterResetMinutes) {
		return nil, false
	}
	return o.CooldownAfterResetMinutes, true
}

// HasCooldownAfterResetMinutes returns a boolean if a field has been set.
func (o *FeatureMasanielloDTO) HasCooldownAfterResetMinutes() bool {
	if o != nil && !IsNil(o.CooldownAfterResetMinutes) {
		return true
	}

	return false
}

// SetCooldownAfterResetMinutes gets a reference to the given int32 and assigns it to the CooldownAfterResetMinutes field.
func (o *FeatureMasanielloDTO) SetCooldownAfterResetMinutes(v int32) {
	o.CooldownAfterResetMinutes = &v
}

// GetExcludeBreakEvenTrades returns the ExcludeBreakEvenTrades field value if set, zero value otherwise.
func (o *FeatureMasanielloDTO) GetExcludeBreakEvenTrades() bool {
	if o == nil || IsNil(o.ExcludeBreakEvenTrades) {
		var ret bool
		return ret
	}
	return *o.ExcludeBreakEvenTrades
}

// GetExcludeBreakEvenTradesOk returns a tuple with the ExcludeBreakEvenTrades field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FeatureMasanielloDTO) GetExcludeBreakEvenTradesOk() (*bool, bool) {
	if o == nil || IsNil(o.ExcludeBreakEvenTrades) {
		return nil, false
	}
	return o.ExcludeBreakEvenTrades, true
}

// HasExcludeBreakEvenTrades returns a boolean if a field has been set.
func (o *FeatureMasanielloDTO) HasExcludeBreakEvenTrades() bool {
	if o != nil && !IsNil(o.ExcludeBreakEvenTrades) {
		return true
	}

	return false
}

// SetExcludeBreakEvenTrades gets a reference to the given bool and assigns it to the ExcludeBreakEvenTrades field.
func (o *FeatureMasanielloDTO) SetExcludeBreakEvenTrades(v bool) {
	o.ExcludeBreakEvenTrades = &v
}

// GetExpectedLossRMultiple returns the ExpectedLossRMultiple field value if set, zero value otherwise.
func (o *FeatureMasanielloDTO) GetExpectedLossRMultiple() float32 {
	if o == nil || IsNil(o.ExpectedLossRMultiple) {
		var ret float32
		return ret
	}
	return *o.ExpectedLossRMultiple
}

// GetExpectedLossRMultipleOk returns a tuple with the ExpectedLossRMultiple field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FeatureMasanielloDTO) GetExpectedLossRMultipleOk() (*float32, bool) {
	if o == nil || IsNil(o.ExpectedLossRMultiple) {
		return nil, false
	}
	return o.ExpectedLossRMultiple, true
}

// HasExpectedLossRMultiple returns a boolean if a field has been set.
func (o *FeatureMasanielloDTO) HasExpectedLossRMultiple() bool {
	if o != nil && !IsNil(o.ExpectedLossRMultiple) {
		return true
	}

	return false
}

// SetExpectedLossRMultiple gets a reference to the given float32 and assigns it to the ExpectedLossRMultiple field.
func (o *FeatureMasanielloDTO) SetExpectedLossRMultiple(v float32) {
	o.ExpectedLossRMultiple = &v
}

// GetExpectedPayoutFactor returns the ExpectedPayoutFactor field value if set, zero value otherwise.
func (o *FeatureMasanielloDTO) GetExpectedPayoutFactor() float32 {
	if o == nil || IsNil(o.ExpectedPayoutFactor) {
		var ret float32
		return ret
	}
	return *o.ExpectedPayoutFactor
}

// GetExpectedPayoutFactorOk returns a tuple with the ExpectedPayoutFactor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FeatureMasanielloDTO) GetExpectedPayoutFactorOk() (*float32, bool) {
	if o == nil || IsNil(o.ExpectedPayoutFactor) {
		return nil, false
	}
	return o.ExpectedPayoutFactor, true
}

// HasExpectedPayoutFactor returns a boolean if a field has been set.
func (o *FeatureMasanielloDTO) HasExpectedPayoutFactor() bool {
	if o != nil && !IsNil(o.ExpectedPayoutFactor) {
		return true
	}

	return false
}

// SetExpectedPayoutFactor gets a reference to the given float32 and assigns it to the ExpectedPayoutFactor field.
func (o *FeatureMasanielloDTO) SetExpectedPayoutFactor(v float32) {
	o.ExpectedPayoutFactor = &v
}

// GetExpectedRMultiple returns the ExpectedRMultiple field value if set, zero value otherwise.
func (o *FeatureMasanielloDTO) GetExpectedRMultiple() float32 {
	if o == nil || IsNil(o.ExpectedRMultiple) {
		var ret float32
		return ret
	}
	return *o.ExpectedRMultiple
}

// GetExpectedRMultipleOk returns a tuple with the ExpectedRMultiple field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FeatureMasanielloDTO) GetExpectedRMultipleOk() (*float32, bool) {
	if o == nil || IsNil(o.ExpectedRMultiple) {
		return nil, false
	}
	return o.ExpectedRMultiple, true
}

// HasExpectedRMultiple returns a boolean if a field has been set.
func (o *FeatureMasanielloDTO) HasExpectedRMultiple() bool {
	if o != nil && !IsNil(o.ExpectedRMultiple) {
		return true
	}

	return false
}

// SetExpectedRMultiple gets a reference to the given float32 and assigns it to the ExpectedRMultiple field.
func (o *FeatureMasanielloDTO) SetExpectedRMultiple(v float32) {
	o.ExpectedRMultiple = &v
}

// GetExpectedWins returns the ExpectedWins field value if set, zero value otherwise.
func (o *FeatureMasanielloDTO) GetExpectedWins() int32 {
	if o == nil || IsNil(o.ExpectedWins) {
		var ret int32
		return ret
	}
	return *o.ExpectedWins
}

// GetExpectedWinsOk returns a tuple with the ExpectedWins field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FeatureMasanielloDTO) GetExpectedWinsOk() (*int32, bool) {
	if o == nil || IsNil(o.ExpectedWins) {
		return nil, false
	}
	return o.ExpectedWins, true
}

// HasExpectedWins returns a boolean if a field has been set.
func (o *FeatureMasanielloDTO) HasExpectedWins() bool {
	if o != nil && !IsNil(o.ExpectedWins) {
		return true
	}

	return false
}

// SetExpectedWins gets a reference to the given int32 and assigns it to the ExpectedWins field.
func (o *FeatureMasanielloDTO) SetExpectedWins(v int32) {
	o.ExpectedWins = &v
}

// GetExpectedWinsValid returns the ExpectedWinsValid field value if set, zero value otherwise.
func (o *FeatureMasanielloDTO) GetExpectedWinsValid() bool {
	if o == nil || IsNil(o.ExpectedWinsValid) {
		var ret bool
		return ret
	}
	return *o.ExpectedWinsValid
}

// GetExpectedWinsValidOk returns a tuple with the ExpectedWinsValid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FeatureMasanielloDTO) GetExpectedWinsValidOk() (*bool, bool) {
	if o == nil || IsNil(o.ExpectedWinsValid) {
		return nil, false
	}
	return o.ExpectedWinsValid, true
}

// HasExpectedWinsValid returns a boolean if a field has been set.
func (o *FeatureMasanielloDTO) HasExpectedWinsValid() bool {
	if o != nil && !IsNil(o.ExpectedWinsValid) {
		return true
	}

	return false
}

// SetExpectedWinsValid gets a reference to the given bool and assigns it to the ExpectedWinsValid field.
func (o *FeatureMasanielloDTO) SetExpectedWinsValid(v bool) {
	o.ExpectedWinsValid = &v
}

// GetLotRoundingMode returns the LotRoundingMode field value
func (o *FeatureMasanielloDTO) GetLotRoundingMode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LotRoundingMode
}

// GetLotRoundingModeOk returns a tuple with the LotRoundingMode field value
// and a boolean to check if the value has been set.
func (o *FeatureMasanielloDTO) GetLotRoundingModeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LotRoundingMode, true
}

// SetLotRoundingMode sets field value
func (o *FeatureMasanielloDTO) SetLotRoundingMode(v string) {
	o.LotRoundingMode = v
}

// GetLotStep returns the LotStep field value if set, zero value otherwise.
func (o *FeatureMasanielloDTO) GetLotStep() float32 {
	if o == nil || IsNil(o.LotStep) {
		var ret float32
		return ret
	}
	return *o.LotStep
}

// GetLotStepOk returns a tuple with the LotStep field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FeatureMasanielloDTO) GetLotStepOk() (*float32, bool) {
	if o == nil || IsNil(o.LotStep) {
		return nil, false
	}
	return o.LotStep, true
}

// HasLotStep returns a boolean if a field has been set.
func (o *FeatureMasanielloDTO) HasLotStep() bool {
	if o != nil && !IsNil(o.LotStep) {
		return true
	}

	return false
}

// SetLotStep gets a reference to the given float32 and assigns it to the LotStep field.
func (o *FeatureMasanielloDTO) SetLotStep(v float32) {
	o.LotStep = &v
}

// GetMaxConsecutiveLosses returns the MaxConsecutiveLosses field value if set, zero value otherwise.
func (o *FeatureMasanielloDTO) GetMaxConsecutiveLosses() int32 {
	if o == nil || IsNil(o.MaxConsecutiveLosses) {
		var ret int32
		return ret
	}
	return *o.MaxConsecutiveLosses
}

// GetMaxConsecutiveLossesOk returns a tuple with the MaxConsecutiveLosses field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FeatureMasanielloDTO) GetMaxConsecutiveLossesOk() (*int32, bool) {
	if o == nil || IsNil(o.MaxConsecutiveLosses) {
		return nil, false
	}
	return o.MaxConsecutiveLosses, true
}

// HasMaxConsecutiveLosses returns a boolean if a field has been set.
func (o *FeatureMasanielloDTO) HasMaxConsecutiveLosses() bool {
	if o != nil && !IsNil(o.MaxConsecutiveLosses) {
		return true
	}

	return false
}

// SetMaxConsecutiveLosses gets a reference to the given int32 and assigns it to the MaxConsecutiveLosses field.
func (o *FeatureMasanielloDTO) SetMaxConsecutiveLosses(v int32) {
	o.MaxConsecutiveLosses = &v
}

// GetMaxExpectedWins returns the MaxExpectedWins field value if set, zero value otherwise.
func (o *FeatureMasanielloDTO) GetMaxExpectedWins() int32 {
	if o == nil || IsNil(o.MaxExpectedWins) {
		var ret int32
		return ret
	}
	return *o.MaxExpectedWins
}

// GetMaxExpectedWinsOk returns a tuple with the MaxExpectedWins field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FeatureMasanielloDTO) GetMaxExpectedWinsOk() (*int32, bool) {
	if o == nil || IsNil(o.MaxExpectedWins) {
		return nil, false
	}
	return o.MaxExpectedWins, true
}

// HasMaxExpectedWins returns a boolean if a field has been set.
func (o *FeatureMasanielloDTO) HasMaxExpectedWins() bool {
	if o != nil && !IsNil(o.MaxExpectedWins) {
		return true
	}

	return false
}

// SetMaxExpectedWins gets a reference to the given int32 and assigns it to the MaxExpectedWins field.
func (o *FeatureMasanielloDTO) SetMaxExpectedWins(v int32) {
	o.MaxExpectedWins = &v
}

// GetMaximumLotSize returns the MaximumLotSize field value if set, zero value otherwise.
func (o *FeatureMasanielloDTO) GetMaximumLotSize() float32 {
	if o == nil || IsNil(o.MaximumLotSize) {
		var ret float32
		return ret
	}
	return *o.MaximumLotSize
}

// GetMaximumLotSizeOk returns a tuple with the MaximumLotSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FeatureMasanielloDTO) GetMaximumLotSizeOk() (*float32, bool) {
	if o == nil || IsNil(o.MaximumLotSize) {
		return nil, false
	}
	return o.MaximumLotSize, true
}

// HasMaximumLotSize returns a boolean if a field has been set.
func (o *FeatureMasanielloDTO) HasMaximumLotSize() bool {
	if o != nil && !IsNil(o.MaximumLotSize) {
		return true
	}

	return false
}

// SetMaximumLotSize gets a reference to the given float32 and assigns it to the MaximumLotSize field.
func (o *FeatureMasanielloDTO) SetMaximumLotSize(v float32) {
	o.MaximumLotSize = &v
}

// GetMinExpectedWins returns the MinExpectedWins field value if set, zero value otherwise.
func (o *FeatureMasanielloDTO) GetMinExpectedWins() int32 {
	if o == nil || IsNil(o.MinExpectedWins) {
		var ret int32
		return ret
	}
	return *o.MinExpectedWins
}

// GetMinExpectedWinsOk returns a tuple with the MinExpectedWins field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FeatureMasanielloDTO) GetMinExpectedWinsOk() (*int32, bool) {
	if o == nil || IsNil(o.MinExpectedWins) {
		return nil, false
	}
	return o.MinExpectedWins, true
}

// HasMinExpectedWins returns a boolean if a field has been set.
func (o *FeatureMasanielloDTO) HasMinExpectedWins() bool {
	if o != nil && !IsNil(o.MinExpectedWins) {
		return true
	}

	return false
}

// SetMinExpectedWins gets a reference to the given int32 and assigns it to the MinExpectedWins field.
func (o *FeatureMasanielloDTO) SetMinExpectedWins(v int32) {
	o.MinExpectedWins = &v
}

// GetMinimumLotSize returns the MinimumLotSize field value if set, zero value otherwise.
func (o *FeatureMasanielloDTO) GetMinimumLotSize() float32 {
	if o == nil || IsNil(o.MinimumLotSize) {
		var ret float32
		return ret
	}
	return *o.MinimumLotSize
}

// GetMinimumLotSizeOk returns a tuple with the MinimumLotSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FeatureMasanielloDTO) GetMinimumLotSizeOk() (*float32, bool) {
	if o == nil || IsNil(o.MinimumLotSize) {
		return nil, false
	}
	return o.MinimumLotSize, true
}

// HasMinimumLotSize returns a boolean if a field has been set.
func (o *FeatureMasanielloDTO) HasMinimumLotSize() bool {
	if o != nil && !IsNil(o.MinimumLotSize) {
		return true
	}

	return false
}

// SetMinimumLotSize gets a reference to the given float32 and assigns it to the MinimumLotSize field.
func (o *FeatureMasanielloDTO) SetMinimumLotSize(v float32) {
	o.MinimumLotSize = &v
}

// GetMinimumTradesForHistoricalWinRate returns the MinimumTradesForHistoricalWinRate field value if set, zero value otherwise.
func (o *FeatureMasanielloDTO) GetMinimumTradesForHistoricalWinRate() int32 {
	if o == nil || IsNil(o.MinimumTradesForHistoricalWinRate) {
		var ret int32
		return ret
	}
	return *o.MinimumTradesForHistoricalWinRate
}

// GetMinimumTradesForHistoricalWinRateOk returns a tuple with the MinimumTradesForHistoricalWinRate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FeatureMasanielloDTO) GetMinimumTradesForHistoricalWinRateOk() (*int32, bool) {
	if o == nil || IsNil(o.MinimumTradesForHistoricalWinRate) {
		return nil, false
	}
	return o.MinimumTradesForHistoricalWinRate, true
}

// HasMinimumTradesForHistoricalWinRate returns a boolean if a field has been set.
func (o *FeatureMasanielloDTO) HasMinimumTradesForHistoricalWinRate() bool {
	if o != nil && !IsNil(o.MinimumTradesForHistoricalWinRate) {
		return true
	}

	return false
}

// SetMinimumTradesForHistoricalWinRate gets a reference to the given int32 and assigns it to the MinimumTradesForHistoricalWinRate field.
func (o *FeatureMasanielloDTO) SetMinimumTradesForHistoricalWinRate(v int32) {
	o.MinimumTradesForHistoricalWinRate = &v
}

// GetOutcomePolicy returns the OutcomePolicy field value
func (o *FeatureMasanielloDTO) GetOutcomePolicy() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OutcomePolicy
}

// GetOutcomePolicyOk returns a tuple with the OutcomePolicy field value
// and a boolean to check if the value has been set.
func (o *FeatureMasanielloDTO) GetOutcomePolicyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OutcomePolicy, true
}

// SetOutcomePolicy sets field value
func (o *FeatureMasanielloDTO) SetOutcomePolicy(v string) {
	o.OutcomePolicy = v
}

// GetPartialWinPolicy returns the PartialWinPolicy field value
func (o *FeatureMasanielloDTO) GetPartialWinPolicy() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PartialWinPolicy
}

// GetPartialWinPolicyOk returns a tuple with the PartialWinPolicy field value
// and a boolean to check if the value has been set.
func (o *FeatureMasanielloDTO) GetPartialWinPolicyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PartialWinPolicy, true
}

// SetPartialWinPolicy sets field value
func (o *FeatureMasanielloDTO) SetPartialWinPolicy(v string) {
	o.PartialWinPolicy = v
}

// GetPayoutModel returns the PayoutModel field value
func (o *FeatureMasanielloDTO) GetPayoutModel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PayoutModel
}

// GetPayoutModelOk returns a tuple with the PayoutModel field value
// and a boolean to check if the value has been set.
func (o *FeatureMasanielloDTO) GetPayoutModelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PayoutModel, true
}

// SetPayoutModel sets field value
func (o *FeatureMasanielloDTO) SetPayoutModel(v string) {
	o.PayoutModel = v
}

// GetResetOnBankrollDepleted returns the ResetOnBankrollDepleted field value if set, zero value otherwise.
func (o *FeatureMasanielloDTO) GetResetOnBankrollDepleted() bool {
	if o == nil || IsNil(o.ResetOnBankrollDepleted) {
		var ret bool
		return ret
	}
	return *o.ResetOnBankrollDepleted
}

// GetResetOnBankrollDepletedOk returns a tuple with the ResetOnBankrollDepleted field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FeatureMasanielloDTO) GetResetOnBankrollDepletedOk() (*bool, bool) {
	if o == nil || IsNil(o.ResetOnBankrollDepleted) {
		return nil, false
	}
	return o.ResetOnBankrollDepleted, true
}

// HasResetOnBankrollDepleted returns a boolean if a field has been set.
func (o *FeatureMasanielloDTO) HasResetOnBankrollDepleted() bool {
	if o != nil && !IsNil(o.ResetOnBankrollDepleted) {
		return true
	}

	return false
}

// SetResetOnBankrollDepleted gets a reference to the given bool and assigns it to the ResetOnBankrollDepleted field.
func (o *FeatureMasanielloDTO) SetResetOnBankrollDepleted(v bool) {
	o.ResetOnBankrollDepleted = &v
}

// GetResetOnTargetReached returns the ResetOnTargetReached field value if set, zero value otherwise.
func (o *FeatureMasanielloDTO) GetResetOnTargetReached() bool {
	if o == nil || IsNil(o.ResetOnTargetReached) {
		var ret bool
		return ret
	}
	return *o.ResetOnTargetReached
}

// GetResetOnTargetReachedOk returns a tuple with the ResetOnTargetReached field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FeatureMasanielloDTO) GetResetOnTargetReachedOk() (*bool, bool) {
	if o == nil || IsNil(o.ResetOnTargetReached) {
		return nil, false
	}
	return o.ResetOnTargetReached, true
}

// HasResetOnTargetReached returns a boolean if a field has been set.
func (o *FeatureMasanielloDTO) HasResetOnTargetReached() bool {
	if o != nil && !IsNil(o.ResetOnTargetReached) {
		return true
	}

	return false
}

// SetResetOnTargetReached gets a reference to the given bool and assigns it to the ResetOnTargetReached field.
func (o *FeatureMasanielloDTO) SetResetOnTargetReached(v bool) {
	o.ResetOnTargetReached = &v
}

// GetStatisticsLookBackDays returns the StatisticsLookBackDays field value if set, zero value otherwise.
func (o *FeatureMasanielloDTO) GetStatisticsLookBackDays() int32 {
	if o == nil || IsNil(o.StatisticsLookBackDays) {
		var ret int32
		return ret
	}
	return *o.StatisticsLookBackDays
}

// GetStatisticsLookBackDaysOk returns a tuple with the StatisticsLookBackDays field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FeatureMasanielloDTO) GetStatisticsLookBackDaysOk() (*int32, bool) {
	if o == nil || IsNil(o.StatisticsLookBackDays) {
		return nil, false
	}
	return o.StatisticsLookBackDays, true
}

// HasStatisticsLookBackDays returns a boolean if a field has been set.
func (o *FeatureMasanielloDTO) HasStatisticsLookBackDays() bool {
	if o != nil && !IsNil(o.StatisticsLookBackDays) {
		return true
	}

	return false
}

// SetStatisticsLookBackDays gets a reference to the given int32 and assigns it to the StatisticsLookBackDays field.
func (o *FeatureMasanielloDTO) SetStatisticsLookBackDays(v int32) {
	o.StatisticsLookBackDays = &v
}

// GetSymbolsConfiguration returns the SymbolsConfiguration field value if set, zero value otherwise.
func (o *FeatureMasanielloDTO) GetSymbolsConfiguration() map[string]FeatureMasanielloDTO {
	if o == nil || IsNil(o.SymbolsConfiguration) {
		var ret map[string]FeatureMasanielloDTO
		return ret
	}
	return *o.SymbolsConfiguration
}

// GetSymbolsConfigurationOk returns a tuple with the SymbolsConfiguration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FeatureMasanielloDTO) GetSymbolsConfigurationOk() (*map[string]FeatureMasanielloDTO, bool) {
	if o == nil || IsNil(o.SymbolsConfiguration) {
		return nil, false
	}
	return o.SymbolsConfiguration, true
}

// HasSymbolsConfiguration returns a boolean if a field has been set.
func (o *FeatureMasanielloDTO) HasSymbolsConfiguration() bool {
	if o != nil && !IsNil(o.SymbolsConfiguration) {
		return true
	}

	return false
}

// SetSymbolsConfiguration gets a reference to the given map[string]FeatureMasanielloDTO and assigns it to the SymbolsConfiguration field.
func (o *FeatureMasanielloDTO) SetSymbolsConfiguration(v map[string]FeatureMasanielloDTO) {
	o.SymbolsConfiguration = &v
}

// GetTargetProfitPercentage returns the TargetProfitPercentage field value if set, zero value otherwise.
func (o *FeatureMasanielloDTO) GetTargetProfitPercentage() float32 {
	if o == nil || IsNil(o.TargetProfitPercentage) {
		var ret float32
		return ret
	}
	return *o.TargetProfitPercentage
}

// GetTargetProfitPercentageOk returns a tuple with the TargetProfitPercentage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FeatureMasanielloDTO) GetTargetProfitPercentageOk() (*float32, bool) {
	if o == nil || IsNil(o.TargetProfitPercentage) {
		return nil, false
	}
	return o.TargetProfitPercentage, true
}

// HasTargetProfitPercentage returns a boolean if a field has been set.
func (o *FeatureMasanielloDTO) HasTargetProfitPercentage() bool {
	if o != nil && !IsNil(o.TargetProfitPercentage) {
		return true
	}

	return false
}

// SetTargetProfitPercentage gets a reference to the given float32 and assigns it to the TargetProfitPercentage field.
func (o *FeatureMasanielloDTO) SetTargetProfitPercentage(v float32) {
	o.TargetProfitPercentage = &v
}

// GetTotalEvents returns the TotalEvents field value if set, zero value otherwise.
func (o *FeatureMasanielloDTO) GetTotalEvents() int32 {
	if o == nil || IsNil(o.TotalEvents) {
		var ret int32
		return ret
	}
	return *o.TotalEvents
}

// GetTotalEventsOk returns a tuple with the TotalEvents field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FeatureMasanielloDTO) GetTotalEventsOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalEvents) {
		return nil, false
	}
	return o.TotalEvents, true
}

// HasTotalEvents returns a boolean if a field has been set.
func (o *FeatureMasanielloDTO) HasTotalEvents() bool {
	if o != nil && !IsNil(o.TotalEvents) {
		return true
	}

	return false
}

// SetTotalEvents gets a reference to the given int32 and assigns it to the TotalEvents field.
func (o *FeatureMasanielloDTO) SetTotalEvents(v int32) {
	o.TotalEvents = &v
}

// GetUseHistoricalWinRate returns the UseHistoricalWinRate field value if set, zero value otherwise.
func (o *FeatureMasanielloDTO) GetUseHistoricalWinRate() bool {
	if o == nil || IsNil(o.UseHistoricalWinRate) {
		var ret bool
		return ret
	}
	return *o.UseHistoricalWinRate
}

// GetUseHistoricalWinRateOk returns a tuple with the UseHistoricalWinRate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FeatureMasanielloDTO) GetUseHistoricalWinRateOk() (*bool, bool) {
	if o == nil || IsNil(o.UseHistoricalWinRate) {
		return nil, false
	}
	return o.UseHistoricalWinRate, true
}

// HasUseHistoricalWinRate returns a boolean if a field has been set.
func (o *FeatureMasanielloDTO) HasUseHistoricalWinRate() bool {
	if o != nil && !IsNil(o.UseHistoricalWinRate) {
		return true
	}

	return false
}

// SetUseHistoricalWinRate gets a reference to the given bool and assigns it to the UseHistoricalWinRate field.
func (o *FeatureMasanielloDTO) SetUseHistoricalWinRate(v bool) {
	o.UseHistoricalWinRate = &v
}

// GetWinRateSmoothingFactor returns the WinRateSmoothingFactor field value if set, zero value otherwise.
func (o *FeatureMasanielloDTO) GetWinRateSmoothingFactor() float32 {
	if o == nil || IsNil(o.WinRateSmoothingFactor) {
		var ret float32
		return ret
	}
	return *o.WinRateSmoothingFactor
}

// GetWinRateSmoothingFactorOk returns a tuple with the WinRateSmoothingFactor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FeatureMasanielloDTO) GetWinRateSmoothingFactorOk() (*float32, bool) {
	if o == nil || IsNil(o.WinRateSmoothingFactor) {
		return nil, false
	}
	return o.WinRateSmoothingFactor, true
}

// HasWinRateSmoothingFactor returns a boolean if a field has been set.
func (o *FeatureMasanielloDTO) HasWinRateSmoothingFactor() bool {
	if o != nil && !IsNil(o.WinRateSmoothingFactor) {
		return true
	}

	return false
}

// SetWinRateSmoothingFactor gets a reference to the given float32 and assigns it to the WinRateSmoothingFactor field.
func (o *FeatureMasanielloDTO) SetWinRateSmoothingFactor(v float32) {
	o.WinRateSmoothingFactor = &v
}

// GetWinThresholdBase returns the WinThresholdBase field value
func (o *FeatureMasanielloDTO) GetWinThresholdBase() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.WinThresholdBase
}

// GetWinThresholdBaseOk returns a tuple with the WinThresholdBase field value
// and a boolean to check if the value has been set.
func (o *FeatureMasanielloDTO) GetWinThresholdBaseOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WinThresholdBase, true
}

// SetWinThresholdBase sets field value
func (o *FeatureMasanielloDTO) SetWinThresholdBase(v string) {
	o.WinThresholdBase = v
}

// GetWinThresholdPercentage returns the WinThresholdPercentage field value if set, zero value otherwise.
func (o *FeatureMasanielloDTO) GetWinThresholdPercentage() float32 {
	if o == nil || IsNil(o.WinThresholdPercentage) {
		var ret float32
		return ret
	}
	return *o.WinThresholdPercentage
}

// GetWinThresholdPercentageOk returns a tuple with the WinThresholdPercentage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FeatureMasanielloDTO) GetWinThresholdPercentageOk() (*float32, bool) {
	if o == nil || IsNil(o.WinThresholdPercentage) {
		return nil, false
	}
	return o.WinThresholdPercentage, true
}

// HasWinThresholdPercentage returns a boolean if a field has been set.
func (o *FeatureMasanielloDTO) HasWinThresholdPercentage() bool {
	if o != nil && !IsNil(o.WinThresholdPercentage) {
		return true
	}

	return false
}

// SetWinThresholdPercentage gets a reference to the given float32 and assigns it to the WinThresholdPercentage field.
func (o *FeatureMasanielloDTO) SetWinThresholdPercentage(v float32) {
	o.WinThresholdPercentage = &v
}

func (o FeatureMasanielloDTO) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FeatureMasanielloDTO) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AssumedPointRisk) {
		toSerialize["assumedPointRisk"] = o.AssumedPointRisk
	}
	if !IsNil(o.AutoResetOnSeriesComplete) {
		toSerialize["autoResetOnSeriesComplete"] = o.AutoResetOnSeriesComplete
	}
	if !IsNil(o.AutoTuneBoundsValid) {
		toSerialize["autoTuneBoundsValid"] = o.AutoTuneBoundsValid
	}
	toSerialize["bankrollBase"] = o.BankrollBase
	if !IsNil(o.BankrollPercentage) {
		toSerialize["bankrollPercentage"] = o.BankrollPercentage
	}
	if !IsNil(o.CooldownAfterResetMinutes) {
		toSerialize["cooldownAfterResetMinutes"] = o.CooldownAfterResetMinutes
	}
	if !IsNil(o.ExcludeBreakEvenTrades) {
		toSerialize["excludeBreakEvenTrades"] = o.ExcludeBreakEvenTrades
	}
	if !IsNil(o.ExpectedLossRMultiple) {
		toSerialize["expectedLossRMultiple"] = o.ExpectedLossRMultiple
	}
	if !IsNil(o.ExpectedPayoutFactor) {
		toSerialize["expectedPayoutFactor"] = o.ExpectedPayoutFactor
	}
	if !IsNil(o.ExpectedRMultiple) {
		toSerialize["expectedRMultiple"] = o.ExpectedRMultiple
	}
	if !IsNil(o.ExpectedWins) {
		toSerialize["expectedWins"] = o.ExpectedWins
	}
	if !IsNil(o.ExpectedWinsValid) {
		toSerialize["expectedWinsValid"] = o.ExpectedWinsValid
	}
	toSerialize["lotRoundingMode"] = o.LotRoundingMode
	if !IsNil(o.LotStep) {
		toSerialize["lotStep"] = o.LotStep
	}
	if !IsNil(o.MaxConsecutiveLosses) {
		toSerialize["maxConsecutiveLosses"] = o.MaxConsecutiveLosses
	}
	if !IsNil(o.MaxExpectedWins) {
		toSerialize["maxExpectedWins"] = o.MaxExpectedWins
	}
	if !IsNil(o.MaximumLotSize) {
		toSerialize["maximumLotSize"] = o.MaximumLotSize
	}
	if !IsNil(o.MinExpectedWins) {
		toSerialize["minExpectedWins"] = o.MinExpectedWins
	}
	if !IsNil(o.MinimumLotSize) {
		toSerialize["minimumLotSize"] = o.MinimumLotSize
	}
	if !IsNil(o.MinimumTradesForHistoricalWinRate) {
		toSerialize["minimumTradesForHistoricalWinRate"] = o.MinimumTradesForHistoricalWinRate
	}
	toSerialize["outcomePolicy"] = o.OutcomePolicy
	toSerialize["partialWinPolicy"] = o.PartialWinPolicy
	toSerialize["payoutModel"] = o.PayoutModel
	if !IsNil(o.ResetOnBankrollDepleted) {
		toSerialize["resetOnBankrollDepleted"] = o.ResetOnBankrollDepleted
	}
	if !IsNil(o.ResetOnTargetReached) {
		toSerialize["resetOnTargetReached"] = o.ResetOnTargetReached
	}
	if !IsNil(o.StatisticsLookBackDays) {
		toSerialize["statisticsLookBackDays"] = o.StatisticsLookBackDays
	}
	if !IsNil(o.SymbolsConfiguration) {
		toSerialize["symbolsConfiguration"] = o.SymbolsConfiguration
	}
	if !IsNil(o.TargetProfitPercentage) {
		toSerialize["targetProfitPercentage"] = o.TargetProfitPercentage
	}
	if !IsNil(o.TotalEvents) {
		toSerialize["totalEvents"] = o.TotalEvents
	}
	if !IsNil(o.UseHistoricalWinRate) {
		toSerialize["useHistoricalWinRate"] = o.UseHistoricalWinRate
	}
	if !IsNil(o.WinRateSmoothingFactor) {
		toSerialize["winRateSmoothingFactor"] = o.WinRateSmoothingFactor
	}
	toSerialize["winThresholdBase"] = o.WinThresholdBase
	if !IsNil(o.WinThresholdPercentage) {
		toSerialize["winThresholdPercentage"] = o.WinThresholdPercentage
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *FeatureMasanielloDTO) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"bankrollBase",
		"lotRoundingMode",
		"outcomePolicy",
		"partialWinPolicy",
		"payoutModel",
		"winThresholdBase",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFeatureMasanielloDTO := _FeatureMasanielloDTO{}

	err = json.Unmarshal(data, &varFeatureMasanielloDTO)

	if err != nil {
		return err
	}

	*o = FeatureMasanielloDTO(varFeatureMasanielloDTO)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "assumedPointRisk")
		delete(additionalProperties, "autoResetOnSeriesComplete")
		delete(additionalProperties, "autoTuneBoundsValid")
		delete(additionalProperties, "bankrollBase")
		delete(additionalProperties, "bankrollPercentage")
		delete(additionalProperties, "cooldownAfterResetMinutes")
		delete(additionalProperties, "excludeBreakEvenTrades")
		delete(additionalProperties, "expectedLossRMultiple")
		delete(additionalProperties, "expectedPayoutFactor")
		delete(additionalProperties, "expectedRMultiple")
		delete(additionalProperties, "expectedWins")
		delete(additionalProperties, "expectedWinsValid")
		delete(additionalProperties, "lotRoundingMode")
		delete(additionalProperties, "lotStep")
		delete(additionalProperties, "maxConsecutiveLosses")
		delete(additionalProperties, "maxExpectedWins")
		delete(additionalProperties, "maximumLotSize")
		delete(additionalProperties, "minExpectedWins")
		delete(additionalProperties, "minimumLotSize")
		delete(additionalProperties, "minimumTradesForHistoricalWinRate")
		delete(additionalProperties, "outcomePolicy")
		delete(additionalProperties, "partialWinPolicy")
		delete(additionalProperties, "payoutModel")
		delete(additionalProperties, "resetOnBankrollDepleted")
		delete(additionalProperties, "resetOnTargetReached")
		delete(additionalProperties, "statisticsLookBackDays")
		delete(additionalProperties, "symbolsConfiguration")
		delete(additionalProperties, "targetProfitPercentage")
		delete(additionalProperties, "totalEvents")
		delete(additionalProperties, "useHistoricalWinRate")
		delete(additionalProperties, "winRateSmoothingFactor")
		delete(additionalProperties, "winThresholdBase")
		delete(additionalProperties, "winThresholdPercentage")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableFeatureMasanielloDTO struct {
	value *FeatureMasanielloDTO
	isSet bool
}

func (v NullableFeatureMasanielloDTO) Get() *FeatureMasanielloDTO {
	return v.value
}

func (v *NullableFeatureMasanielloDTO) Set(val *FeatureMasanielloDTO) {
	v.value = val
	v.isSet = true
}

func (v NullableFeatureMasanielloDTO) IsSet() bool {
	return v.isSet
}

func (v *NullableFeatureMasanielloDTO) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFeatureMasanielloDTO(val *FeatureMasanielloDTO) *NullableFeatureMasanielloDTO {
	return &NullableFeatureMasanielloDTO{value: val, isSet: true}
}

func (v NullableFeatureMasanielloDTO) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFeatureMasanielloDTO) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
