/*
MetaCopier API

Explore the power of the MetaCopier API! Our RESTful API offers scalable and secure access to accounts, projects, and more. Get started quickly with authentication, explore endpoints, and access code samples in various languages.<br/><br/>All dates are in ISO 8601<br/><br/>This API is not designed for real-time communication purposes. For instance, continuously polling account information such as open positions every second is not recommended.<br/><br/>Our frontend uses this API, so you can look at the requests on our frontend for examples.

API version: 1.2.5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package metacopier

import (
	"encoding/json"
	"fmt"
)

// checks if the StrategyDTO type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StrategyDTO{}

// StrategyDTO struct for StrategyDTO
type StrategyDTO struct {
	Active bool    `json:"active"`
	Id     *string `json:"id,omitempty"`
	// You can define a positive number as key. This key will be saved in the \"magic number\" field for each trade
	Key                  int32  `json:"key"`
	Name                 string `json:"name"`
	ProjectId            string `json:"projectId"`
	AdditionalProperties map[string]interface{}
}

type _StrategyDTO StrategyDTO

// NewStrategyDTO instantiates a new StrategyDTO object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStrategyDTO(active bool, key int32, name string, projectId string) *StrategyDTO {
	this := StrategyDTO{}
	this.Active = active
	this.Key = key
	this.Name = name
	this.ProjectId = projectId
	return &this
}

// NewStrategyDTOWithDefaults instantiates a new StrategyDTO object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStrategyDTOWithDefaults() *StrategyDTO {
	this := StrategyDTO{}
	return &this
}

// GetActive returns the Active field value
func (o *StrategyDTO) GetActive() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Active
}

// GetActiveOk returns a tuple with the Active field value
// and a boolean to check if the value has been set.
func (o *StrategyDTO) GetActiveOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Active, true
}

// SetActive sets field value
func (o *StrategyDTO) SetActive(v bool) {
	o.Active = v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *StrategyDTO) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StrategyDTO) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *StrategyDTO) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *StrategyDTO) SetId(v string) {
	o.Id = &v
}

// GetKey returns the Key field value
func (o *StrategyDTO) GetKey() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Key
}

// GetKeyOk returns a tuple with the Key field value
// and a boolean to check if the value has been set.
func (o *StrategyDTO) GetKeyOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Key, true
}

// SetKey sets field value
func (o *StrategyDTO) SetKey(v int32) {
	o.Key = v
}

// GetName returns the Name field value
func (o *StrategyDTO) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *StrategyDTO) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *StrategyDTO) SetName(v string) {
	o.Name = v
}

// GetProjectId returns the ProjectId field value
func (o *StrategyDTO) GetProjectId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProjectId
}

// GetProjectIdOk returns a tuple with the ProjectId field value
// and a boolean to check if the value has been set.
func (o *StrategyDTO) GetProjectIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProjectId, true
}

// SetProjectId sets field value
func (o *StrategyDTO) SetProjectId(v string) {
	o.ProjectId = v
}

func (o StrategyDTO) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StrategyDTO) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["active"] = o.Active
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	toSerialize["key"] = o.Key
	toSerialize["name"] = o.Name
	toSerialize["projectId"] = o.ProjectId

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *StrategyDTO) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"active",
		"key",
		"name",
		"projectId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varStrategyDTO := _StrategyDTO{}

	err = json.Unmarshal(data, &varStrategyDTO)

	if err != nil {
		return err
	}

	*o = StrategyDTO(varStrategyDTO)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "active")
		delete(additionalProperties, "id")
		delete(additionalProperties, "key")
		delete(additionalProperties, "name")
		delete(additionalProperties, "projectId")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableStrategyDTO struct {
	value *StrategyDTO
	isSet bool
}

func (v NullableStrategyDTO) Get() *StrategyDTO {
	return v.value
}

func (v *NullableStrategyDTO) Set(val *StrategyDTO) {
	v.value = val
	v.isSet = true
}

func (v NullableStrategyDTO) IsSet() bool {
	return v.isSet
}

func (v *NullableStrategyDTO) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStrategyDTO(val *StrategyDTO) *NullableStrategyDTO {
	return &NullableStrategyDTO{value: val, isSet: true}
}

func (v NullableStrategyDTO) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStrategyDTO) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
