/*
MetaCopier API

Explore the power of the MetaCopier API! Our RESTful API offers scalable and secure access to accounts, projects, and more. Get started quickly with authentication, explore endpoints, and access code samples in various languages.<br/><br/>All dates are in ISO 8601<br/><br/>This API is not designed for real-time communication purposes. For instance, continuously polling account information such as open positions every second is not recommended.<br/><br/>Our frontend uses this API, so you can look at the requests on our frontend for examples.

API version: 1.2.5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package metacopier

import (
	"encoding/json"
)

// checks if the FeatureMaxLotSizeDTO type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FeatureMaxLotSizeDTO{}

// FeatureMaxLotSizeDTO DTO for max lot size feature (copier)
type FeatureMaxLotSizeDTO struct {
	// If true, the max lot size check will compare against the master account's original position lot size instead of the calculated lot size. Only active when skipIfExceedsMax is true.
	CheckMasterLotSize *bool `json:"checkMasterLotSize,omitempty"`
	// Sets the global max lot size for each position for all symbols. If a position exceeds this size, it will be adjusted to this max limit. This setting will override the copier's max lot size. A value of 0 means deactivated.
	MaxLotSize *float32 `json:"maxLotSize,omitempty"`
	// If true, positions that exceed the max lot size will be skipped instead of being limited to the max lot size.
	SkipIfExceedsMax *bool `json:"skipIfExceedsMax,omitempty"`
	// Defines the max lot size per symbol.
	SymbolsConfiguration *map[string]FeatureMaxLotSizeDTO `json:"symbolsConfiguration,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _FeatureMaxLotSizeDTO FeatureMaxLotSizeDTO

// NewFeatureMaxLotSizeDTO instantiates a new FeatureMaxLotSizeDTO object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFeatureMaxLotSizeDTO() *FeatureMaxLotSizeDTO {
	this := FeatureMaxLotSizeDTO{}
	var checkMasterLotSize bool = false
	this.CheckMasterLotSize = &checkMasterLotSize
	var maxLotSize float32 = 0.0
	this.MaxLotSize = &maxLotSize
	var skipIfExceedsMax bool = false
	this.SkipIfExceedsMax = &skipIfExceedsMax
	return &this
}

// NewFeatureMaxLotSizeDTOWithDefaults instantiates a new FeatureMaxLotSizeDTO object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFeatureMaxLotSizeDTOWithDefaults() *FeatureMaxLotSizeDTO {
	this := FeatureMaxLotSizeDTO{}
	var checkMasterLotSize bool = false
	this.CheckMasterLotSize = &checkMasterLotSize
	var maxLotSize float32 = 0.0
	this.MaxLotSize = &maxLotSize
	var skipIfExceedsMax bool = false
	this.SkipIfExceedsMax = &skipIfExceedsMax
	return &this
}

// GetCheckMasterLotSize returns the CheckMasterLotSize field value if set, zero value otherwise.
func (o *FeatureMaxLotSizeDTO) GetCheckMasterLotSize() bool {
	if o == nil || IsNil(o.CheckMasterLotSize) {
		var ret bool
		return ret
	}
	return *o.CheckMasterLotSize
}

// GetCheckMasterLotSizeOk returns a tuple with the CheckMasterLotSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FeatureMaxLotSizeDTO) GetCheckMasterLotSizeOk() (*bool, bool) {
	if o == nil || IsNil(o.CheckMasterLotSize) {
		return nil, false
	}
	return o.CheckMasterLotSize, true
}

// HasCheckMasterLotSize returns a boolean if a field has been set.
func (o *FeatureMaxLotSizeDTO) HasCheckMasterLotSize() bool {
	if o != nil && !IsNil(o.CheckMasterLotSize) {
		return true
	}

	return false
}

// SetCheckMasterLotSize gets a reference to the given bool and assigns it to the CheckMasterLotSize field.
func (o *FeatureMaxLotSizeDTO) SetCheckMasterLotSize(v bool) {
	o.CheckMasterLotSize = &v
}

// GetMaxLotSize returns the MaxLotSize field value if set, zero value otherwise.
func (o *FeatureMaxLotSizeDTO) GetMaxLotSize() float32 {
	if o == nil || IsNil(o.MaxLotSize) {
		var ret float32
		return ret
	}
	return *o.MaxLotSize
}

// GetMaxLotSizeOk returns a tuple with the MaxLotSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FeatureMaxLotSizeDTO) GetMaxLotSizeOk() (*float32, bool) {
	if o == nil || IsNil(o.MaxLotSize) {
		return nil, false
	}
	return o.MaxLotSize, true
}

// HasMaxLotSize returns a boolean if a field has been set.
func (o *FeatureMaxLotSizeDTO) HasMaxLotSize() bool {
	if o != nil && !IsNil(o.MaxLotSize) {
		return true
	}

	return false
}

// SetMaxLotSize gets a reference to the given float32 and assigns it to the MaxLotSize field.
func (o *FeatureMaxLotSizeDTO) SetMaxLotSize(v float32) {
	o.MaxLotSize = &v
}

// GetSkipIfExceedsMax returns the SkipIfExceedsMax field value if set, zero value otherwise.
func (o *FeatureMaxLotSizeDTO) GetSkipIfExceedsMax() bool {
	if o == nil || IsNil(o.SkipIfExceedsMax) {
		var ret bool
		return ret
	}
	return *o.SkipIfExceedsMax
}

// GetSkipIfExceedsMaxOk returns a tuple with the SkipIfExceedsMax field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FeatureMaxLotSizeDTO) GetSkipIfExceedsMaxOk() (*bool, bool) {
	if o == nil || IsNil(o.SkipIfExceedsMax) {
		return nil, false
	}
	return o.SkipIfExceedsMax, true
}

// HasSkipIfExceedsMax returns a boolean if a field has been set.
func (o *FeatureMaxLotSizeDTO) HasSkipIfExceedsMax() bool {
	if o != nil && !IsNil(o.SkipIfExceedsMax) {
		return true
	}

	return false
}

// SetSkipIfExceedsMax gets a reference to the given bool and assigns it to the SkipIfExceedsMax field.
func (o *FeatureMaxLotSizeDTO) SetSkipIfExceedsMax(v bool) {
	o.SkipIfExceedsMax = &v
}

// GetSymbolsConfiguration returns the SymbolsConfiguration field value if set, zero value otherwise.
func (o *FeatureMaxLotSizeDTO) GetSymbolsConfiguration() map[string]FeatureMaxLotSizeDTO {
	if o == nil || IsNil(o.SymbolsConfiguration) {
		var ret map[string]FeatureMaxLotSizeDTO
		return ret
	}
	return *o.SymbolsConfiguration
}

// GetSymbolsConfigurationOk returns a tuple with the SymbolsConfiguration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FeatureMaxLotSizeDTO) GetSymbolsConfigurationOk() (*map[string]FeatureMaxLotSizeDTO, bool) {
	if o == nil || IsNil(o.SymbolsConfiguration) {
		return nil, false
	}
	return o.SymbolsConfiguration, true
}

// HasSymbolsConfiguration returns a boolean if a field has been set.
func (o *FeatureMaxLotSizeDTO) HasSymbolsConfiguration() bool {
	if o != nil && !IsNil(o.SymbolsConfiguration) {
		return true
	}

	return false
}

// SetSymbolsConfiguration gets a reference to the given map[string]FeatureMaxLotSizeDTO and assigns it to the SymbolsConfiguration field.
func (o *FeatureMaxLotSizeDTO) SetSymbolsConfiguration(v map[string]FeatureMaxLotSizeDTO) {
	o.SymbolsConfiguration = &v
}

func (o FeatureMaxLotSizeDTO) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FeatureMaxLotSizeDTO) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CheckMasterLotSize) {
		toSerialize["checkMasterLotSize"] = o.CheckMasterLotSize
	}
	if !IsNil(o.MaxLotSize) {
		toSerialize["maxLotSize"] = o.MaxLotSize
	}
	if !IsNil(o.SkipIfExceedsMax) {
		toSerialize["skipIfExceedsMax"] = o.SkipIfExceedsMax
	}
	if !IsNil(o.SymbolsConfiguration) {
		toSerialize["symbolsConfiguration"] = o.SymbolsConfiguration
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *FeatureMaxLotSizeDTO) UnmarshalJSON(data []byte) (err error) {
	varFeatureMaxLotSizeDTO := _FeatureMaxLotSizeDTO{}

	err = json.Unmarshal(data, &varFeatureMaxLotSizeDTO)

	if err != nil {
		return err
	}

	*o = FeatureMaxLotSizeDTO(varFeatureMaxLotSizeDTO)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "checkMasterLotSize")
		delete(additionalProperties, "maxLotSize")
		delete(additionalProperties, "skipIfExceedsMax")
		delete(additionalProperties, "symbolsConfiguration")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableFeatureMaxLotSizeDTO struct {
	value *FeatureMaxLotSizeDTO
	isSet bool
}

func (v NullableFeatureMaxLotSizeDTO) Get() *FeatureMaxLotSizeDTO {
	return v.value
}

func (v *NullableFeatureMaxLotSizeDTO) Set(val *FeatureMaxLotSizeDTO) {
	v.value = val
	v.isSet = true
}

func (v NullableFeatureMaxLotSizeDTO) IsSet() bool {
	return v.isSet
}

func (v *NullableFeatureMaxLotSizeDTO) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFeatureMaxLotSizeDTO(val *FeatureMaxLotSizeDTO) *NullableFeatureMaxLotSizeDTO {
	return &NullableFeatureMaxLotSizeDTO{value: val, isSet: true}
}

func (v NullableFeatureMaxLotSizeDTO) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFeatureMaxLotSizeDTO) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
