/*
MetaCopier API

Explore the power of the MetaCopier API! Our RESTful API offers scalable and secure access to accounts, projects, and more. Get started quickly with authentication, explore endpoints, and access code samples in various languages.<br/><br/>All dates are in ISO 8601<br/><br/>This API is not designed for real-time communication purposes. For instance, continuously polling account information such as open positions every second is not recommended.<br/><br/>Our frontend uses this API, so you can look at the requests on our frontend for examples.

API version: 1.2.5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package metacopier

import (
	"encoding/json"
)

// checks if the FeatureFallbackSettingDTO type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FeatureFallbackSettingDTO{}

// FeatureFallbackSettingDTO DTO for fallback setting feature (account and project). If applied to a project, the fallback behavior will be applied to all accounts within that project.
type FeatureFallbackSettingDTO struct {
	// A list of allowed regions to which the account can be moved if an error or issue occurs. When an account is moved, another IP address will be assigned to it. If the list is empty, all regions are allowed.
	AllowedRegions []RegionDTO `json:"allowedRegions,omitempty"`
	// Indicates whether fallback behavior is disabled. If set to true, the account will not be moved to another region in case of errors or issues. If fallback is enabled, another IP address will be assigned to the account when it is moved.
	NoFallback           *bool `json:"noFallback,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _FeatureFallbackSettingDTO FeatureFallbackSettingDTO

// NewFeatureFallbackSettingDTO instantiates a new FeatureFallbackSettingDTO object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFeatureFallbackSettingDTO() *FeatureFallbackSettingDTO {
	this := FeatureFallbackSettingDTO{}
	var noFallback bool = false
	this.NoFallback = &noFallback
	return &this
}

// NewFeatureFallbackSettingDTOWithDefaults instantiates a new FeatureFallbackSettingDTO object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFeatureFallbackSettingDTOWithDefaults() *FeatureFallbackSettingDTO {
	this := FeatureFallbackSettingDTO{}
	var noFallback bool = false
	this.NoFallback = &noFallback
	return &this
}

// GetAllowedRegions returns the AllowedRegions field value if set, zero value otherwise.
func (o *FeatureFallbackSettingDTO) GetAllowedRegions() []RegionDTO {
	if o == nil || IsNil(o.AllowedRegions) {
		var ret []RegionDTO
		return ret
	}
	return o.AllowedRegions
}

// GetAllowedRegionsOk returns a tuple with the AllowedRegions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FeatureFallbackSettingDTO) GetAllowedRegionsOk() ([]RegionDTO, bool) {
	if o == nil || IsNil(o.AllowedRegions) {
		return nil, false
	}
	return o.AllowedRegions, true
}

// HasAllowedRegions returns a boolean if a field has been set.
func (o *FeatureFallbackSettingDTO) HasAllowedRegions() bool {
	if o != nil && !IsNil(o.AllowedRegions) {
		return true
	}

	return false
}

// SetAllowedRegions gets a reference to the given []RegionDTO and assigns it to the AllowedRegions field.
func (o *FeatureFallbackSettingDTO) SetAllowedRegions(v []RegionDTO) {
	o.AllowedRegions = v
}

// GetNoFallback returns the NoFallback field value if set, zero value otherwise.
func (o *FeatureFallbackSettingDTO) GetNoFallback() bool {
	if o == nil || IsNil(o.NoFallback) {
		var ret bool
		return ret
	}
	return *o.NoFallback
}

// GetNoFallbackOk returns a tuple with the NoFallback field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FeatureFallbackSettingDTO) GetNoFallbackOk() (*bool, bool) {
	if o == nil || IsNil(o.NoFallback) {
		return nil, false
	}
	return o.NoFallback, true
}

// HasNoFallback returns a boolean if a field has been set.
func (o *FeatureFallbackSettingDTO) HasNoFallback() bool {
	if o != nil && !IsNil(o.NoFallback) {
		return true
	}

	return false
}

// SetNoFallback gets a reference to the given bool and assigns it to the NoFallback field.
func (o *FeatureFallbackSettingDTO) SetNoFallback(v bool) {
	o.NoFallback = &v
}

func (o FeatureFallbackSettingDTO) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FeatureFallbackSettingDTO) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AllowedRegions) {
		toSerialize["allowedRegions"] = o.AllowedRegions
	}
	if !IsNil(o.NoFallback) {
		toSerialize["noFallback"] = o.NoFallback
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *FeatureFallbackSettingDTO) UnmarshalJSON(data []byte) (err error) {
	varFeatureFallbackSettingDTO := _FeatureFallbackSettingDTO{}

	err = json.Unmarshal(data, &varFeatureFallbackSettingDTO)

	if err != nil {
		return err
	}

	*o = FeatureFallbackSettingDTO(varFeatureFallbackSettingDTO)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "allowedRegions")
		delete(additionalProperties, "noFallback")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableFeatureFallbackSettingDTO struct {
	value *FeatureFallbackSettingDTO
	isSet bool
}

func (v NullableFeatureFallbackSettingDTO) Get() *FeatureFallbackSettingDTO {
	return v.value
}

func (v *NullableFeatureFallbackSettingDTO) Set(val *FeatureFallbackSettingDTO) {
	v.value = val
	v.isSet = true
}

func (v NullableFeatureFallbackSettingDTO) IsSet() bool {
	return v.isSet
}

func (v *NullableFeatureFallbackSettingDTO) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFeatureFallbackSettingDTO(val *FeatureFallbackSettingDTO) *NullableFeatureFallbackSettingDTO {
	return &NullableFeatureFallbackSettingDTO{value: val, isSet: true}
}

func (v NullableFeatureFallbackSettingDTO) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFeatureFallbackSettingDTO) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
