/*
MetaCopier API

Explore the power of the MetaCopier API! Our RESTful API offers scalable and secure access to accounts, projects, and more. Get started quickly with authentication, explore endpoints, and access code samples in various languages.<br/><br/>All dates are in ISO 8601<br/><br/>This API is not designed for real-time communication purposes. For instance, continuously polling account information such as open positions every second is not recommended.<br/><br/>Our frontend uses this API, so you can look at the requests on our frontend for examples.

API version: 1.2.5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package metacopier

import (
	"encoding/json"
)

// checks if the FeatureTpSlManagementDTO type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FeatureTpSlManagementDTO{}

// FeatureTpSlManagementDTO DTO for TP/SL management feature (copier) (PRO)
type FeatureTpSlManagementDTO struct {
	// Additional points to add to the existing SL value. Useful for prop firms.
	AdditionalSlPoints *int32 `json:"additionalSlPoints,omitempty"`
	// Additional points to add to the existing TP value. Useful for prop firms.
	AdditionalTpPoints *int32 `json:"additionalTpPoints,omitempty"`
	// Indicates whether the TP/SL should be adjusted based on the distance from the master trade's values, maintaining the same distance on both the master and the slave trades.
	AdjustWithMasterDistance *bool `json:"adjustWithMasterDistance,omitempty"`
	// Fixed Stop Loss value in points. Set to 0 if not used.
	FixedSlInPoints *int32 `json:"fixedSlInPoints,omitempty"`
	// Fixed Take Profit value in points. Set to 0 if not used.
	FixedTpInPoints *int32 `json:"fixedTpInPoints,omitempty"`
	// If true, the TP/SL values are set once and are never modified afterward.
	LockTpSl *bool `json:"lockTpSl,omitempty"`
	// If true, removes the Stop Loss (SL) from the copied positions.
	RemoveSl *bool `json:"removeSl,omitempty"`
	// If true, removes the Take Profit (TP) from the copied positions.
	RemoveTp *bool `json:"removeTp,omitempty"`
	// Defines TP/SL management per symbol. Symbol configuration has priority over the general configuration.
	SymbolsConfiguration *map[string]FeatureTpSlManagementDTO `json:"symbolsConfiguration,omitempty"`
}

// NewFeatureTpSlManagementDTO instantiates a new FeatureTpSlManagementDTO object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFeatureTpSlManagementDTO() *FeatureTpSlManagementDTO {
	this := FeatureTpSlManagementDTO{}
	var adjustWithMasterDistance bool = false
	this.AdjustWithMasterDistance = &adjustWithMasterDistance
	var lockTpSl bool = false
	this.LockTpSl = &lockTpSl
	var removeSl bool = false
	this.RemoveSl = &removeSl
	var removeTp bool = false
	this.RemoveTp = &removeTp
	return &this
}

// NewFeatureTpSlManagementDTOWithDefaults instantiates a new FeatureTpSlManagementDTO object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFeatureTpSlManagementDTOWithDefaults() *FeatureTpSlManagementDTO {
	this := FeatureTpSlManagementDTO{}
	var adjustWithMasterDistance bool = false
	this.AdjustWithMasterDistance = &adjustWithMasterDistance
	var lockTpSl bool = false
	this.LockTpSl = &lockTpSl
	var removeSl bool = false
	this.RemoveSl = &removeSl
	var removeTp bool = false
	this.RemoveTp = &removeTp
	return &this
}

// GetAdditionalSlPoints returns the AdditionalSlPoints field value if set, zero value otherwise.
func (o *FeatureTpSlManagementDTO) GetAdditionalSlPoints() int32 {
	if o == nil || IsNil(o.AdditionalSlPoints) {
		var ret int32
		return ret
	}
	return *o.AdditionalSlPoints
}

// GetAdditionalSlPointsOk returns a tuple with the AdditionalSlPoints field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FeatureTpSlManagementDTO) GetAdditionalSlPointsOk() (*int32, bool) {
	if o == nil || IsNil(o.AdditionalSlPoints) {
		return nil, false
	}
	return o.AdditionalSlPoints, true
}

// HasAdditionalSlPoints returns a boolean if a field has been set.
func (o *FeatureTpSlManagementDTO) HasAdditionalSlPoints() bool {
	if o != nil && !IsNil(o.AdditionalSlPoints) {
		return true
	}

	return false
}

// SetAdditionalSlPoints gets a reference to the given int32 and assigns it to the AdditionalSlPoints field.
func (o *FeatureTpSlManagementDTO) SetAdditionalSlPoints(v int32) {
	o.AdditionalSlPoints = &v
}

// GetAdditionalTpPoints returns the AdditionalTpPoints field value if set, zero value otherwise.
func (o *FeatureTpSlManagementDTO) GetAdditionalTpPoints() int32 {
	if o == nil || IsNil(o.AdditionalTpPoints) {
		var ret int32
		return ret
	}
	return *o.AdditionalTpPoints
}

// GetAdditionalTpPointsOk returns a tuple with the AdditionalTpPoints field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FeatureTpSlManagementDTO) GetAdditionalTpPointsOk() (*int32, bool) {
	if o == nil || IsNil(o.AdditionalTpPoints) {
		return nil, false
	}
	return o.AdditionalTpPoints, true
}

// HasAdditionalTpPoints returns a boolean if a field has been set.
func (o *FeatureTpSlManagementDTO) HasAdditionalTpPoints() bool {
	if o != nil && !IsNil(o.AdditionalTpPoints) {
		return true
	}

	return false
}

// SetAdditionalTpPoints gets a reference to the given int32 and assigns it to the AdditionalTpPoints field.
func (o *FeatureTpSlManagementDTO) SetAdditionalTpPoints(v int32) {
	o.AdditionalTpPoints = &v
}

// GetAdjustWithMasterDistance returns the AdjustWithMasterDistance field value if set, zero value otherwise.
func (o *FeatureTpSlManagementDTO) GetAdjustWithMasterDistance() bool {
	if o == nil || IsNil(o.AdjustWithMasterDistance) {
		var ret bool
		return ret
	}
	return *o.AdjustWithMasterDistance
}

// GetAdjustWithMasterDistanceOk returns a tuple with the AdjustWithMasterDistance field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FeatureTpSlManagementDTO) GetAdjustWithMasterDistanceOk() (*bool, bool) {
	if o == nil || IsNil(o.AdjustWithMasterDistance) {
		return nil, false
	}
	return o.AdjustWithMasterDistance, true
}

// HasAdjustWithMasterDistance returns a boolean if a field has been set.
func (o *FeatureTpSlManagementDTO) HasAdjustWithMasterDistance() bool {
	if o != nil && !IsNil(o.AdjustWithMasterDistance) {
		return true
	}

	return false
}

// SetAdjustWithMasterDistance gets a reference to the given bool and assigns it to the AdjustWithMasterDistance field.
func (o *FeatureTpSlManagementDTO) SetAdjustWithMasterDistance(v bool) {
	o.AdjustWithMasterDistance = &v
}

// GetFixedSlInPoints returns the FixedSlInPoints field value if set, zero value otherwise.
func (o *FeatureTpSlManagementDTO) GetFixedSlInPoints() int32 {
	if o == nil || IsNil(o.FixedSlInPoints) {
		var ret int32
		return ret
	}
	return *o.FixedSlInPoints
}

// GetFixedSlInPointsOk returns a tuple with the FixedSlInPoints field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FeatureTpSlManagementDTO) GetFixedSlInPointsOk() (*int32, bool) {
	if o == nil || IsNil(o.FixedSlInPoints) {
		return nil, false
	}
	return o.FixedSlInPoints, true
}

// HasFixedSlInPoints returns a boolean if a field has been set.
func (o *FeatureTpSlManagementDTO) HasFixedSlInPoints() bool {
	if o != nil && !IsNil(o.FixedSlInPoints) {
		return true
	}

	return false
}

// SetFixedSlInPoints gets a reference to the given int32 and assigns it to the FixedSlInPoints field.
func (o *FeatureTpSlManagementDTO) SetFixedSlInPoints(v int32) {
	o.FixedSlInPoints = &v
}

// GetFixedTpInPoints returns the FixedTpInPoints field value if set, zero value otherwise.
func (o *FeatureTpSlManagementDTO) GetFixedTpInPoints() int32 {
	if o == nil || IsNil(o.FixedTpInPoints) {
		var ret int32
		return ret
	}
	return *o.FixedTpInPoints
}

// GetFixedTpInPointsOk returns a tuple with the FixedTpInPoints field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FeatureTpSlManagementDTO) GetFixedTpInPointsOk() (*int32, bool) {
	if o == nil || IsNil(o.FixedTpInPoints) {
		return nil, false
	}
	return o.FixedTpInPoints, true
}

// HasFixedTpInPoints returns a boolean if a field has been set.
func (o *FeatureTpSlManagementDTO) HasFixedTpInPoints() bool {
	if o != nil && !IsNil(o.FixedTpInPoints) {
		return true
	}

	return false
}

// SetFixedTpInPoints gets a reference to the given int32 and assigns it to the FixedTpInPoints field.
func (o *FeatureTpSlManagementDTO) SetFixedTpInPoints(v int32) {
	o.FixedTpInPoints = &v
}

// GetLockTpSl returns the LockTpSl field value if set, zero value otherwise.
func (o *FeatureTpSlManagementDTO) GetLockTpSl() bool {
	if o == nil || IsNil(o.LockTpSl) {
		var ret bool
		return ret
	}
	return *o.LockTpSl
}

// GetLockTpSlOk returns a tuple with the LockTpSl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FeatureTpSlManagementDTO) GetLockTpSlOk() (*bool, bool) {
	if o == nil || IsNil(o.LockTpSl) {
		return nil, false
	}
	return o.LockTpSl, true
}

// HasLockTpSl returns a boolean if a field has been set.
func (o *FeatureTpSlManagementDTO) HasLockTpSl() bool {
	if o != nil && !IsNil(o.LockTpSl) {
		return true
	}

	return false
}

// SetLockTpSl gets a reference to the given bool and assigns it to the LockTpSl field.
func (o *FeatureTpSlManagementDTO) SetLockTpSl(v bool) {
	o.LockTpSl = &v
}

// GetRemoveSl returns the RemoveSl field value if set, zero value otherwise.
func (o *FeatureTpSlManagementDTO) GetRemoveSl() bool {
	if o == nil || IsNil(o.RemoveSl) {
		var ret bool
		return ret
	}
	return *o.RemoveSl
}

// GetRemoveSlOk returns a tuple with the RemoveSl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FeatureTpSlManagementDTO) GetRemoveSlOk() (*bool, bool) {
	if o == nil || IsNil(o.RemoveSl) {
		return nil, false
	}
	return o.RemoveSl, true
}

// HasRemoveSl returns a boolean if a field has been set.
func (o *FeatureTpSlManagementDTO) HasRemoveSl() bool {
	if o != nil && !IsNil(o.RemoveSl) {
		return true
	}

	return false
}

// SetRemoveSl gets a reference to the given bool and assigns it to the RemoveSl field.
func (o *FeatureTpSlManagementDTO) SetRemoveSl(v bool) {
	o.RemoveSl = &v
}

// GetRemoveTp returns the RemoveTp field value if set, zero value otherwise.
func (o *FeatureTpSlManagementDTO) GetRemoveTp() bool {
	if o == nil || IsNil(o.RemoveTp) {
		var ret bool
		return ret
	}
	return *o.RemoveTp
}

// GetRemoveTpOk returns a tuple with the RemoveTp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FeatureTpSlManagementDTO) GetRemoveTpOk() (*bool, bool) {
	if o == nil || IsNil(o.RemoveTp) {
		return nil, false
	}
	return o.RemoveTp, true
}

// HasRemoveTp returns a boolean if a field has been set.
func (o *FeatureTpSlManagementDTO) HasRemoveTp() bool {
	if o != nil && !IsNil(o.RemoveTp) {
		return true
	}

	return false
}

// SetRemoveTp gets a reference to the given bool and assigns it to the RemoveTp field.
func (o *FeatureTpSlManagementDTO) SetRemoveTp(v bool) {
	o.RemoveTp = &v
}

// GetSymbolsConfiguration returns the SymbolsConfiguration field value if set, zero value otherwise.
func (o *FeatureTpSlManagementDTO) GetSymbolsConfiguration() map[string]FeatureTpSlManagementDTO {
	if o == nil || IsNil(o.SymbolsConfiguration) {
		var ret map[string]FeatureTpSlManagementDTO
		return ret
	}
	return *o.SymbolsConfiguration
}

// GetSymbolsConfigurationOk returns a tuple with the SymbolsConfiguration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FeatureTpSlManagementDTO) GetSymbolsConfigurationOk() (*map[string]FeatureTpSlManagementDTO, bool) {
	if o == nil || IsNil(o.SymbolsConfiguration) {
		return nil, false
	}
	return o.SymbolsConfiguration, true
}

// HasSymbolsConfiguration returns a boolean if a field has been set.
func (o *FeatureTpSlManagementDTO) HasSymbolsConfiguration() bool {
	if o != nil && !IsNil(o.SymbolsConfiguration) {
		return true
	}

	return false
}

// SetSymbolsConfiguration gets a reference to the given map[string]FeatureTpSlManagementDTO and assigns it to the SymbolsConfiguration field.
func (o *FeatureTpSlManagementDTO) SetSymbolsConfiguration(v map[string]FeatureTpSlManagementDTO) {
	o.SymbolsConfiguration = &v
}

func (o FeatureTpSlManagementDTO) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FeatureTpSlManagementDTO) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AdditionalSlPoints) {
		toSerialize["additionalSlPoints"] = o.AdditionalSlPoints
	}
	if !IsNil(o.AdditionalTpPoints) {
		toSerialize["additionalTpPoints"] = o.AdditionalTpPoints
	}
	if !IsNil(o.AdjustWithMasterDistance) {
		toSerialize["adjustWithMasterDistance"] = o.AdjustWithMasterDistance
	}
	if !IsNil(o.FixedSlInPoints) {
		toSerialize["fixedSlInPoints"] = o.FixedSlInPoints
	}
	if !IsNil(o.FixedTpInPoints) {
		toSerialize["fixedTpInPoints"] = o.FixedTpInPoints
	}
	if !IsNil(o.LockTpSl) {
		toSerialize["lockTpSl"] = o.LockTpSl
	}
	if !IsNil(o.RemoveSl) {
		toSerialize["removeSl"] = o.RemoveSl
	}
	if !IsNil(o.RemoveTp) {
		toSerialize["removeTp"] = o.RemoveTp
	}
	if !IsNil(o.SymbolsConfiguration) {
		toSerialize["symbolsConfiguration"] = o.SymbolsConfiguration
	}
	return toSerialize, nil
}

type NullableFeatureTpSlManagementDTO struct {
	value *FeatureTpSlManagementDTO
	isSet bool
}

func (v NullableFeatureTpSlManagementDTO) Get() *FeatureTpSlManagementDTO {
	return v.value
}

func (v *NullableFeatureTpSlManagementDTO) Set(val *FeatureTpSlManagementDTO) {
	v.value = val
	v.isSet = true
}

func (v NullableFeatureTpSlManagementDTO) IsSet() bool {
	return v.isSet
}

func (v *NullableFeatureTpSlManagementDTO) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFeatureTpSlManagementDTO(val *FeatureTpSlManagementDTO) *NullableFeatureTpSlManagementDTO {
	return &NullableFeatureTpSlManagementDTO{value: val, isSet: true}
}

func (v NullableFeatureTpSlManagementDTO) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFeatureTpSlManagementDTO) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


