/*
MetaCopier API

Explore the power of the MetaCopier API! Our RESTful API offers scalable and secure access to accounts, projects, and more. Get started quickly with authentication, explore endpoints, and access code samples in various languages.<br/><br/>All dates are in ISO 8601<br/><br/>This API is not designed for real-time communication purposes. For instance, continuously polling account information such as open positions every second is not recommended.<br/><br/>Our frontend uses this API, so you can look at the requests on our frontend for examples.

API version: 1.2.5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package metacopier

import (
	"encoding/json"
)

// checks if the FeatureSkipPositionDTO type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FeatureSkipPositionDTO{}

// FeatureSkipPositionDTO DTO for skip position feature (copier)
type FeatureSkipPositionDTO struct {
	// If set to true and the master position does not define a Stop Loss (SL), the copier will skip copying the position to the slave account. This can be used to avoid trades without predefined risk management.
	IfSlNotDefined *bool `json:"ifSlNotDefined,omitempty"`
	// If set to true and the master position does not define a Take Profit (TP), the copier will skip copying the position to the slave account.
	IfTpNotDefined *bool `json:"ifTpNotDefined,omitempty"`
	// Specifies how the copier should evaluate SL and TP conditions. If set to AND, both conditions must be met to skip the position. If set to OR, either condition is enough to skip.
	LogicOperatorTpSl *string `json:"logicOperatorTpSl,omitempty"`
	// Defines skip position per symbol. Symbol configuration has priority over the general configuration.
	SymbolsConfiguration *map[string]FeatureSkipPositionDTO `json:"symbolsConfiguration,omitempty"`
}

// NewFeatureSkipPositionDTO instantiates a new FeatureSkipPositionDTO object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFeatureSkipPositionDTO() *FeatureSkipPositionDTO {
	this := FeatureSkipPositionDTO{}
	var ifSlNotDefined bool = false
	this.IfSlNotDefined = &ifSlNotDefined
	var ifTpNotDefined bool = false
	this.IfTpNotDefined = &ifTpNotDefined
	var logicOperatorTpSl string = "OR"
	this.LogicOperatorTpSl = &logicOperatorTpSl
	return &this
}

// NewFeatureSkipPositionDTOWithDefaults instantiates a new FeatureSkipPositionDTO object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFeatureSkipPositionDTOWithDefaults() *FeatureSkipPositionDTO {
	this := FeatureSkipPositionDTO{}
	var ifSlNotDefined bool = false
	this.IfSlNotDefined = &ifSlNotDefined
	var ifTpNotDefined bool = false
	this.IfTpNotDefined = &ifTpNotDefined
	var logicOperatorTpSl string = "OR"
	this.LogicOperatorTpSl = &logicOperatorTpSl
	return &this
}

// GetIfSlNotDefined returns the IfSlNotDefined field value if set, zero value otherwise.
func (o *FeatureSkipPositionDTO) GetIfSlNotDefined() bool {
	if o == nil || IsNil(o.IfSlNotDefined) {
		var ret bool
		return ret
	}
	return *o.IfSlNotDefined
}

// GetIfSlNotDefinedOk returns a tuple with the IfSlNotDefined field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FeatureSkipPositionDTO) GetIfSlNotDefinedOk() (*bool, bool) {
	if o == nil || IsNil(o.IfSlNotDefined) {
		return nil, false
	}
	return o.IfSlNotDefined, true
}

// HasIfSlNotDefined returns a boolean if a field has been set.
func (o *FeatureSkipPositionDTO) HasIfSlNotDefined() bool {
	if o != nil && !IsNil(o.IfSlNotDefined) {
		return true
	}

	return false
}

// SetIfSlNotDefined gets a reference to the given bool and assigns it to the IfSlNotDefined field.
func (o *FeatureSkipPositionDTO) SetIfSlNotDefined(v bool) {
	o.IfSlNotDefined = &v
}

// GetIfTpNotDefined returns the IfTpNotDefined field value if set, zero value otherwise.
func (o *FeatureSkipPositionDTO) GetIfTpNotDefined() bool {
	if o == nil || IsNil(o.IfTpNotDefined) {
		var ret bool
		return ret
	}
	return *o.IfTpNotDefined
}

// GetIfTpNotDefinedOk returns a tuple with the IfTpNotDefined field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FeatureSkipPositionDTO) GetIfTpNotDefinedOk() (*bool, bool) {
	if o == nil || IsNil(o.IfTpNotDefined) {
		return nil, false
	}
	return o.IfTpNotDefined, true
}

// HasIfTpNotDefined returns a boolean if a field has been set.
func (o *FeatureSkipPositionDTO) HasIfTpNotDefined() bool {
	if o != nil && !IsNil(o.IfTpNotDefined) {
		return true
	}

	return false
}

// SetIfTpNotDefined gets a reference to the given bool and assigns it to the IfTpNotDefined field.
func (o *FeatureSkipPositionDTO) SetIfTpNotDefined(v bool) {
	o.IfTpNotDefined = &v
}

// GetLogicOperatorTpSl returns the LogicOperatorTpSl field value if set, zero value otherwise.
func (o *FeatureSkipPositionDTO) GetLogicOperatorTpSl() string {
	if o == nil || IsNil(o.LogicOperatorTpSl) {
		var ret string
		return ret
	}
	return *o.LogicOperatorTpSl
}

// GetLogicOperatorTpSlOk returns a tuple with the LogicOperatorTpSl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FeatureSkipPositionDTO) GetLogicOperatorTpSlOk() (*string, bool) {
	if o == nil || IsNil(o.LogicOperatorTpSl) {
		return nil, false
	}
	return o.LogicOperatorTpSl, true
}

// HasLogicOperatorTpSl returns a boolean if a field has been set.
func (o *FeatureSkipPositionDTO) HasLogicOperatorTpSl() bool {
	if o != nil && !IsNil(o.LogicOperatorTpSl) {
		return true
	}

	return false
}

// SetLogicOperatorTpSl gets a reference to the given string and assigns it to the LogicOperatorTpSl field.
func (o *FeatureSkipPositionDTO) SetLogicOperatorTpSl(v string) {
	o.LogicOperatorTpSl = &v
}

// GetSymbolsConfiguration returns the SymbolsConfiguration field value if set, zero value otherwise.
func (o *FeatureSkipPositionDTO) GetSymbolsConfiguration() map[string]FeatureSkipPositionDTO {
	if o == nil || IsNil(o.SymbolsConfiguration) {
		var ret map[string]FeatureSkipPositionDTO
		return ret
	}
	return *o.SymbolsConfiguration
}

// GetSymbolsConfigurationOk returns a tuple with the SymbolsConfiguration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FeatureSkipPositionDTO) GetSymbolsConfigurationOk() (*map[string]FeatureSkipPositionDTO, bool) {
	if o == nil || IsNil(o.SymbolsConfiguration) {
		return nil, false
	}
	return o.SymbolsConfiguration, true
}

// HasSymbolsConfiguration returns a boolean if a field has been set.
func (o *FeatureSkipPositionDTO) HasSymbolsConfiguration() bool {
	if o != nil && !IsNil(o.SymbolsConfiguration) {
		return true
	}

	return false
}

// SetSymbolsConfiguration gets a reference to the given map[string]FeatureSkipPositionDTO and assigns it to the SymbolsConfiguration field.
func (o *FeatureSkipPositionDTO) SetSymbolsConfiguration(v map[string]FeatureSkipPositionDTO) {
	o.SymbolsConfiguration = &v
}

func (o FeatureSkipPositionDTO) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FeatureSkipPositionDTO) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.IfSlNotDefined) {
		toSerialize["ifSlNotDefined"] = o.IfSlNotDefined
	}
	if !IsNil(o.IfTpNotDefined) {
		toSerialize["ifTpNotDefined"] = o.IfTpNotDefined
	}
	if !IsNil(o.LogicOperatorTpSl) {
		toSerialize["logicOperatorTpSl"] = o.LogicOperatorTpSl
	}
	if !IsNil(o.SymbolsConfiguration) {
		toSerialize["symbolsConfiguration"] = o.SymbolsConfiguration
	}
	return toSerialize, nil
}

type NullableFeatureSkipPositionDTO struct {
	value *FeatureSkipPositionDTO
	isSet bool
}

func (v NullableFeatureSkipPositionDTO) Get() *FeatureSkipPositionDTO {
	return v.value
}

func (v *NullableFeatureSkipPositionDTO) Set(val *FeatureSkipPositionDTO) {
	v.value = val
	v.isSet = true
}

func (v NullableFeatureSkipPositionDTO) IsSet() bool {
	return v.isSet
}

func (v *NullableFeatureSkipPositionDTO) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFeatureSkipPositionDTO(val *FeatureSkipPositionDTO) *NullableFeatureSkipPositionDTO {
	return &NullableFeatureSkipPositionDTO{value: val, isSet: true}
}

func (v NullableFeatureSkipPositionDTO) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFeatureSkipPositionDTO) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


