/*
MetaCopier API

Explore the power of the MetaCopier API! Our RESTful API offers scalable and secure access to accounts, projects, and more. Get started quickly with authentication, explore endpoints, and access code samples in various languages.<br/><br/>All dates are in ISO 8601<br/><br/>This API is not designed for real-time communication purposes. For instance, continuously polling account information such as open positions every second is not recommended.<br/><br/>Our frontend uses this API, so you can look at the requests on our frontend for examples.

API version: 1.2.5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package metacopier

import (
	"encoding/json"
)

// checks if the ForecastDTO type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ForecastDTO{}

// ForecastDTO struct for ForecastDTO
type ForecastDTO struct {
	Currency             *CurrencyTypeDTO `json:"currency,omitempty"`
	Positions            []string         `json:"positions,omitempty"`
	Total                *float32         `json:"total,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ForecastDTO ForecastDTO

// NewForecastDTO instantiates a new ForecastDTO object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewForecastDTO() *ForecastDTO {
	this := ForecastDTO{}
	return &this
}

// NewForecastDTOWithDefaults instantiates a new ForecastDTO object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewForecastDTOWithDefaults() *ForecastDTO {
	this := ForecastDTO{}
	return &this
}

// GetCurrency returns the Currency field value if set, zero value otherwise.
func (o *ForecastDTO) GetCurrency() CurrencyTypeDTO {
	if o == nil || IsNil(o.Currency) {
		var ret CurrencyTypeDTO
		return ret
	}
	return *o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ForecastDTO) GetCurrencyOk() (*CurrencyTypeDTO, bool) {
	if o == nil || IsNil(o.Currency) {
		return nil, false
	}
	return o.Currency, true
}

// HasCurrency returns a boolean if a field has been set.
func (o *ForecastDTO) HasCurrency() bool {
	if o != nil && !IsNil(o.Currency) {
		return true
	}

	return false
}

// SetCurrency gets a reference to the given CurrencyTypeDTO and assigns it to the Currency field.
func (o *ForecastDTO) SetCurrency(v CurrencyTypeDTO) {
	o.Currency = &v
}

// GetPositions returns the Positions field value if set, zero value otherwise.
func (o *ForecastDTO) GetPositions() []string {
	if o == nil || IsNil(o.Positions) {
		var ret []string
		return ret
	}
	return o.Positions
}

// GetPositionsOk returns a tuple with the Positions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ForecastDTO) GetPositionsOk() ([]string, bool) {
	if o == nil || IsNil(o.Positions) {
		return nil, false
	}
	return o.Positions, true
}

// HasPositions returns a boolean if a field has been set.
func (o *ForecastDTO) HasPositions() bool {
	if o != nil && !IsNil(o.Positions) {
		return true
	}

	return false
}

// SetPositions gets a reference to the given []string and assigns it to the Positions field.
func (o *ForecastDTO) SetPositions(v []string) {
	o.Positions = v
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *ForecastDTO) GetTotal() float32 {
	if o == nil || IsNil(o.Total) {
		var ret float32
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ForecastDTO) GetTotalOk() (*float32, bool) {
	if o == nil || IsNil(o.Total) {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *ForecastDTO) HasTotal() bool {
	if o != nil && !IsNil(o.Total) {
		return true
	}

	return false
}

// SetTotal gets a reference to the given float32 and assigns it to the Total field.
func (o *ForecastDTO) SetTotal(v float32) {
	o.Total = &v
}

func (o ForecastDTO) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ForecastDTO) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Currency) {
		toSerialize["currency"] = o.Currency
	}
	if !IsNil(o.Positions) {
		toSerialize["positions"] = o.Positions
	}
	if !IsNil(o.Total) {
		toSerialize["total"] = o.Total
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ForecastDTO) UnmarshalJSON(data []byte) (err error) {
	varForecastDTO := _ForecastDTO{}

	err = json.Unmarshal(data, &varForecastDTO)

	if err != nil {
		return err
	}

	*o = ForecastDTO(varForecastDTO)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "currency")
		delete(additionalProperties, "positions")
		delete(additionalProperties, "total")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableForecastDTO struct {
	value *ForecastDTO
	isSet bool
}

func (v NullableForecastDTO) Get() *ForecastDTO {
	return v.value
}

func (v *NullableForecastDTO) Set(val *ForecastDTO) {
	v.value = val
	v.isSet = true
}

func (v NullableForecastDTO) IsSet() bool {
	return v.isSet
}

func (v *NullableForecastDTO) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableForecastDTO(val *ForecastDTO) *NullableForecastDTO {
	return &NullableForecastDTO{value: val, isSet: true}
}

func (v NullableForecastDTO) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableForecastDTO) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
