/*
MetaCopier API

Explore the power of the MetaCopier API! Our RESTful API offers scalable and secure access to accounts, projects, and more. Get started quickly with authentication, explore endpoints, and access code samples in various languages.<br/><br/>All dates are in ISO 8601<br/><br/>This API is not designed for real-time communication purposes. For instance, continuously polling account information such as open positions every second is not recommended.<br/><br/>Our frontend uses this API, so you can look at the requests on our frontend for examples.

API version: 1.2.5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package metacopier

import (
	"encoding/json"
	"time"
)

// checks if the MarketQuoteDTO type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MarketQuoteDTO{}

// MarketQuoteDTO struct for MarketQuoteDTO
type MarketQuoteDTO struct {
	// Ask price
	Ask *float32 `json:"ask,omitempty"`
	// Bid price
	Bid *float32 `json:"bid,omitempty"`
	// Symbol name
	Symbol *string `json:"symbol,omitempty"`
	// Quote timestamp (ISO 8601)
	Timestamp *time.Time `json:"timestamp,omitempty"`
}

// NewMarketQuoteDTO instantiates a new MarketQuoteDTO object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMarketQuoteDTO() *MarketQuoteDTO {
	this := MarketQuoteDTO{}
	return &this
}

// NewMarketQuoteDTOWithDefaults instantiates a new MarketQuoteDTO object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMarketQuoteDTOWithDefaults() *MarketQuoteDTO {
	this := MarketQuoteDTO{}
	return &this
}

// GetAsk returns the Ask field value if set, zero value otherwise.
func (o *MarketQuoteDTO) GetAsk() float32 {
	if o == nil || IsNil(o.Ask) {
		var ret float32
		return ret
	}
	return *o.Ask
}

// GetAskOk returns a tuple with the Ask field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MarketQuoteDTO) GetAskOk() (*float32, bool) {
	if o == nil || IsNil(o.Ask) {
		return nil, false
	}
	return o.Ask, true
}

// HasAsk returns a boolean if a field has been set.
func (o *MarketQuoteDTO) HasAsk() bool {
	if o != nil && !IsNil(o.Ask) {
		return true
	}

	return false
}

// SetAsk gets a reference to the given float32 and assigns it to the Ask field.
func (o *MarketQuoteDTO) SetAsk(v float32) {
	o.Ask = &v
}

// GetBid returns the Bid field value if set, zero value otherwise.
func (o *MarketQuoteDTO) GetBid() float32 {
	if o == nil || IsNil(o.Bid) {
		var ret float32
		return ret
	}
	return *o.Bid
}

// GetBidOk returns a tuple with the Bid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MarketQuoteDTO) GetBidOk() (*float32, bool) {
	if o == nil || IsNil(o.Bid) {
		return nil, false
	}
	return o.Bid, true
}

// HasBid returns a boolean if a field has been set.
func (o *MarketQuoteDTO) HasBid() bool {
	if o != nil && !IsNil(o.Bid) {
		return true
	}

	return false
}

// SetBid gets a reference to the given float32 and assigns it to the Bid field.
func (o *MarketQuoteDTO) SetBid(v float32) {
	o.Bid = &v
}

// GetSymbol returns the Symbol field value if set, zero value otherwise.
func (o *MarketQuoteDTO) GetSymbol() string {
	if o == nil || IsNil(o.Symbol) {
		var ret string
		return ret
	}
	return *o.Symbol
}

// GetSymbolOk returns a tuple with the Symbol field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MarketQuoteDTO) GetSymbolOk() (*string, bool) {
	if o == nil || IsNil(o.Symbol) {
		return nil, false
	}
	return o.Symbol, true
}

// HasSymbol returns a boolean if a field has been set.
func (o *MarketQuoteDTO) HasSymbol() bool {
	if o != nil && !IsNil(o.Symbol) {
		return true
	}

	return false
}

// SetSymbol gets a reference to the given string and assigns it to the Symbol field.
func (o *MarketQuoteDTO) SetSymbol(v string) {
	o.Symbol = &v
}

// GetTimestamp returns the Timestamp field value if set, zero value otherwise.
func (o *MarketQuoteDTO) GetTimestamp() time.Time {
	if o == nil || IsNil(o.Timestamp) {
		var ret time.Time
		return ret
	}
	return *o.Timestamp
}

// GetTimestampOk returns a tuple with the Timestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MarketQuoteDTO) GetTimestampOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Timestamp) {
		return nil, false
	}
	return o.Timestamp, true
}

// HasTimestamp returns a boolean if a field has been set.
func (o *MarketQuoteDTO) HasTimestamp() bool {
	if o != nil && !IsNil(o.Timestamp) {
		return true
	}

	return false
}

// SetTimestamp gets a reference to the given time.Time and assigns it to the Timestamp field.
func (o *MarketQuoteDTO) SetTimestamp(v time.Time) {
	o.Timestamp = &v
}

func (o MarketQuoteDTO) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MarketQuoteDTO) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Ask) {
		toSerialize["ask"] = o.Ask
	}
	if !IsNil(o.Bid) {
		toSerialize["bid"] = o.Bid
	}
	if !IsNil(o.Symbol) {
		toSerialize["symbol"] = o.Symbol
	}
	if !IsNil(o.Timestamp) {
		toSerialize["timestamp"] = o.Timestamp
	}
	return toSerialize, nil
}

type NullableMarketQuoteDTO struct {
	value *MarketQuoteDTO
	isSet bool
}

func (v NullableMarketQuoteDTO) Get() *MarketQuoteDTO {
	return v.value
}

func (v *NullableMarketQuoteDTO) Set(val *MarketQuoteDTO) {
	v.value = val
	v.isSet = true
}

func (v NullableMarketQuoteDTO) IsSet() bool {
	return v.isSet
}

func (v *NullableMarketQuoteDTO) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMarketQuoteDTO(val *MarketQuoteDTO) *NullableMarketQuoteDTO {
	return &NullableMarketQuoteDTO{value: val, isSet: true}
}

func (v NullableMarketQuoteDTO) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMarketQuoteDTO) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


