/*
MetaCopier API

Explore the power of the MetaCopier API! Our RESTful API offers scalable and secure access to accounts, projects, and more. Get started quickly with authentication, explore endpoints, and access code samples in various languages.<br/><br/>All dates are in ISO 8601<br/><br/>This API is not designed for real-time communication purposes. For instance, continuously polling account information such as open positions every second is not recommended.<br/><br/>Our frontend uses this API, so you can look at the requests on our frontend for examples.

API version: 1.2.5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package metacopier

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the FeatureTradingWindowsDTO type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FeatureTradingWindowsDTO{}

// FeatureTradingWindowsDTO DTO for the trading windows feature (copier/account) (PRO)
type FeatureTradingWindowsDTO struct {
	// Indicates whether to close all open positions at the end of the trading window.
	ClosePositionsAtWindowEnd *bool `json:"closePositionsAtWindowEnd,omitempty"`
	// Defines the trading windows configuration per symbol.
	SymbolsConfiguration *map[string]FeatureTradingWindowsDTO `json:"symbolsConfiguration,omitempty"`
	// Indicates whether trades outside the defined windows are temporarily skipped until the next trading window starts. This option is only applicable to copiers.
	TemporarilySkipUntilNextWindow *bool `json:"temporarilySkipUntilNextWindow,omitempty"`
	// List of trading windows defined by the user.
	TradingWindows []TradingWindowDTO `json:"tradingWindows"`
}

type _FeatureTradingWindowsDTO FeatureTradingWindowsDTO

// NewFeatureTradingWindowsDTO instantiates a new FeatureTradingWindowsDTO object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFeatureTradingWindowsDTO(tradingWindows []TradingWindowDTO) *FeatureTradingWindowsDTO {
	this := FeatureTradingWindowsDTO{}
	var closePositionsAtWindowEnd bool = true
	this.ClosePositionsAtWindowEnd = &closePositionsAtWindowEnd
	var temporarilySkipUntilNextWindow bool = false
	this.TemporarilySkipUntilNextWindow = &temporarilySkipUntilNextWindow
	this.TradingWindows = tradingWindows
	return &this
}

// NewFeatureTradingWindowsDTOWithDefaults instantiates a new FeatureTradingWindowsDTO object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFeatureTradingWindowsDTOWithDefaults() *FeatureTradingWindowsDTO {
	this := FeatureTradingWindowsDTO{}
	var closePositionsAtWindowEnd bool = true
	this.ClosePositionsAtWindowEnd = &closePositionsAtWindowEnd
	var temporarilySkipUntilNextWindow bool = false
	this.TemporarilySkipUntilNextWindow = &temporarilySkipUntilNextWindow
	return &this
}

// GetClosePositionsAtWindowEnd returns the ClosePositionsAtWindowEnd field value if set, zero value otherwise.
func (o *FeatureTradingWindowsDTO) GetClosePositionsAtWindowEnd() bool {
	if o == nil || IsNil(o.ClosePositionsAtWindowEnd) {
		var ret bool
		return ret
	}
	return *o.ClosePositionsAtWindowEnd
}

// GetClosePositionsAtWindowEndOk returns a tuple with the ClosePositionsAtWindowEnd field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FeatureTradingWindowsDTO) GetClosePositionsAtWindowEndOk() (*bool, bool) {
	if o == nil || IsNil(o.ClosePositionsAtWindowEnd) {
		return nil, false
	}
	return o.ClosePositionsAtWindowEnd, true
}

// HasClosePositionsAtWindowEnd returns a boolean if a field has been set.
func (o *FeatureTradingWindowsDTO) HasClosePositionsAtWindowEnd() bool {
	if o != nil && !IsNil(o.ClosePositionsAtWindowEnd) {
		return true
	}

	return false
}

// SetClosePositionsAtWindowEnd gets a reference to the given bool and assigns it to the ClosePositionsAtWindowEnd field.
func (o *FeatureTradingWindowsDTO) SetClosePositionsAtWindowEnd(v bool) {
	o.ClosePositionsAtWindowEnd = &v
}

// GetSymbolsConfiguration returns the SymbolsConfiguration field value if set, zero value otherwise.
func (o *FeatureTradingWindowsDTO) GetSymbolsConfiguration() map[string]FeatureTradingWindowsDTO {
	if o == nil || IsNil(o.SymbolsConfiguration) {
		var ret map[string]FeatureTradingWindowsDTO
		return ret
	}
	return *o.SymbolsConfiguration
}

// GetSymbolsConfigurationOk returns a tuple with the SymbolsConfiguration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FeatureTradingWindowsDTO) GetSymbolsConfigurationOk() (*map[string]FeatureTradingWindowsDTO, bool) {
	if o == nil || IsNil(o.SymbolsConfiguration) {
		return nil, false
	}
	return o.SymbolsConfiguration, true
}

// HasSymbolsConfiguration returns a boolean if a field has been set.
func (o *FeatureTradingWindowsDTO) HasSymbolsConfiguration() bool {
	if o != nil && !IsNil(o.SymbolsConfiguration) {
		return true
	}

	return false
}

// SetSymbolsConfiguration gets a reference to the given map[string]FeatureTradingWindowsDTO and assigns it to the SymbolsConfiguration field.
func (o *FeatureTradingWindowsDTO) SetSymbolsConfiguration(v map[string]FeatureTradingWindowsDTO) {
	o.SymbolsConfiguration = &v
}

// GetTemporarilySkipUntilNextWindow returns the TemporarilySkipUntilNextWindow field value if set, zero value otherwise.
func (o *FeatureTradingWindowsDTO) GetTemporarilySkipUntilNextWindow() bool {
	if o == nil || IsNil(o.TemporarilySkipUntilNextWindow) {
		var ret bool
		return ret
	}
	return *o.TemporarilySkipUntilNextWindow
}

// GetTemporarilySkipUntilNextWindowOk returns a tuple with the TemporarilySkipUntilNextWindow field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FeatureTradingWindowsDTO) GetTemporarilySkipUntilNextWindowOk() (*bool, bool) {
	if o == nil || IsNil(o.TemporarilySkipUntilNextWindow) {
		return nil, false
	}
	return o.TemporarilySkipUntilNextWindow, true
}

// HasTemporarilySkipUntilNextWindow returns a boolean if a field has been set.
func (o *FeatureTradingWindowsDTO) HasTemporarilySkipUntilNextWindow() bool {
	if o != nil && !IsNil(o.TemporarilySkipUntilNextWindow) {
		return true
	}

	return false
}

// SetTemporarilySkipUntilNextWindow gets a reference to the given bool and assigns it to the TemporarilySkipUntilNextWindow field.
func (o *FeatureTradingWindowsDTO) SetTemporarilySkipUntilNextWindow(v bool) {
	o.TemporarilySkipUntilNextWindow = &v
}

// GetTradingWindows returns the TradingWindows field value
func (o *FeatureTradingWindowsDTO) GetTradingWindows() []TradingWindowDTO {
	if o == nil {
		var ret []TradingWindowDTO
		return ret
	}

	return o.TradingWindows
}

// GetTradingWindowsOk returns a tuple with the TradingWindows field value
// and a boolean to check if the value has been set.
func (o *FeatureTradingWindowsDTO) GetTradingWindowsOk() ([]TradingWindowDTO, bool) {
	if o == nil {
		return nil, false
	}
	return o.TradingWindows, true
}

// SetTradingWindows sets field value
func (o *FeatureTradingWindowsDTO) SetTradingWindows(v []TradingWindowDTO) {
	o.TradingWindows = v
}

func (o FeatureTradingWindowsDTO) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FeatureTradingWindowsDTO) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ClosePositionsAtWindowEnd) {
		toSerialize["closePositionsAtWindowEnd"] = o.ClosePositionsAtWindowEnd
	}
	if !IsNil(o.SymbolsConfiguration) {
		toSerialize["symbolsConfiguration"] = o.SymbolsConfiguration
	}
	if !IsNil(o.TemporarilySkipUntilNextWindow) {
		toSerialize["temporarilySkipUntilNextWindow"] = o.TemporarilySkipUntilNextWindow
	}
	toSerialize["tradingWindows"] = o.TradingWindows
	return toSerialize, nil
}

func (o *FeatureTradingWindowsDTO) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"tradingWindows",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFeatureTradingWindowsDTO := _FeatureTradingWindowsDTO{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varFeatureTradingWindowsDTO)

	if err != nil {
		return err
	}

	*o = FeatureTradingWindowsDTO(varFeatureTradingWindowsDTO)

	return err
}

type NullableFeatureTradingWindowsDTO struct {
	value *FeatureTradingWindowsDTO
	isSet bool
}

func (v NullableFeatureTradingWindowsDTO) Get() *FeatureTradingWindowsDTO {
	return v.value
}

func (v *NullableFeatureTradingWindowsDTO) Set(val *FeatureTradingWindowsDTO) {
	v.value = val
	v.isSet = true
}

func (v NullableFeatureTradingWindowsDTO) IsSet() bool {
	return v.isSet
}

func (v *NullableFeatureTradingWindowsDTO) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFeatureTradingWindowsDTO(val *FeatureTradingWindowsDTO) *NullableFeatureTradingWindowsDTO {
	return &NullableFeatureTradingWindowsDTO{value: val, isSet: true}
}

func (v NullableFeatureTradingWindowsDTO) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFeatureTradingWindowsDTO) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


