/*
MetaCopier API

Explore the power of the MetaCopier API! Our RESTful API offers scalable and secure access to accounts, projects, and more. Get started quickly with authentication, explore endpoints, and access code samples in various languages.<br/><br/>All dates are in ISO 8601<br/><br/>This API is not designed for real-time communication purposes. For instance, continuously polling account information such as open positions every second is not recommended.<br/><br/>Our frontend uses this API, so you can look at the requests on our frontend for examples.

API version: 1.2.5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package metacopier

import (
	"encoding/json"
	"time"
)

// checks if the CustomerDTO type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CustomerDTO{}

// CustomerDTO struct for CustomerDTO
type CustomerDTO struct {
	Blocked *bool `json:"blocked,omitempty"`
	// ISO 8601
	Created *time.Time `json:"created,omitempty"`
	Email *string `json:"email,omitempty"`
	Id *int32 `json:"id,omitempty"`
	Kyc *bool `json:"kyc,omitempty"`
	PayoutMethod *PayoutDTO `json:"payoutMethod,omitempty"`
	// Permission level for this customer in the project
	PermissionType *string `json:"permissionType,omitempty"`
	// ISO 8601
	Tos *time.Time `json:"tos,omitempty"`
}

// NewCustomerDTO instantiates a new CustomerDTO object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCustomerDTO() *CustomerDTO {
	this := CustomerDTO{}
	return &this
}

// NewCustomerDTOWithDefaults instantiates a new CustomerDTO object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCustomerDTOWithDefaults() *CustomerDTO {
	this := CustomerDTO{}
	return &this
}

// GetBlocked returns the Blocked field value if set, zero value otherwise.
func (o *CustomerDTO) GetBlocked() bool {
	if o == nil || IsNil(o.Blocked) {
		var ret bool
		return ret
	}
	return *o.Blocked
}

// GetBlockedOk returns a tuple with the Blocked field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerDTO) GetBlockedOk() (*bool, bool) {
	if o == nil || IsNil(o.Blocked) {
		return nil, false
	}
	return o.Blocked, true
}

// HasBlocked returns a boolean if a field has been set.
func (o *CustomerDTO) HasBlocked() bool {
	if o != nil && !IsNil(o.Blocked) {
		return true
	}

	return false
}

// SetBlocked gets a reference to the given bool and assigns it to the Blocked field.
func (o *CustomerDTO) SetBlocked(v bool) {
	o.Blocked = &v
}

// GetCreated returns the Created field value if set, zero value otherwise.
func (o *CustomerDTO) GetCreated() time.Time {
	if o == nil || IsNil(o.Created) {
		var ret time.Time
		return ret
	}
	return *o.Created
}

// GetCreatedOk returns a tuple with the Created field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerDTO) GetCreatedOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Created) {
		return nil, false
	}
	return o.Created, true
}

// HasCreated returns a boolean if a field has been set.
func (o *CustomerDTO) HasCreated() bool {
	if o != nil && !IsNil(o.Created) {
		return true
	}

	return false
}

// SetCreated gets a reference to the given time.Time and assigns it to the Created field.
func (o *CustomerDTO) SetCreated(v time.Time) {
	o.Created = &v
}

// GetEmail returns the Email field value if set, zero value otherwise.
func (o *CustomerDTO) GetEmail() string {
	if o == nil || IsNil(o.Email) {
		var ret string
		return ret
	}
	return *o.Email
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerDTO) GetEmailOk() (*string, bool) {
	if o == nil || IsNil(o.Email) {
		return nil, false
	}
	return o.Email, true
}

// HasEmail returns a boolean if a field has been set.
func (o *CustomerDTO) HasEmail() bool {
	if o != nil && !IsNil(o.Email) {
		return true
	}

	return false
}

// SetEmail gets a reference to the given string and assigns it to the Email field.
func (o *CustomerDTO) SetEmail(v string) {
	o.Email = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *CustomerDTO) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerDTO) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *CustomerDTO) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *CustomerDTO) SetId(v int32) {
	o.Id = &v
}

// GetKyc returns the Kyc field value if set, zero value otherwise.
func (o *CustomerDTO) GetKyc() bool {
	if o == nil || IsNil(o.Kyc) {
		var ret bool
		return ret
	}
	return *o.Kyc
}

// GetKycOk returns a tuple with the Kyc field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerDTO) GetKycOk() (*bool, bool) {
	if o == nil || IsNil(o.Kyc) {
		return nil, false
	}
	return o.Kyc, true
}

// HasKyc returns a boolean if a field has been set.
func (o *CustomerDTO) HasKyc() bool {
	if o != nil && !IsNil(o.Kyc) {
		return true
	}

	return false
}

// SetKyc gets a reference to the given bool and assigns it to the Kyc field.
func (o *CustomerDTO) SetKyc(v bool) {
	o.Kyc = &v
}

// GetPayoutMethod returns the PayoutMethod field value if set, zero value otherwise.
func (o *CustomerDTO) GetPayoutMethod() PayoutDTO {
	if o == nil || IsNil(o.PayoutMethod) {
		var ret PayoutDTO
		return ret
	}
	return *o.PayoutMethod
}

// GetPayoutMethodOk returns a tuple with the PayoutMethod field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerDTO) GetPayoutMethodOk() (*PayoutDTO, bool) {
	if o == nil || IsNil(o.PayoutMethod) {
		return nil, false
	}
	return o.PayoutMethod, true
}

// HasPayoutMethod returns a boolean if a field has been set.
func (o *CustomerDTO) HasPayoutMethod() bool {
	if o != nil && !IsNil(o.PayoutMethod) {
		return true
	}

	return false
}

// SetPayoutMethod gets a reference to the given PayoutDTO and assigns it to the PayoutMethod field.
func (o *CustomerDTO) SetPayoutMethod(v PayoutDTO) {
	o.PayoutMethod = &v
}

// GetPermissionType returns the PermissionType field value if set, zero value otherwise.
func (o *CustomerDTO) GetPermissionType() string {
	if o == nil || IsNil(o.PermissionType) {
		var ret string
		return ret
	}
	return *o.PermissionType
}

// GetPermissionTypeOk returns a tuple with the PermissionType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerDTO) GetPermissionTypeOk() (*string, bool) {
	if o == nil || IsNil(o.PermissionType) {
		return nil, false
	}
	return o.PermissionType, true
}

// HasPermissionType returns a boolean if a field has been set.
func (o *CustomerDTO) HasPermissionType() bool {
	if o != nil && !IsNil(o.PermissionType) {
		return true
	}

	return false
}

// SetPermissionType gets a reference to the given string and assigns it to the PermissionType field.
func (o *CustomerDTO) SetPermissionType(v string) {
	o.PermissionType = &v
}

// GetTos returns the Tos field value if set, zero value otherwise.
func (o *CustomerDTO) GetTos() time.Time {
	if o == nil || IsNil(o.Tos) {
		var ret time.Time
		return ret
	}
	return *o.Tos
}

// GetTosOk returns a tuple with the Tos field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustomerDTO) GetTosOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Tos) {
		return nil, false
	}
	return o.Tos, true
}

// HasTos returns a boolean if a field has been set.
func (o *CustomerDTO) HasTos() bool {
	if o != nil && !IsNil(o.Tos) {
		return true
	}

	return false
}

// SetTos gets a reference to the given time.Time and assigns it to the Tos field.
func (o *CustomerDTO) SetTos(v time.Time) {
	o.Tos = &v
}

func (o CustomerDTO) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CustomerDTO) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Blocked) {
		toSerialize["blocked"] = o.Blocked
	}
	if !IsNil(o.Created) {
		toSerialize["created"] = o.Created
	}
	if !IsNil(o.Email) {
		toSerialize["email"] = o.Email
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Kyc) {
		toSerialize["kyc"] = o.Kyc
	}
	if !IsNil(o.PayoutMethod) {
		toSerialize["payoutMethod"] = o.PayoutMethod
	}
	if !IsNil(o.PermissionType) {
		toSerialize["permissionType"] = o.PermissionType
	}
	if !IsNil(o.Tos) {
		toSerialize["tos"] = o.Tos
	}
	return toSerialize, nil
}

type NullableCustomerDTO struct {
	value *CustomerDTO
	isSet bool
}

func (v NullableCustomerDTO) Get() *CustomerDTO {
	return v.value
}

func (v *NullableCustomerDTO) Set(val *CustomerDTO) {
	v.value = val
	v.isSet = true
}

func (v NullableCustomerDTO) IsSet() bool {
	return v.isSet
}

func (v *NullableCustomerDTO) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCustomerDTO(val *CustomerDTO) *NullableCustomerDTO {
	return &NullableCustomerDTO{value: val, isSet: true}
}

func (v NullableCustomerDTO) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCustomerDTO) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


