/*
MetaCopier API

Explore the power of the MetaCopier API! Our RESTful API offers scalable and secure access to accounts, projects, and more. Get started quickly with authentication, explore endpoints, and access code samples in various languages.<br/><br/>All dates are in ISO 8601<br/><br/>This API is not designed for real-time communication purposes. For instance, continuously polling account information such as open positions every second is not recommended.<br/><br/>Our frontend uses this API, so you can look at the requests on our frontend for examples.

API version: 1.2.5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package metacopier

import (
	"encoding/json"
)

// checks if the FieldMetadataDTO type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FieldMetadataDTO{}

// FieldMetadataDTO Represents a field in a DTO that can be included/excluded via API key access policy
type FieldMetadataDTO struct {
	// Field description from @Schema annotation if available
	Description *string `json:"description,omitempty"`
	// The DTO class name this field belongs to
	DtoClassName *string `json:"dtoClassName,omitempty"`
	// Field name
	FieldName *string `json:"fieldName,omitempty"`
	// Field Java type
	FieldType            *string `json:"fieldType,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _FieldMetadataDTO FieldMetadataDTO

// NewFieldMetadataDTO instantiates a new FieldMetadataDTO object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFieldMetadataDTO() *FieldMetadataDTO {
	this := FieldMetadataDTO{}
	return &this
}

// NewFieldMetadataDTOWithDefaults instantiates a new FieldMetadataDTO object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFieldMetadataDTOWithDefaults() *FieldMetadataDTO {
	this := FieldMetadataDTO{}
	return &this
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *FieldMetadataDTO) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FieldMetadataDTO) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *FieldMetadataDTO) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *FieldMetadataDTO) SetDescription(v string) {
	o.Description = &v
}

// GetDtoClassName returns the DtoClassName field value if set, zero value otherwise.
func (o *FieldMetadataDTO) GetDtoClassName() string {
	if o == nil || IsNil(o.DtoClassName) {
		var ret string
		return ret
	}
	return *o.DtoClassName
}

// GetDtoClassNameOk returns a tuple with the DtoClassName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FieldMetadataDTO) GetDtoClassNameOk() (*string, bool) {
	if o == nil || IsNil(o.DtoClassName) {
		return nil, false
	}
	return o.DtoClassName, true
}

// HasDtoClassName returns a boolean if a field has been set.
func (o *FieldMetadataDTO) HasDtoClassName() bool {
	if o != nil && !IsNil(o.DtoClassName) {
		return true
	}

	return false
}

// SetDtoClassName gets a reference to the given string and assigns it to the DtoClassName field.
func (o *FieldMetadataDTO) SetDtoClassName(v string) {
	o.DtoClassName = &v
}

// GetFieldName returns the FieldName field value if set, zero value otherwise.
func (o *FieldMetadataDTO) GetFieldName() string {
	if o == nil || IsNil(o.FieldName) {
		var ret string
		return ret
	}
	return *o.FieldName
}

// GetFieldNameOk returns a tuple with the FieldName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FieldMetadataDTO) GetFieldNameOk() (*string, bool) {
	if o == nil || IsNil(o.FieldName) {
		return nil, false
	}
	return o.FieldName, true
}

// HasFieldName returns a boolean if a field has been set.
func (o *FieldMetadataDTO) HasFieldName() bool {
	if o != nil && !IsNil(o.FieldName) {
		return true
	}

	return false
}

// SetFieldName gets a reference to the given string and assigns it to the FieldName field.
func (o *FieldMetadataDTO) SetFieldName(v string) {
	o.FieldName = &v
}

// GetFieldType returns the FieldType field value if set, zero value otherwise.
func (o *FieldMetadataDTO) GetFieldType() string {
	if o == nil || IsNil(o.FieldType) {
		var ret string
		return ret
	}
	return *o.FieldType
}

// GetFieldTypeOk returns a tuple with the FieldType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FieldMetadataDTO) GetFieldTypeOk() (*string, bool) {
	if o == nil || IsNil(o.FieldType) {
		return nil, false
	}
	return o.FieldType, true
}

// HasFieldType returns a boolean if a field has been set.
func (o *FieldMetadataDTO) HasFieldType() bool {
	if o != nil && !IsNil(o.FieldType) {
		return true
	}

	return false
}

// SetFieldType gets a reference to the given string and assigns it to the FieldType field.
func (o *FieldMetadataDTO) SetFieldType(v string) {
	o.FieldType = &v
}

func (o FieldMetadataDTO) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FieldMetadataDTO) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.DtoClassName) {
		toSerialize["dtoClassName"] = o.DtoClassName
	}
	if !IsNil(o.FieldName) {
		toSerialize["fieldName"] = o.FieldName
	}
	if !IsNil(o.FieldType) {
		toSerialize["fieldType"] = o.FieldType
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *FieldMetadataDTO) UnmarshalJSON(data []byte) (err error) {
	varFieldMetadataDTO := _FieldMetadataDTO{}

	err = json.Unmarshal(data, &varFieldMetadataDTO)

	if err != nil {
		return err
	}

	*o = FieldMetadataDTO(varFieldMetadataDTO)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "description")
		delete(additionalProperties, "dtoClassName")
		delete(additionalProperties, "fieldName")
		delete(additionalProperties, "fieldType")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableFieldMetadataDTO struct {
	value *FieldMetadataDTO
	isSet bool
}

func (v NullableFieldMetadataDTO) Get() *FieldMetadataDTO {
	return v.value
}

func (v *NullableFieldMetadataDTO) Set(val *FieldMetadataDTO) {
	v.value = val
	v.isSet = true
}

func (v NullableFieldMetadataDTO) IsSet() bool {
	return v.isSet
}

func (v *NullableFieldMetadataDTO) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFieldMetadataDTO(val *FieldMetadataDTO) *NullableFieldMetadataDTO {
	return &NullableFieldMetadataDTO{value: val, isSet: true}
}

func (v NullableFieldMetadataDTO) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFieldMetadataDTO) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
