/*
MetaCopier API

Explore the power of the MetaCopier API! Our RESTful API offers scalable and secure access to accounts, projects, and more. Get started quickly with authentication, explore endpoints, and access code samples in various languages.<br/><br/>All dates are in ISO 8601<br/><br/>This API is not designed for real-time communication purposes. For instance, continuously polling account information such as open positions every second is not recommended.<br/><br/>Our frontend uses this API, so you can look at the requests on our frontend for examples.

API version: 1.2.5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package metacopier

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the RiskLimitDTO type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RiskLimitDTO{}

// RiskLimitDTO struct for RiskLimitDTO
type RiskLimitDTO struct {
	// Enter an absolute risk limit in account currency. Set to 0 to deactivate.
	AbsoluteRiskLimit *float32 `json:"absoluteRiskLimit,omitempty"`
	// You have to set it during resource creation, after that, it is only read-only
	AccountId *string `json:"accountId,omitempty"`
	Active *bool `json:"active,omitempty"`
	// If set to 'true', all positions will be closed immediately when the primary risk limit is reached. If set to 'false', new trades will not be opened when the primary limit is reached, but the fallback limits become active as a secondary safety measure.
	CloseAllOpenPositions *bool `json:"closeAllOpenPositions,omitempty"`
	// You have to set it during resource creation, after that, it is only read-only
	CopierId *string `json:"copierId,omitempty"`
	// Fallback absolute risk limit in account currency. Only applies when closeAllOpenPositions is false. When this limit is reached, all positions will be closed. Set to 0 to deactivate.
	FallbackAbsoluteRiskLimit *float32 `json:"fallbackAbsoluteRiskLimit,omitempty"`
	// Fallback relative risk limit in account currency. Only applies when closeAllOpenPositions is false. When this limit is reached, all positions will be closed. Set to 0 to deactivate.
	FallbackRelativeRiskLimit *float32 `json:"fallbackRelativeRiskLimit,omitempty"`
	// Fallback risk limit (percentage). Only applies when closeAllOpenPositions is false. When this limit is reached, all positions will be closed. Set to 0 to deactivate.
	FallbackRiskLimit *float32 `json:"fallbackRiskLimit,omitempty"`
	// If set to 5, it means that if the limit is reached and stays over the limit for 5 seconds, the risk limit will be activated; otherwise, the limit will remain deactivated
	FulfillSeconds *int32 `json:"fulfillSeconds,omitempty"`
	Id *string `json:"id,omitempty"`
	// Enter an relative risk limit in account currency. Set to 0 to deactivate.
	RelativeRiskLimit *float32 `json:"relativeRiskLimit,omitempty"`
	// ISO 8601. Set the reset time for calculation (see riskType). Only used for 1-3 risk type. Only the time is considered, and the date is ignored.
	ResetTime *time.Time `json:"resetTime,omitempty"`
	// 0.215 for 21.5% (set to 0 to deactivate)
	RiskLimit float32 `json:"riskLimit"`
	RiskType RiskTypeDTO `json:"riskType"`
}

type _RiskLimitDTO RiskLimitDTO

// NewRiskLimitDTO instantiates a new RiskLimitDTO object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRiskLimitDTO(riskLimit float32, riskType RiskTypeDTO) *RiskLimitDTO {
	this := RiskLimitDTO{}
	var absoluteRiskLimit float32 = 0
	this.AbsoluteRiskLimit = &absoluteRiskLimit
	var active bool = true
	this.Active = &active
	var closeAllOpenPositions bool = true
	this.CloseAllOpenPositions = &closeAllOpenPositions
	var fallbackAbsoluteRiskLimit float32 = 0
	this.FallbackAbsoluteRiskLimit = &fallbackAbsoluteRiskLimit
	var fallbackRelativeRiskLimit float32 = 0
	this.FallbackRelativeRiskLimit = &fallbackRelativeRiskLimit
	var fallbackRiskLimit float32 = 0
	this.FallbackRiskLimit = &fallbackRiskLimit
	var fulfillSeconds int32 = 60
	this.FulfillSeconds = &fulfillSeconds
	var relativeRiskLimit float32 = 0
	this.RelativeRiskLimit = &relativeRiskLimit
	var resetTime time.Time = "2023-12-30T00:00Z"
	this.ResetTime = &resetTime
	this.RiskLimit = riskLimit
	this.RiskType = riskType
	return &this
}

// NewRiskLimitDTOWithDefaults instantiates a new RiskLimitDTO object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRiskLimitDTOWithDefaults() *RiskLimitDTO {
	this := RiskLimitDTO{}
	var absoluteRiskLimit float32 = 0
	this.AbsoluteRiskLimit = &absoluteRiskLimit
	var active bool = true
	this.Active = &active
	var closeAllOpenPositions bool = true
	this.CloseAllOpenPositions = &closeAllOpenPositions
	var fallbackAbsoluteRiskLimit float32 = 0
	this.FallbackAbsoluteRiskLimit = &fallbackAbsoluteRiskLimit
	var fallbackRelativeRiskLimit float32 = 0
	this.FallbackRelativeRiskLimit = &fallbackRelativeRiskLimit
	var fallbackRiskLimit float32 = 0
	this.FallbackRiskLimit = &fallbackRiskLimit
	var fulfillSeconds int32 = 60
	this.FulfillSeconds = &fulfillSeconds
	var relativeRiskLimit float32 = 0
	this.RelativeRiskLimit = &relativeRiskLimit
	var resetTime time.Time = "2023-12-30T00:00Z"
	this.ResetTime = &resetTime
	return &this
}

// GetAbsoluteRiskLimit returns the AbsoluteRiskLimit field value if set, zero value otherwise.
func (o *RiskLimitDTO) GetAbsoluteRiskLimit() float32 {
	if o == nil || IsNil(o.AbsoluteRiskLimit) {
		var ret float32
		return ret
	}
	return *o.AbsoluteRiskLimit
}

// GetAbsoluteRiskLimitOk returns a tuple with the AbsoluteRiskLimit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskLimitDTO) GetAbsoluteRiskLimitOk() (*float32, bool) {
	if o == nil || IsNil(o.AbsoluteRiskLimit) {
		return nil, false
	}
	return o.AbsoluteRiskLimit, true
}

// HasAbsoluteRiskLimit returns a boolean if a field has been set.
func (o *RiskLimitDTO) HasAbsoluteRiskLimit() bool {
	if o != nil && !IsNil(o.AbsoluteRiskLimit) {
		return true
	}

	return false
}

// SetAbsoluteRiskLimit gets a reference to the given float32 and assigns it to the AbsoluteRiskLimit field.
func (o *RiskLimitDTO) SetAbsoluteRiskLimit(v float32) {
	o.AbsoluteRiskLimit = &v
}

// GetAccountId returns the AccountId field value if set, zero value otherwise.
func (o *RiskLimitDTO) GetAccountId() string {
	if o == nil || IsNil(o.AccountId) {
		var ret string
		return ret
	}
	return *o.AccountId
}

// GetAccountIdOk returns a tuple with the AccountId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskLimitDTO) GetAccountIdOk() (*string, bool) {
	if o == nil || IsNil(o.AccountId) {
		return nil, false
	}
	return o.AccountId, true
}

// HasAccountId returns a boolean if a field has been set.
func (o *RiskLimitDTO) HasAccountId() bool {
	if o != nil && !IsNil(o.AccountId) {
		return true
	}

	return false
}

// SetAccountId gets a reference to the given string and assigns it to the AccountId field.
func (o *RiskLimitDTO) SetAccountId(v string) {
	o.AccountId = &v
}

// GetActive returns the Active field value if set, zero value otherwise.
func (o *RiskLimitDTO) GetActive() bool {
	if o == nil || IsNil(o.Active) {
		var ret bool
		return ret
	}
	return *o.Active
}

// GetActiveOk returns a tuple with the Active field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskLimitDTO) GetActiveOk() (*bool, bool) {
	if o == nil || IsNil(o.Active) {
		return nil, false
	}
	return o.Active, true
}

// HasActive returns a boolean if a field has been set.
func (o *RiskLimitDTO) HasActive() bool {
	if o != nil && !IsNil(o.Active) {
		return true
	}

	return false
}

// SetActive gets a reference to the given bool and assigns it to the Active field.
func (o *RiskLimitDTO) SetActive(v bool) {
	o.Active = &v
}

// GetCloseAllOpenPositions returns the CloseAllOpenPositions field value if set, zero value otherwise.
func (o *RiskLimitDTO) GetCloseAllOpenPositions() bool {
	if o == nil || IsNil(o.CloseAllOpenPositions) {
		var ret bool
		return ret
	}
	return *o.CloseAllOpenPositions
}

// GetCloseAllOpenPositionsOk returns a tuple with the CloseAllOpenPositions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskLimitDTO) GetCloseAllOpenPositionsOk() (*bool, bool) {
	if o == nil || IsNil(o.CloseAllOpenPositions) {
		return nil, false
	}
	return o.CloseAllOpenPositions, true
}

// HasCloseAllOpenPositions returns a boolean if a field has been set.
func (o *RiskLimitDTO) HasCloseAllOpenPositions() bool {
	if o != nil && !IsNil(o.CloseAllOpenPositions) {
		return true
	}

	return false
}

// SetCloseAllOpenPositions gets a reference to the given bool and assigns it to the CloseAllOpenPositions field.
func (o *RiskLimitDTO) SetCloseAllOpenPositions(v bool) {
	o.CloseAllOpenPositions = &v
}

// GetCopierId returns the CopierId field value if set, zero value otherwise.
func (o *RiskLimitDTO) GetCopierId() string {
	if o == nil || IsNil(o.CopierId) {
		var ret string
		return ret
	}
	return *o.CopierId
}

// GetCopierIdOk returns a tuple with the CopierId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskLimitDTO) GetCopierIdOk() (*string, bool) {
	if o == nil || IsNil(o.CopierId) {
		return nil, false
	}
	return o.CopierId, true
}

// HasCopierId returns a boolean if a field has been set.
func (o *RiskLimitDTO) HasCopierId() bool {
	if o != nil && !IsNil(o.CopierId) {
		return true
	}

	return false
}

// SetCopierId gets a reference to the given string and assigns it to the CopierId field.
func (o *RiskLimitDTO) SetCopierId(v string) {
	o.CopierId = &v
}

// GetFallbackAbsoluteRiskLimit returns the FallbackAbsoluteRiskLimit field value if set, zero value otherwise.
func (o *RiskLimitDTO) GetFallbackAbsoluteRiskLimit() float32 {
	if o == nil || IsNil(o.FallbackAbsoluteRiskLimit) {
		var ret float32
		return ret
	}
	return *o.FallbackAbsoluteRiskLimit
}

// GetFallbackAbsoluteRiskLimitOk returns a tuple with the FallbackAbsoluteRiskLimit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskLimitDTO) GetFallbackAbsoluteRiskLimitOk() (*float32, bool) {
	if o == nil || IsNil(o.FallbackAbsoluteRiskLimit) {
		return nil, false
	}
	return o.FallbackAbsoluteRiskLimit, true
}

// HasFallbackAbsoluteRiskLimit returns a boolean if a field has been set.
func (o *RiskLimitDTO) HasFallbackAbsoluteRiskLimit() bool {
	if o != nil && !IsNil(o.FallbackAbsoluteRiskLimit) {
		return true
	}

	return false
}

// SetFallbackAbsoluteRiskLimit gets a reference to the given float32 and assigns it to the FallbackAbsoluteRiskLimit field.
func (o *RiskLimitDTO) SetFallbackAbsoluteRiskLimit(v float32) {
	o.FallbackAbsoluteRiskLimit = &v
}

// GetFallbackRelativeRiskLimit returns the FallbackRelativeRiskLimit field value if set, zero value otherwise.
func (o *RiskLimitDTO) GetFallbackRelativeRiskLimit() float32 {
	if o == nil || IsNil(o.FallbackRelativeRiskLimit) {
		var ret float32
		return ret
	}
	return *o.FallbackRelativeRiskLimit
}

// GetFallbackRelativeRiskLimitOk returns a tuple with the FallbackRelativeRiskLimit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskLimitDTO) GetFallbackRelativeRiskLimitOk() (*float32, bool) {
	if o == nil || IsNil(o.FallbackRelativeRiskLimit) {
		return nil, false
	}
	return o.FallbackRelativeRiskLimit, true
}

// HasFallbackRelativeRiskLimit returns a boolean if a field has been set.
func (o *RiskLimitDTO) HasFallbackRelativeRiskLimit() bool {
	if o != nil && !IsNil(o.FallbackRelativeRiskLimit) {
		return true
	}

	return false
}

// SetFallbackRelativeRiskLimit gets a reference to the given float32 and assigns it to the FallbackRelativeRiskLimit field.
func (o *RiskLimitDTO) SetFallbackRelativeRiskLimit(v float32) {
	o.FallbackRelativeRiskLimit = &v
}

// GetFallbackRiskLimit returns the FallbackRiskLimit field value if set, zero value otherwise.
func (o *RiskLimitDTO) GetFallbackRiskLimit() float32 {
	if o == nil || IsNil(o.FallbackRiskLimit) {
		var ret float32
		return ret
	}
	return *o.FallbackRiskLimit
}

// GetFallbackRiskLimitOk returns a tuple with the FallbackRiskLimit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskLimitDTO) GetFallbackRiskLimitOk() (*float32, bool) {
	if o == nil || IsNil(o.FallbackRiskLimit) {
		return nil, false
	}
	return o.FallbackRiskLimit, true
}

// HasFallbackRiskLimit returns a boolean if a field has been set.
func (o *RiskLimitDTO) HasFallbackRiskLimit() bool {
	if o != nil && !IsNil(o.FallbackRiskLimit) {
		return true
	}

	return false
}

// SetFallbackRiskLimit gets a reference to the given float32 and assigns it to the FallbackRiskLimit field.
func (o *RiskLimitDTO) SetFallbackRiskLimit(v float32) {
	o.FallbackRiskLimit = &v
}

// GetFulfillSeconds returns the FulfillSeconds field value if set, zero value otherwise.
func (o *RiskLimitDTO) GetFulfillSeconds() int32 {
	if o == nil || IsNil(o.FulfillSeconds) {
		var ret int32
		return ret
	}
	return *o.FulfillSeconds
}

// GetFulfillSecondsOk returns a tuple with the FulfillSeconds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskLimitDTO) GetFulfillSecondsOk() (*int32, bool) {
	if o == nil || IsNil(o.FulfillSeconds) {
		return nil, false
	}
	return o.FulfillSeconds, true
}

// HasFulfillSeconds returns a boolean if a field has been set.
func (o *RiskLimitDTO) HasFulfillSeconds() bool {
	if o != nil && !IsNil(o.FulfillSeconds) {
		return true
	}

	return false
}

// SetFulfillSeconds gets a reference to the given int32 and assigns it to the FulfillSeconds field.
func (o *RiskLimitDTO) SetFulfillSeconds(v int32) {
	o.FulfillSeconds = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *RiskLimitDTO) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskLimitDTO) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *RiskLimitDTO) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *RiskLimitDTO) SetId(v string) {
	o.Id = &v
}

// GetRelativeRiskLimit returns the RelativeRiskLimit field value if set, zero value otherwise.
func (o *RiskLimitDTO) GetRelativeRiskLimit() float32 {
	if o == nil || IsNil(o.RelativeRiskLimit) {
		var ret float32
		return ret
	}
	return *o.RelativeRiskLimit
}

// GetRelativeRiskLimitOk returns a tuple with the RelativeRiskLimit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskLimitDTO) GetRelativeRiskLimitOk() (*float32, bool) {
	if o == nil || IsNil(o.RelativeRiskLimit) {
		return nil, false
	}
	return o.RelativeRiskLimit, true
}

// HasRelativeRiskLimit returns a boolean if a field has been set.
func (o *RiskLimitDTO) HasRelativeRiskLimit() bool {
	if o != nil && !IsNil(o.RelativeRiskLimit) {
		return true
	}

	return false
}

// SetRelativeRiskLimit gets a reference to the given float32 and assigns it to the RelativeRiskLimit field.
func (o *RiskLimitDTO) SetRelativeRiskLimit(v float32) {
	o.RelativeRiskLimit = &v
}

// GetResetTime returns the ResetTime field value if set, zero value otherwise.
func (o *RiskLimitDTO) GetResetTime() time.Time {
	if o == nil || IsNil(o.ResetTime) {
		var ret time.Time
		return ret
	}
	return *o.ResetTime
}

// GetResetTimeOk returns a tuple with the ResetTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskLimitDTO) GetResetTimeOk() (*time.Time, bool) {
	if o == nil || IsNil(o.ResetTime) {
		return nil, false
	}
	return o.ResetTime, true
}

// HasResetTime returns a boolean if a field has been set.
func (o *RiskLimitDTO) HasResetTime() bool {
	if o != nil && !IsNil(o.ResetTime) {
		return true
	}

	return false
}

// SetResetTime gets a reference to the given time.Time and assigns it to the ResetTime field.
func (o *RiskLimitDTO) SetResetTime(v time.Time) {
	o.ResetTime = &v
}

// GetRiskLimit returns the RiskLimit field value
func (o *RiskLimitDTO) GetRiskLimit() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.RiskLimit
}

// GetRiskLimitOk returns a tuple with the RiskLimit field value
// and a boolean to check if the value has been set.
func (o *RiskLimitDTO) GetRiskLimitOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RiskLimit, true
}

// SetRiskLimit sets field value
func (o *RiskLimitDTO) SetRiskLimit(v float32) {
	o.RiskLimit = v
}

// GetRiskType returns the RiskType field value
func (o *RiskLimitDTO) GetRiskType() RiskTypeDTO {
	if o == nil {
		var ret RiskTypeDTO
		return ret
	}

	return o.RiskType
}

// GetRiskTypeOk returns a tuple with the RiskType field value
// and a boolean to check if the value has been set.
func (o *RiskLimitDTO) GetRiskTypeOk() (*RiskTypeDTO, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RiskType, true
}

// SetRiskType sets field value
func (o *RiskLimitDTO) SetRiskType(v RiskTypeDTO) {
	o.RiskType = v
}

func (o RiskLimitDTO) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RiskLimitDTO) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AbsoluteRiskLimit) {
		toSerialize["absoluteRiskLimit"] = o.AbsoluteRiskLimit
	}
	if !IsNil(o.AccountId) {
		toSerialize["accountId"] = o.AccountId
	}
	if !IsNil(o.Active) {
		toSerialize["active"] = o.Active
	}
	if !IsNil(o.CloseAllOpenPositions) {
		toSerialize["closeAllOpenPositions"] = o.CloseAllOpenPositions
	}
	if !IsNil(o.CopierId) {
		toSerialize["copierId"] = o.CopierId
	}
	if !IsNil(o.FallbackAbsoluteRiskLimit) {
		toSerialize["fallbackAbsoluteRiskLimit"] = o.FallbackAbsoluteRiskLimit
	}
	if !IsNil(o.FallbackRelativeRiskLimit) {
		toSerialize["fallbackRelativeRiskLimit"] = o.FallbackRelativeRiskLimit
	}
	if !IsNil(o.FallbackRiskLimit) {
		toSerialize["fallbackRiskLimit"] = o.FallbackRiskLimit
	}
	if !IsNil(o.FulfillSeconds) {
		toSerialize["fulfillSeconds"] = o.FulfillSeconds
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.RelativeRiskLimit) {
		toSerialize["relativeRiskLimit"] = o.RelativeRiskLimit
	}
	if !IsNil(o.ResetTime) {
		toSerialize["resetTime"] = o.ResetTime
	}
	toSerialize["riskLimit"] = o.RiskLimit
	toSerialize["riskType"] = o.RiskType
	return toSerialize, nil
}

func (o *RiskLimitDTO) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"riskLimit",
		"riskType",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRiskLimitDTO := _RiskLimitDTO{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRiskLimitDTO)

	if err != nil {
		return err
	}

	*o = RiskLimitDTO(varRiskLimitDTO)

	return err
}

type NullableRiskLimitDTO struct {
	value *RiskLimitDTO
	isSet bool
}

func (v NullableRiskLimitDTO) Get() *RiskLimitDTO {
	return v.value
}

func (v *NullableRiskLimitDTO) Set(val *RiskLimitDTO) {
	v.value = val
	v.isSet = true
}

func (v NullableRiskLimitDTO) IsSet() bool {
	return v.isSet
}

func (v *NullableRiskLimitDTO) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRiskLimitDTO(val *RiskLimitDTO) *NullableRiskLimitDTO {
	return &NullableRiskLimitDTO{value: val, isSet: true}
}

func (v NullableRiskLimitDTO) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRiskLimitDTO) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


