/*
MetaCopier API

Explore the power of the MetaCopier API! Our RESTful API offers scalable and secure access to accounts, projects, and more. Get started quickly with authentication, explore endpoints, and access code samples in various languages.<br/><br/>All dates are in ISO 8601<br/><br/>This API is not designed for real-time communication purposes. For instance, continuously polling account information such as open positions every second is not recommended.<br/><br/>Our frontend uses this API, so you can look at the requests on our frontend for examples.

API version: 1.2.5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package metacopier

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the ReportPerformanceParametersDTO type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ReportPerformanceParametersDTO{}

// ReportPerformanceParametersDTO Parameters required for generating a performance report over a specified time period for one or more resources.
type ReportPerformanceParametersDTO struct {
	// List of unique identifiers for the resources (e.g., account IDs, project IDs, or feature IDs) for which the performance report is requested.
	Id []string `json:"id"`
	// Type of resource identified by the IDs, indicating whether the report pertains to accounts, projects, or specific features.
	IdType string `json:"idType"`
	// Start date for the reporting period.
	Start time.Time `json:"start"`
	// End date for the reporting period.
	Stop time.Time `json:"stop"`
}

type _ReportPerformanceParametersDTO ReportPerformanceParametersDTO

// NewReportPerformanceParametersDTO instantiates a new ReportPerformanceParametersDTO object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReportPerformanceParametersDTO(id []string, idType string, start time.Time, stop time.Time) *ReportPerformanceParametersDTO {
	this := ReportPerformanceParametersDTO{}
	this.Id = id
	this.IdType = idType
	this.Start = start
	this.Stop = stop
	return &this
}

// NewReportPerformanceParametersDTOWithDefaults instantiates a new ReportPerformanceParametersDTO object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReportPerformanceParametersDTOWithDefaults() *ReportPerformanceParametersDTO {
	this := ReportPerformanceParametersDTO{}
	return &this
}

// GetId returns the Id field value
func (o *ReportPerformanceParametersDTO) GetId() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ReportPerformanceParametersDTO) GetIdOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Id, true
}

// SetId sets field value
func (o *ReportPerformanceParametersDTO) SetId(v []string) {
	o.Id = v
}

// GetIdType returns the IdType field value
func (o *ReportPerformanceParametersDTO) GetIdType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.IdType
}

// GetIdTypeOk returns a tuple with the IdType field value
// and a boolean to check if the value has been set.
func (o *ReportPerformanceParametersDTO) GetIdTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IdType, true
}

// SetIdType sets field value
func (o *ReportPerformanceParametersDTO) SetIdType(v string) {
	o.IdType = v
}

// GetStart returns the Start field value
func (o *ReportPerformanceParametersDTO) GetStart() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.Start
}

// GetStartOk returns a tuple with the Start field value
// and a boolean to check if the value has been set.
func (o *ReportPerformanceParametersDTO) GetStartOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Start, true
}

// SetStart sets field value
func (o *ReportPerformanceParametersDTO) SetStart(v time.Time) {
	o.Start = v
}

// GetStop returns the Stop field value
func (o *ReportPerformanceParametersDTO) GetStop() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.Stop
}

// GetStopOk returns a tuple with the Stop field value
// and a boolean to check if the value has been set.
func (o *ReportPerformanceParametersDTO) GetStopOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Stop, true
}

// SetStop sets field value
func (o *ReportPerformanceParametersDTO) SetStop(v time.Time) {
	o.Stop = v
}

func (o ReportPerformanceParametersDTO) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ReportPerformanceParametersDTO) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["idType"] = o.IdType
	toSerialize["start"] = o.Start
	toSerialize["stop"] = o.Stop
	return toSerialize, nil
}

func (o *ReportPerformanceParametersDTO) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"idType",
		"start",
		"stop",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varReportPerformanceParametersDTO := _ReportPerformanceParametersDTO{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varReportPerformanceParametersDTO)

	if err != nil {
		return err
	}

	*o = ReportPerformanceParametersDTO(varReportPerformanceParametersDTO)

	return err
}

type NullableReportPerformanceParametersDTO struct {
	value *ReportPerformanceParametersDTO
	isSet bool
}

func (v NullableReportPerformanceParametersDTO) Get() *ReportPerformanceParametersDTO {
	return v.value
}

func (v *NullableReportPerformanceParametersDTO) Set(val *ReportPerformanceParametersDTO) {
	v.value = val
	v.isSet = true
}

func (v NullableReportPerformanceParametersDTO) IsSet() bool {
	return v.isSet
}

func (v *NullableReportPerformanceParametersDTO) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReportPerformanceParametersDTO(val *ReportPerformanceParametersDTO) *NullableReportPerformanceParametersDTO {
	return &NullableReportPerformanceParametersDTO{value: val, isSet: true}
}

func (v NullableReportPerformanceParametersDTO) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReportPerformanceParametersDTO) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
