/*
MetaCopier API

Explore the power of the MetaCopier API! Our RESTful API offers scalable and secure access to accounts, projects, and more. Get started quickly with authentication, explore endpoints, and access code samples in various languages.<br/><br/>All dates are in ISO 8601<br/><br/>This API is not designed for real-time communication purposes. For instance, continuously polling account information such as open positions every second is not recommended.<br/><br/>Our frontend uses this API, so you can look at the requests on our frontend for examples.

API version: 1.2.5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package metacopier

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the SymbolMappingDTO type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SymbolMappingDTO{}

// SymbolMappingDTO struct for SymbolMappingDTO
type SymbolMappingDTO struct {
	// This symbol mapping is only applied if the trade comes from a specific broker, for example, 'ICMarkets.*'. For all brokers, you can enter '.*' (this is a regex)
	BrokerFrom string `json:"brokerFrom"`
	// This symbol mapping is only applied if the trade is copied to a specific broker, for example, 'ICMarkets.*'. For all brokers, you can enter '.*' (this is a regex)
	BrokerTo string `json:"brokerTo"`
	// This is read-only. The system attempts to automatically map symbols, but if there are multiple findings, they will be listed here. (This member is used only for the endpoint symbolMappings/current)
	BrokerToSuggestion []string `json:"brokerToSuggestion,omitempty"`
	// Enter a symbol e.g. GBPUSD (is not a regex)
	From string `json:"from"`
	Id   *int64 `json:"id,omitempty"`
	// The priority is ascending, which means that 0 has a higher priority than 1. Priority is always positive
	Priority  int32   `json:"priority"`
	ProjectId *string `json:"projectId,omitempty"`
	// Enter a symbol e.g. GBPEUR (is not a regex)
	To string `json:"to"`
}

type _SymbolMappingDTO SymbolMappingDTO

// NewSymbolMappingDTO instantiates a new SymbolMappingDTO object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSymbolMappingDTO(brokerFrom string, brokerTo string, from string, priority int32, to string) *SymbolMappingDTO {
	this := SymbolMappingDTO{}
	this.BrokerFrom = brokerFrom
	this.BrokerTo = brokerTo
	this.From = from
	this.Priority = priority
	this.To = to
	return &this
}

// NewSymbolMappingDTOWithDefaults instantiates a new SymbolMappingDTO object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSymbolMappingDTOWithDefaults() *SymbolMappingDTO {
	this := SymbolMappingDTO{}
	return &this
}

// GetBrokerFrom returns the BrokerFrom field value
func (o *SymbolMappingDTO) GetBrokerFrom() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BrokerFrom
}

// GetBrokerFromOk returns a tuple with the BrokerFrom field value
// and a boolean to check if the value has been set.
func (o *SymbolMappingDTO) GetBrokerFromOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BrokerFrom, true
}

// SetBrokerFrom sets field value
func (o *SymbolMappingDTO) SetBrokerFrom(v string) {
	o.BrokerFrom = v
}

// GetBrokerTo returns the BrokerTo field value
func (o *SymbolMappingDTO) GetBrokerTo() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BrokerTo
}

// GetBrokerToOk returns a tuple with the BrokerTo field value
// and a boolean to check if the value has been set.
func (o *SymbolMappingDTO) GetBrokerToOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BrokerTo, true
}

// SetBrokerTo sets field value
func (o *SymbolMappingDTO) SetBrokerTo(v string) {
	o.BrokerTo = v
}

// GetBrokerToSuggestion returns the BrokerToSuggestion field value if set, zero value otherwise.
func (o *SymbolMappingDTO) GetBrokerToSuggestion() []string {
	if o == nil || IsNil(o.BrokerToSuggestion) {
		var ret []string
		return ret
	}
	return o.BrokerToSuggestion
}

// GetBrokerToSuggestionOk returns a tuple with the BrokerToSuggestion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SymbolMappingDTO) GetBrokerToSuggestionOk() ([]string, bool) {
	if o == nil || IsNil(o.BrokerToSuggestion) {
		return nil, false
	}
	return o.BrokerToSuggestion, true
}

// HasBrokerToSuggestion returns a boolean if a field has been set.
func (o *SymbolMappingDTO) HasBrokerToSuggestion() bool {
	if o != nil && !IsNil(o.BrokerToSuggestion) {
		return true
	}

	return false
}

// SetBrokerToSuggestion gets a reference to the given []string and assigns it to the BrokerToSuggestion field.
func (o *SymbolMappingDTO) SetBrokerToSuggestion(v []string) {
	o.BrokerToSuggestion = v
}

// GetFrom returns the From field value
func (o *SymbolMappingDTO) GetFrom() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.From
}

// GetFromOk returns a tuple with the From field value
// and a boolean to check if the value has been set.
func (o *SymbolMappingDTO) GetFromOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.From, true
}

// SetFrom sets field value
func (o *SymbolMappingDTO) SetFrom(v string) {
	o.From = v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *SymbolMappingDTO) GetId() int64 {
	if o == nil || IsNil(o.Id) {
		var ret int64
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SymbolMappingDTO) GetIdOk() (*int64, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *SymbolMappingDTO) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int64 and assigns it to the Id field.
func (o *SymbolMappingDTO) SetId(v int64) {
	o.Id = &v
}

// GetPriority returns the Priority field value
func (o *SymbolMappingDTO) GetPriority() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Priority
}

// GetPriorityOk returns a tuple with the Priority field value
// and a boolean to check if the value has been set.
func (o *SymbolMappingDTO) GetPriorityOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Priority, true
}

// SetPriority sets field value
func (o *SymbolMappingDTO) SetPriority(v int32) {
	o.Priority = v
}

// GetProjectId returns the ProjectId field value if set, zero value otherwise.
func (o *SymbolMappingDTO) GetProjectId() string {
	if o == nil || IsNil(o.ProjectId) {
		var ret string
		return ret
	}
	return *o.ProjectId
}

// GetProjectIdOk returns a tuple with the ProjectId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SymbolMappingDTO) GetProjectIdOk() (*string, bool) {
	if o == nil || IsNil(o.ProjectId) {
		return nil, false
	}
	return o.ProjectId, true
}

// HasProjectId returns a boolean if a field has been set.
func (o *SymbolMappingDTO) HasProjectId() bool {
	if o != nil && !IsNil(o.ProjectId) {
		return true
	}

	return false
}

// SetProjectId gets a reference to the given string and assigns it to the ProjectId field.
func (o *SymbolMappingDTO) SetProjectId(v string) {
	o.ProjectId = &v
}

// GetTo returns the To field value
func (o *SymbolMappingDTO) GetTo() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.To
}

// GetToOk returns a tuple with the To field value
// and a boolean to check if the value has been set.
func (o *SymbolMappingDTO) GetToOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.To, true
}

// SetTo sets field value
func (o *SymbolMappingDTO) SetTo(v string) {
	o.To = v
}

func (o SymbolMappingDTO) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SymbolMappingDTO) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["brokerFrom"] = o.BrokerFrom
	toSerialize["brokerTo"] = o.BrokerTo
	if !IsNil(o.BrokerToSuggestion) {
		toSerialize["brokerToSuggestion"] = o.BrokerToSuggestion
	}
	toSerialize["from"] = o.From
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	toSerialize["priority"] = o.Priority
	if !IsNil(o.ProjectId) {
		toSerialize["projectId"] = o.ProjectId
	}
	toSerialize["to"] = o.To
	return toSerialize, nil
}

func (o *SymbolMappingDTO) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"brokerFrom",
		"brokerTo",
		"from",
		"priority",
		"to",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSymbolMappingDTO := _SymbolMappingDTO{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSymbolMappingDTO)

	if err != nil {
		return err
	}

	*o = SymbolMappingDTO(varSymbolMappingDTO)

	return err
}

type NullableSymbolMappingDTO struct {
	value *SymbolMappingDTO
	isSet bool
}

func (v NullableSymbolMappingDTO) Get() *SymbolMappingDTO {
	return v.value
}

func (v *NullableSymbolMappingDTO) Set(val *SymbolMappingDTO) {
	v.value = val
	v.isSet = true
}

func (v NullableSymbolMappingDTO) IsSet() bool {
	return v.isSet
}

func (v *NullableSymbolMappingDTO) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSymbolMappingDTO(val *SymbolMappingDTO) *NullableSymbolMappingDTO {
	return &NullableSymbolMappingDTO{value: val, isSet: true}
}

func (v NullableSymbolMappingDTO) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSymbolMappingDTO) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
