/*
MetaCopier API

Explore the power of the MetaCopier API! Our RESTful API offers scalable and secure access to accounts, projects, and more. Get started quickly with authentication, explore endpoints, and access code samples in various languages.<br/><br/>All dates are in ISO 8601<br/><br/>This API is not designed for real-time communication purposes. For instance, continuously polling account information such as open positions every second is not recommended.<br/><br/>Our frontend uses this API, so you can look at the requests on our frontend for examples.

API version: 1.2.5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package metacopier

import (
	"encoding/json"
)

// checks if the RestEndpointMetadataDTO type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RestEndpointMetadataDTO{}

// RestEndpointMetadataDTO Represents a REST endpoint that can be allowed/blocked via API key access policy
type RestEndpointMetadataDTO struct {
	// HTTP method
	Method *string `json:"method,omitempty"`
	// Endpoint path pattern
	Path *string `json:"path,omitempty"`
	// Operation summary/description if available
	Summary *string `json:"summary,omitempty"`
}

// NewRestEndpointMetadataDTO instantiates a new RestEndpointMetadataDTO object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRestEndpointMetadataDTO() *RestEndpointMetadataDTO {
	this := RestEndpointMetadataDTO{}
	return &this
}

// NewRestEndpointMetadataDTOWithDefaults instantiates a new RestEndpointMetadataDTO object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRestEndpointMetadataDTOWithDefaults() *RestEndpointMetadataDTO {
	this := RestEndpointMetadataDTO{}
	return &this
}

// GetMethod returns the Method field value if set, zero value otherwise.
func (o *RestEndpointMetadataDTO) GetMethod() string {
	if o == nil || IsNil(o.Method) {
		var ret string
		return ret
	}
	return *o.Method
}

// GetMethodOk returns a tuple with the Method field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RestEndpointMetadataDTO) GetMethodOk() (*string, bool) {
	if o == nil || IsNil(o.Method) {
		return nil, false
	}
	return o.Method, true
}

// HasMethod returns a boolean if a field has been set.
func (o *RestEndpointMetadataDTO) HasMethod() bool {
	if o != nil && !IsNil(o.Method) {
		return true
	}

	return false
}

// SetMethod gets a reference to the given string and assigns it to the Method field.
func (o *RestEndpointMetadataDTO) SetMethod(v string) {
	o.Method = &v
}

// GetPath returns the Path field value if set, zero value otherwise.
func (o *RestEndpointMetadataDTO) GetPath() string {
	if o == nil || IsNil(o.Path) {
		var ret string
		return ret
	}
	return *o.Path
}

// GetPathOk returns a tuple with the Path field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RestEndpointMetadataDTO) GetPathOk() (*string, bool) {
	if o == nil || IsNil(o.Path) {
		return nil, false
	}
	return o.Path, true
}

// HasPath returns a boolean if a field has been set.
func (o *RestEndpointMetadataDTO) HasPath() bool {
	if o != nil && !IsNil(o.Path) {
		return true
	}

	return false
}

// SetPath gets a reference to the given string and assigns it to the Path field.
func (o *RestEndpointMetadataDTO) SetPath(v string) {
	o.Path = &v
}

// GetSummary returns the Summary field value if set, zero value otherwise.
func (o *RestEndpointMetadataDTO) GetSummary() string {
	if o == nil || IsNil(o.Summary) {
		var ret string
		return ret
	}
	return *o.Summary
}

// GetSummaryOk returns a tuple with the Summary field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RestEndpointMetadataDTO) GetSummaryOk() (*string, bool) {
	if o == nil || IsNil(o.Summary) {
		return nil, false
	}
	return o.Summary, true
}

// HasSummary returns a boolean if a field has been set.
func (o *RestEndpointMetadataDTO) HasSummary() bool {
	if o != nil && !IsNil(o.Summary) {
		return true
	}

	return false
}

// SetSummary gets a reference to the given string and assigns it to the Summary field.
func (o *RestEndpointMetadataDTO) SetSummary(v string) {
	o.Summary = &v
}

func (o RestEndpointMetadataDTO) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RestEndpointMetadataDTO) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Method) {
		toSerialize["method"] = o.Method
	}
	if !IsNil(o.Path) {
		toSerialize["path"] = o.Path
	}
	if !IsNil(o.Summary) {
		toSerialize["summary"] = o.Summary
	}
	return toSerialize, nil
}

type NullableRestEndpointMetadataDTO struct {
	value *RestEndpointMetadataDTO
	isSet bool
}

func (v NullableRestEndpointMetadataDTO) Get() *RestEndpointMetadataDTO {
	return v.value
}

func (v *NullableRestEndpointMetadataDTO) Set(val *RestEndpointMetadataDTO) {
	v.value = val
	v.isSet = true
}

func (v NullableRestEndpointMetadataDTO) IsSet() bool {
	return v.isSet
}

func (v *NullableRestEndpointMetadataDTO) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRestEndpointMetadataDTO(val *RestEndpointMetadataDTO) *NullableRestEndpointMetadataDTO {
	return &NullableRestEndpointMetadataDTO{value: val, isSet: true}
}

func (v NullableRestEndpointMetadataDTO) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRestEndpointMetadataDTO) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
