/*
MetaCopier API

Explore the power of the MetaCopier API! Our RESTful API offers scalable and secure access to accounts, projects, and more. Get started quickly with authentication, explore endpoints, and access code samples in various languages.<br/><br/>All dates are in ISO 8601<br/><br/>This API is not designed for real-time communication purposes. For instance, continuously polling account information such as open positions every second is not recommended.<br/><br/>Our frontend uses this API, so you can look at the requests on our frontend for examples.

API version: 1.2.5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package metacopier

import (
	"encoding/json"
)

// checks if the FeatureTrailingStopDTO type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FeatureTrailingStopDTO{}

// FeatureTrailingStopDTO DTO for the trailing stop feature (copier/account) (PRO)
type FeatureTrailingStopDTO struct {
	// Defines the activation threshold as a percentage of the take profit. For example, if TP is 1000 points and this is set to 50, trailing stop activates at 500 points profit. A value of 0 means this activation method is deactivated. Requires TakeProfit to be set on the trade. If both activationThresholdPoints and activationThresholdPercentage are active (>0), the maximum (most conservative) value will be used.
	ActivationThresholdPercentage *float64 `json:"activationThresholdPercentage,omitempty"`
	// Defines the activation threshold in points. Trailing stop starts only when profit reaches this value. A value of 0 means this activation method is deactivated. If both activationThresholdPoints and activationThresholdPercentage are active (>0), the maximum (most conservative) value will be used.
	ActivationThresholdPoints *int32 `json:"activationThresholdPoints,omitempty"`
	// Defines the initial stop loss distance in points from the entry price when the trade is opened. A value of 0 means no stop loss is applied initially.
	InitialStopLossPoints *int32 `json:"initialStopLossPoints,omitempty"`
	// Defines the minimum distance in points from the current price to the stop loss. Prevents the stop-loss from moving too close.
	MinimumDistancePoints *int32 `json:"minimumDistancePoints,omitempty"`
	// Defines the trailing stop configuration per symbol.
	SymbolsConfiguration *map[string]FeatureTrailingStopDTO `json:"symbolsConfiguration,omitempty"`
	// Defines the step distance in points at which the trailing stop will move as the trade progresses.
	TrailingStepPoints   *int32 `json:"trailingStepPoints,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _FeatureTrailingStopDTO FeatureTrailingStopDTO

// NewFeatureTrailingStopDTO instantiates a new FeatureTrailingStopDTO object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFeatureTrailingStopDTO() *FeatureTrailingStopDTO {
	this := FeatureTrailingStopDTO{}
	var activationThresholdPercentage float64 = 0
	this.ActivationThresholdPercentage = &activationThresholdPercentage
	var activationThresholdPoints int32 = 30
	this.ActivationThresholdPoints = &activationThresholdPoints
	var initialStopLossPoints int32 = 50
	this.InitialStopLossPoints = &initialStopLossPoints
	var minimumDistancePoints int32 = 20
	this.MinimumDistancePoints = &minimumDistancePoints
	var trailingStepPoints int32 = 10
	this.TrailingStepPoints = &trailingStepPoints
	return &this
}

// NewFeatureTrailingStopDTOWithDefaults instantiates a new FeatureTrailingStopDTO object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFeatureTrailingStopDTOWithDefaults() *FeatureTrailingStopDTO {
	this := FeatureTrailingStopDTO{}
	var activationThresholdPercentage float64 = 0
	this.ActivationThresholdPercentage = &activationThresholdPercentage
	var activationThresholdPoints int32 = 30
	this.ActivationThresholdPoints = &activationThresholdPoints
	var initialStopLossPoints int32 = 50
	this.InitialStopLossPoints = &initialStopLossPoints
	var minimumDistancePoints int32 = 20
	this.MinimumDistancePoints = &minimumDistancePoints
	var trailingStepPoints int32 = 10
	this.TrailingStepPoints = &trailingStepPoints
	return &this
}

// GetActivationThresholdPercentage returns the ActivationThresholdPercentage field value if set, zero value otherwise.
func (o *FeatureTrailingStopDTO) GetActivationThresholdPercentage() float64 {
	if o == nil || IsNil(o.ActivationThresholdPercentage) {
		var ret float64
		return ret
	}
	return *o.ActivationThresholdPercentage
}

// GetActivationThresholdPercentageOk returns a tuple with the ActivationThresholdPercentage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FeatureTrailingStopDTO) GetActivationThresholdPercentageOk() (*float64, bool) {
	if o == nil || IsNil(o.ActivationThresholdPercentage) {
		return nil, false
	}
	return o.ActivationThresholdPercentage, true
}

// HasActivationThresholdPercentage returns a boolean if a field has been set.
func (o *FeatureTrailingStopDTO) HasActivationThresholdPercentage() bool {
	if o != nil && !IsNil(o.ActivationThresholdPercentage) {
		return true
	}

	return false
}

// SetActivationThresholdPercentage gets a reference to the given float64 and assigns it to the ActivationThresholdPercentage field.
func (o *FeatureTrailingStopDTO) SetActivationThresholdPercentage(v float64) {
	o.ActivationThresholdPercentage = &v
}

// GetActivationThresholdPoints returns the ActivationThresholdPoints field value if set, zero value otherwise.
func (o *FeatureTrailingStopDTO) GetActivationThresholdPoints() int32 {
	if o == nil || IsNil(o.ActivationThresholdPoints) {
		var ret int32
		return ret
	}
	return *o.ActivationThresholdPoints
}

// GetActivationThresholdPointsOk returns a tuple with the ActivationThresholdPoints field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FeatureTrailingStopDTO) GetActivationThresholdPointsOk() (*int32, bool) {
	if o == nil || IsNil(o.ActivationThresholdPoints) {
		return nil, false
	}
	return o.ActivationThresholdPoints, true
}

// HasActivationThresholdPoints returns a boolean if a field has been set.
func (o *FeatureTrailingStopDTO) HasActivationThresholdPoints() bool {
	if o != nil && !IsNil(o.ActivationThresholdPoints) {
		return true
	}

	return false
}

// SetActivationThresholdPoints gets a reference to the given int32 and assigns it to the ActivationThresholdPoints field.
func (o *FeatureTrailingStopDTO) SetActivationThresholdPoints(v int32) {
	o.ActivationThresholdPoints = &v
}

// GetInitialStopLossPoints returns the InitialStopLossPoints field value if set, zero value otherwise.
func (o *FeatureTrailingStopDTO) GetInitialStopLossPoints() int32 {
	if o == nil || IsNil(o.InitialStopLossPoints) {
		var ret int32
		return ret
	}
	return *o.InitialStopLossPoints
}

// GetInitialStopLossPointsOk returns a tuple with the InitialStopLossPoints field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FeatureTrailingStopDTO) GetInitialStopLossPointsOk() (*int32, bool) {
	if o == nil || IsNil(o.InitialStopLossPoints) {
		return nil, false
	}
	return o.InitialStopLossPoints, true
}

// HasInitialStopLossPoints returns a boolean if a field has been set.
func (o *FeatureTrailingStopDTO) HasInitialStopLossPoints() bool {
	if o != nil && !IsNil(o.InitialStopLossPoints) {
		return true
	}

	return false
}

// SetInitialStopLossPoints gets a reference to the given int32 and assigns it to the InitialStopLossPoints field.
func (o *FeatureTrailingStopDTO) SetInitialStopLossPoints(v int32) {
	o.InitialStopLossPoints = &v
}

// GetMinimumDistancePoints returns the MinimumDistancePoints field value if set, zero value otherwise.
func (o *FeatureTrailingStopDTO) GetMinimumDistancePoints() int32 {
	if o == nil || IsNil(o.MinimumDistancePoints) {
		var ret int32
		return ret
	}
	return *o.MinimumDistancePoints
}

// GetMinimumDistancePointsOk returns a tuple with the MinimumDistancePoints field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FeatureTrailingStopDTO) GetMinimumDistancePointsOk() (*int32, bool) {
	if o == nil || IsNil(o.MinimumDistancePoints) {
		return nil, false
	}
	return o.MinimumDistancePoints, true
}

// HasMinimumDistancePoints returns a boolean if a field has been set.
func (o *FeatureTrailingStopDTO) HasMinimumDistancePoints() bool {
	if o != nil && !IsNil(o.MinimumDistancePoints) {
		return true
	}

	return false
}

// SetMinimumDistancePoints gets a reference to the given int32 and assigns it to the MinimumDistancePoints field.
func (o *FeatureTrailingStopDTO) SetMinimumDistancePoints(v int32) {
	o.MinimumDistancePoints = &v
}

// GetSymbolsConfiguration returns the SymbolsConfiguration field value if set, zero value otherwise.
func (o *FeatureTrailingStopDTO) GetSymbolsConfiguration() map[string]FeatureTrailingStopDTO {
	if o == nil || IsNil(o.SymbolsConfiguration) {
		var ret map[string]FeatureTrailingStopDTO
		return ret
	}
	return *o.SymbolsConfiguration
}

// GetSymbolsConfigurationOk returns a tuple with the SymbolsConfiguration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FeatureTrailingStopDTO) GetSymbolsConfigurationOk() (*map[string]FeatureTrailingStopDTO, bool) {
	if o == nil || IsNil(o.SymbolsConfiguration) {
		return nil, false
	}
	return o.SymbolsConfiguration, true
}

// HasSymbolsConfiguration returns a boolean if a field has been set.
func (o *FeatureTrailingStopDTO) HasSymbolsConfiguration() bool {
	if o != nil && !IsNil(o.SymbolsConfiguration) {
		return true
	}

	return false
}

// SetSymbolsConfiguration gets a reference to the given map[string]FeatureTrailingStopDTO and assigns it to the SymbolsConfiguration field.
func (o *FeatureTrailingStopDTO) SetSymbolsConfiguration(v map[string]FeatureTrailingStopDTO) {
	o.SymbolsConfiguration = &v
}

// GetTrailingStepPoints returns the TrailingStepPoints field value if set, zero value otherwise.
func (o *FeatureTrailingStopDTO) GetTrailingStepPoints() int32 {
	if o == nil || IsNil(o.TrailingStepPoints) {
		var ret int32
		return ret
	}
	return *o.TrailingStepPoints
}

// GetTrailingStepPointsOk returns a tuple with the TrailingStepPoints field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FeatureTrailingStopDTO) GetTrailingStepPointsOk() (*int32, bool) {
	if o == nil || IsNil(o.TrailingStepPoints) {
		return nil, false
	}
	return o.TrailingStepPoints, true
}

// HasTrailingStepPoints returns a boolean if a field has been set.
func (o *FeatureTrailingStopDTO) HasTrailingStepPoints() bool {
	if o != nil && !IsNil(o.TrailingStepPoints) {
		return true
	}

	return false
}

// SetTrailingStepPoints gets a reference to the given int32 and assigns it to the TrailingStepPoints field.
func (o *FeatureTrailingStopDTO) SetTrailingStepPoints(v int32) {
	o.TrailingStepPoints = &v
}

func (o FeatureTrailingStopDTO) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FeatureTrailingStopDTO) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ActivationThresholdPercentage) {
		toSerialize["activationThresholdPercentage"] = o.ActivationThresholdPercentage
	}
	if !IsNil(o.ActivationThresholdPoints) {
		toSerialize["activationThresholdPoints"] = o.ActivationThresholdPoints
	}
	if !IsNil(o.InitialStopLossPoints) {
		toSerialize["initialStopLossPoints"] = o.InitialStopLossPoints
	}
	if !IsNil(o.MinimumDistancePoints) {
		toSerialize["minimumDistancePoints"] = o.MinimumDistancePoints
	}
	if !IsNil(o.SymbolsConfiguration) {
		toSerialize["symbolsConfiguration"] = o.SymbolsConfiguration
	}
	if !IsNil(o.TrailingStepPoints) {
		toSerialize["trailingStepPoints"] = o.TrailingStepPoints
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *FeatureTrailingStopDTO) UnmarshalJSON(data []byte) (err error) {
	varFeatureTrailingStopDTO := _FeatureTrailingStopDTO{}

	err = json.Unmarshal(data, &varFeatureTrailingStopDTO)

	if err != nil {
		return err
	}

	*o = FeatureTrailingStopDTO(varFeatureTrailingStopDTO)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "activationThresholdPercentage")
		delete(additionalProperties, "activationThresholdPoints")
		delete(additionalProperties, "initialStopLossPoints")
		delete(additionalProperties, "minimumDistancePoints")
		delete(additionalProperties, "symbolsConfiguration")
		delete(additionalProperties, "trailingStepPoints")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableFeatureTrailingStopDTO struct {
	value *FeatureTrailingStopDTO
	isSet bool
}

func (v NullableFeatureTrailingStopDTO) Get() *FeatureTrailingStopDTO {
	return v.value
}

func (v *NullableFeatureTrailingStopDTO) Set(val *FeatureTrailingStopDTO) {
	v.value = val
	v.isSet = true
}

func (v NullableFeatureTrailingStopDTO) IsSet() bool {
	return v.isSet
}

func (v *NullableFeatureTrailingStopDTO) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFeatureTrailingStopDTO(val *FeatureTrailingStopDTO) *NullableFeatureTrailingStopDTO {
	return &NullableFeatureTrailingStopDTO{value: val, isSet: true}
}

func (v NullableFeatureTrailingStopDTO) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFeatureTrailingStopDTO) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
