/*
MetaCopier API

Explore the power of the MetaCopier API! Our RESTful API offers scalable and secure access to accounts, projects, and more. Get started quickly with authentication, explore endpoints, and access code samples in various languages.<br/><br/>All dates are in ISO 8601<br/><br/>This API is not designed for real-time communication purposes. For instance, continuously polling account information such as open positions every second is not recommended.<br/><br/>Our frontend uses this API, so you can look at the requests on our frontend for examples.

API version: 1.2.5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package metacopier

import (
	"encoding/json"
)

// checks if the PayoutDTO type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PayoutDTO{}

// PayoutDTO struct for PayoutDTO
type PayoutDTO struct {
	// Wise payout details
	WiseDetails          []WisePayoutDetailsDTO `json:"wiseDetails,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _PayoutDTO PayoutDTO

// NewPayoutDTO instantiates a new PayoutDTO object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPayoutDTO() *PayoutDTO {
	this := PayoutDTO{}
	return &this
}

// NewPayoutDTOWithDefaults instantiates a new PayoutDTO object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPayoutDTOWithDefaults() *PayoutDTO {
	this := PayoutDTO{}
	return &this
}

// GetWiseDetails returns the WiseDetails field value if set, zero value otherwise.
func (o *PayoutDTO) GetWiseDetails() []WisePayoutDetailsDTO {
	if o == nil || IsNil(o.WiseDetails) {
		var ret []WisePayoutDetailsDTO
		return ret
	}
	return o.WiseDetails
}

// GetWiseDetailsOk returns a tuple with the WiseDetails field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PayoutDTO) GetWiseDetailsOk() ([]WisePayoutDetailsDTO, bool) {
	if o == nil || IsNil(o.WiseDetails) {
		return nil, false
	}
	return o.WiseDetails, true
}

// HasWiseDetails returns a boolean if a field has been set.
func (o *PayoutDTO) HasWiseDetails() bool {
	if o != nil && !IsNil(o.WiseDetails) {
		return true
	}

	return false
}

// SetWiseDetails gets a reference to the given []WisePayoutDetailsDTO and assigns it to the WiseDetails field.
func (o *PayoutDTO) SetWiseDetails(v []WisePayoutDetailsDTO) {
	o.WiseDetails = v
}

func (o PayoutDTO) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PayoutDTO) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.WiseDetails) {
		toSerialize["wiseDetails"] = o.WiseDetails
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PayoutDTO) UnmarshalJSON(data []byte) (err error) {
	varPayoutDTO := _PayoutDTO{}

	err = json.Unmarshal(data, &varPayoutDTO)

	if err != nil {
		return err
	}

	*o = PayoutDTO(varPayoutDTO)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "wiseDetails")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePayoutDTO struct {
	value *PayoutDTO
	isSet bool
}

func (v NullablePayoutDTO) Get() *PayoutDTO {
	return v.value
}

func (v *NullablePayoutDTO) Set(val *PayoutDTO) {
	v.value = val
	v.isSet = true
}

func (v NullablePayoutDTO) IsSet() bool {
	return v.isSet
}

func (v *NullablePayoutDTO) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePayoutDTO(val *PayoutDTO) *NullablePayoutDTO {
	return &NullablePayoutDTO{value: val, isSet: true}
}

func (v NullablePayoutDTO) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePayoutDTO) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
