/*
MetaCopier API

Explore the power of the MetaCopier API! Our RESTful API offers scalable and secure access to accounts, projects, and more. Get started quickly with authentication, explore endpoints, and access code samples in various languages.<br/><br/>All dates are in ISO 8601<br/><br/>This API is not designed for real-time communication purposes. For instance, continuously polling account information such as open positions every second is not recommended.<br/><br/>Our frontend uses this API, so you can look at the requests on our frontend for examples.

API version: 1.2.5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package metacopier

import (
	"encoding/json"
	"fmt"
	"time"
)

// checks if the FeatureMaintenanceWindowDTO type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FeatureMaintenanceWindowDTO{}

// FeatureMaintenanceWindowDTO DTO for defining a maintenance window (project)
type FeatureMaintenanceWindowDTO struct {
	AccountType *AccountTypeDTO `json:"accountType,omitempty"`
	// Is only applied to a specific broker, for example, 'ICMarkets.*' (case non sensitive). For all brokers, you can enter '.*' or null (this is a regex)
	Broker *string `json:"broker,omitempty"`
	// If true, all open positions are closed at the beginning of the maintenance window
	CloseAllPositions *bool `json:"closeAllPositions,omitempty"`
	// End time of the maintenance window.
	EndTime time.Time `json:"endTime"`
	// Start time of the maintenance window.
	StartTime            time.Time `json:"startTime"`
	AdditionalProperties map[string]interface{}
}

type _FeatureMaintenanceWindowDTO FeatureMaintenanceWindowDTO

// NewFeatureMaintenanceWindowDTO instantiates a new FeatureMaintenanceWindowDTO object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFeatureMaintenanceWindowDTO(endTime time.Time, startTime time.Time) *FeatureMaintenanceWindowDTO {
	this := FeatureMaintenanceWindowDTO{}
	this.EndTime = endTime
	this.StartTime = startTime
	return &this
}

// NewFeatureMaintenanceWindowDTOWithDefaults instantiates a new FeatureMaintenanceWindowDTO object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFeatureMaintenanceWindowDTOWithDefaults() *FeatureMaintenanceWindowDTO {
	this := FeatureMaintenanceWindowDTO{}
	return &this
}

// GetAccountType returns the AccountType field value if set, zero value otherwise.
func (o *FeatureMaintenanceWindowDTO) GetAccountType() AccountTypeDTO {
	if o == nil || IsNil(o.AccountType) {
		var ret AccountTypeDTO
		return ret
	}
	return *o.AccountType
}

// GetAccountTypeOk returns a tuple with the AccountType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FeatureMaintenanceWindowDTO) GetAccountTypeOk() (*AccountTypeDTO, bool) {
	if o == nil || IsNil(o.AccountType) {
		return nil, false
	}
	return o.AccountType, true
}

// HasAccountType returns a boolean if a field has been set.
func (o *FeatureMaintenanceWindowDTO) HasAccountType() bool {
	if o != nil && !IsNil(o.AccountType) {
		return true
	}

	return false
}

// SetAccountType gets a reference to the given AccountTypeDTO and assigns it to the AccountType field.
func (o *FeatureMaintenanceWindowDTO) SetAccountType(v AccountTypeDTO) {
	o.AccountType = &v
}

// GetBroker returns the Broker field value if set, zero value otherwise.
func (o *FeatureMaintenanceWindowDTO) GetBroker() string {
	if o == nil || IsNil(o.Broker) {
		var ret string
		return ret
	}
	return *o.Broker
}

// GetBrokerOk returns a tuple with the Broker field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FeatureMaintenanceWindowDTO) GetBrokerOk() (*string, bool) {
	if o == nil || IsNil(o.Broker) {
		return nil, false
	}
	return o.Broker, true
}

// HasBroker returns a boolean if a field has been set.
func (o *FeatureMaintenanceWindowDTO) HasBroker() bool {
	if o != nil && !IsNil(o.Broker) {
		return true
	}

	return false
}

// SetBroker gets a reference to the given string and assigns it to the Broker field.
func (o *FeatureMaintenanceWindowDTO) SetBroker(v string) {
	o.Broker = &v
}

// GetCloseAllPositions returns the CloseAllPositions field value if set, zero value otherwise.
func (o *FeatureMaintenanceWindowDTO) GetCloseAllPositions() bool {
	if o == nil || IsNil(o.CloseAllPositions) {
		var ret bool
		return ret
	}
	return *o.CloseAllPositions
}

// GetCloseAllPositionsOk returns a tuple with the CloseAllPositions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FeatureMaintenanceWindowDTO) GetCloseAllPositionsOk() (*bool, bool) {
	if o == nil || IsNil(o.CloseAllPositions) {
		return nil, false
	}
	return o.CloseAllPositions, true
}

// HasCloseAllPositions returns a boolean if a field has been set.
func (o *FeatureMaintenanceWindowDTO) HasCloseAllPositions() bool {
	if o != nil && !IsNil(o.CloseAllPositions) {
		return true
	}

	return false
}

// SetCloseAllPositions gets a reference to the given bool and assigns it to the CloseAllPositions field.
func (o *FeatureMaintenanceWindowDTO) SetCloseAllPositions(v bool) {
	o.CloseAllPositions = &v
}

// GetEndTime returns the EndTime field value
func (o *FeatureMaintenanceWindowDTO) GetEndTime() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.EndTime
}

// GetEndTimeOk returns a tuple with the EndTime field value
// and a boolean to check if the value has been set.
func (o *FeatureMaintenanceWindowDTO) GetEndTimeOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EndTime, true
}

// SetEndTime sets field value
func (o *FeatureMaintenanceWindowDTO) SetEndTime(v time.Time) {
	o.EndTime = v
}

// GetStartTime returns the StartTime field value
func (o *FeatureMaintenanceWindowDTO) GetStartTime() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.StartTime
}

// GetStartTimeOk returns a tuple with the StartTime field value
// and a boolean to check if the value has been set.
func (o *FeatureMaintenanceWindowDTO) GetStartTimeOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StartTime, true
}

// SetStartTime sets field value
func (o *FeatureMaintenanceWindowDTO) SetStartTime(v time.Time) {
	o.StartTime = v
}

func (o FeatureMaintenanceWindowDTO) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FeatureMaintenanceWindowDTO) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AccountType) {
		toSerialize["accountType"] = o.AccountType
	}
	if !IsNil(o.Broker) {
		toSerialize["broker"] = o.Broker
	}
	if !IsNil(o.CloseAllPositions) {
		toSerialize["closeAllPositions"] = o.CloseAllPositions
	}
	toSerialize["endTime"] = o.EndTime
	toSerialize["startTime"] = o.StartTime

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *FeatureMaintenanceWindowDTO) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"endTime",
		"startTime",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFeatureMaintenanceWindowDTO := _FeatureMaintenanceWindowDTO{}

	err = json.Unmarshal(data, &varFeatureMaintenanceWindowDTO)

	if err != nil {
		return err
	}

	*o = FeatureMaintenanceWindowDTO(varFeatureMaintenanceWindowDTO)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "accountType")
		delete(additionalProperties, "broker")
		delete(additionalProperties, "closeAllPositions")
		delete(additionalProperties, "endTime")
		delete(additionalProperties, "startTime")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableFeatureMaintenanceWindowDTO struct {
	value *FeatureMaintenanceWindowDTO
	isSet bool
}

func (v NullableFeatureMaintenanceWindowDTO) Get() *FeatureMaintenanceWindowDTO {
	return v.value
}

func (v *NullableFeatureMaintenanceWindowDTO) Set(val *FeatureMaintenanceWindowDTO) {
	v.value = val
	v.isSet = true
}

func (v NullableFeatureMaintenanceWindowDTO) IsSet() bool {
	return v.isSet
}

func (v *NullableFeatureMaintenanceWindowDTO) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFeatureMaintenanceWindowDTO(val *FeatureMaintenanceWindowDTO) *NullableFeatureMaintenanceWindowDTO {
	return &NullableFeatureMaintenanceWindowDTO{value: val, isSet: true}
}

func (v NullableFeatureMaintenanceWindowDTO) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFeatureMaintenanceWindowDTO) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
