/*
MetaCopier API

Explore the power of the MetaCopier API! Our RESTful API offers scalable and secure access to accounts, projects, and more. Get started quickly with authentication, explore endpoints, and access code samples in various languages.<br/><br/>All dates are in ISO 8601<br/><br/>This API is not designed for real-time communication purposes. For instance, continuously polling account information such as open positions every second is not recommended.<br/><br/>Our frontend uses this API, so you can look at the requests on our frontend for examples.

API version: 1.2.5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package metacopier

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the PositionRequestDTO type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PositionRequestDTO{}

// PositionRequestDTO struct for PositionRequestDTO
type PositionRequestDTO struct {
	// An 'API|YOUR_REQUEST_ID|' is prepended to your comment for tracking purpose (this prefix is only used for the endpoint /rest/api/v1/accounts/{accountId}/positions)
	Comment *string `json:"comment,omitempty"`
	// At the moment, only numbers as string are supported
	MagicNumber *string `json:"magicNumber,omitempty"`
	// Used for pending orders (buy limit, stop limit, ...). For buy or sell you can enter 0.
	OpenPrice float32 `json:"openPrice"`
	OrderType string  `json:"orderType"`
	// Indicates if stop loss and take profit are relative values in points when opening new positions (cTrader accounts only)
	RelativeTpSl *bool `json:"relativeTpSl,omitempty"`
	// A client request ID to avoid the request being executed multiple times due to network or client errors. The IDs start at 0 and increment up to 999, then begin again at 0.
	RequestId int64 `json:"requestId"`
	// A value of 0 means no stop loss
	StopLoss float32 `json:"stopLoss"`
	Symbol   string  `json:"symbol"`
	// A value of 0 means no take profit
	TakeProfit float32 `json:"takeProfit"`
	// In lots. The volume will be automatically adjusted according to the symbol data.
	Volume float32 `json:"volume"`
}

type _PositionRequestDTO PositionRequestDTO

// NewPositionRequestDTO instantiates a new PositionRequestDTO object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPositionRequestDTO(openPrice float32, orderType string, requestId int64, stopLoss float32, symbol string, takeProfit float32, volume float32) *PositionRequestDTO {
	this := PositionRequestDTO{}
	this.OpenPrice = openPrice
	this.OrderType = orderType
	var relativeTpSl bool = false
	this.RelativeTpSl = &relativeTpSl
	this.RequestId = requestId
	this.StopLoss = stopLoss
	this.Symbol = symbol
	this.TakeProfit = takeProfit
	this.Volume = volume
	return &this
}

// NewPositionRequestDTOWithDefaults instantiates a new PositionRequestDTO object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPositionRequestDTOWithDefaults() *PositionRequestDTO {
	this := PositionRequestDTO{}
	var openPrice float32 = 0
	this.OpenPrice = openPrice
	var relativeTpSl bool = false
	this.RelativeTpSl = &relativeTpSl
	var stopLoss float32 = 0
	this.StopLoss = stopLoss
	var takeProfit float32 = 0
	this.TakeProfit = takeProfit
	return &this
}

// GetComment returns the Comment field value if set, zero value otherwise.
func (o *PositionRequestDTO) GetComment() string {
	if o == nil || IsNil(o.Comment) {
		var ret string
		return ret
	}
	return *o.Comment
}

// GetCommentOk returns a tuple with the Comment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PositionRequestDTO) GetCommentOk() (*string, bool) {
	if o == nil || IsNil(o.Comment) {
		return nil, false
	}
	return o.Comment, true
}

// HasComment returns a boolean if a field has been set.
func (o *PositionRequestDTO) HasComment() bool {
	if o != nil && !IsNil(o.Comment) {
		return true
	}

	return false
}

// SetComment gets a reference to the given string and assigns it to the Comment field.
func (o *PositionRequestDTO) SetComment(v string) {
	o.Comment = &v
}

// GetMagicNumber returns the MagicNumber field value if set, zero value otherwise.
func (o *PositionRequestDTO) GetMagicNumber() string {
	if o == nil || IsNil(o.MagicNumber) {
		var ret string
		return ret
	}
	return *o.MagicNumber
}

// GetMagicNumberOk returns a tuple with the MagicNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PositionRequestDTO) GetMagicNumberOk() (*string, bool) {
	if o == nil || IsNil(o.MagicNumber) {
		return nil, false
	}
	return o.MagicNumber, true
}

// HasMagicNumber returns a boolean if a field has been set.
func (o *PositionRequestDTO) HasMagicNumber() bool {
	if o != nil && !IsNil(o.MagicNumber) {
		return true
	}

	return false
}

// SetMagicNumber gets a reference to the given string and assigns it to the MagicNumber field.
func (o *PositionRequestDTO) SetMagicNumber(v string) {
	o.MagicNumber = &v
}

// GetOpenPrice returns the OpenPrice field value
func (o *PositionRequestDTO) GetOpenPrice() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.OpenPrice
}

// GetOpenPriceOk returns a tuple with the OpenPrice field value
// and a boolean to check if the value has been set.
func (o *PositionRequestDTO) GetOpenPriceOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OpenPrice, true
}

// SetOpenPrice sets field value
func (o *PositionRequestDTO) SetOpenPrice(v float32) {
	o.OpenPrice = v
}

// GetOrderType returns the OrderType field value
func (o *PositionRequestDTO) GetOrderType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OrderType
}

// GetOrderTypeOk returns a tuple with the OrderType field value
// and a boolean to check if the value has been set.
func (o *PositionRequestDTO) GetOrderTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrderType, true
}

// SetOrderType sets field value
func (o *PositionRequestDTO) SetOrderType(v string) {
	o.OrderType = v
}

// GetRelativeTpSl returns the RelativeTpSl field value if set, zero value otherwise.
func (o *PositionRequestDTO) GetRelativeTpSl() bool {
	if o == nil || IsNil(o.RelativeTpSl) {
		var ret bool
		return ret
	}
	return *o.RelativeTpSl
}

// GetRelativeTpSlOk returns a tuple with the RelativeTpSl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PositionRequestDTO) GetRelativeTpSlOk() (*bool, bool) {
	if o == nil || IsNil(o.RelativeTpSl) {
		return nil, false
	}
	return o.RelativeTpSl, true
}

// HasRelativeTpSl returns a boolean if a field has been set.
func (o *PositionRequestDTO) HasRelativeTpSl() bool {
	if o != nil && !IsNil(o.RelativeTpSl) {
		return true
	}

	return false
}

// SetRelativeTpSl gets a reference to the given bool and assigns it to the RelativeTpSl field.
func (o *PositionRequestDTO) SetRelativeTpSl(v bool) {
	o.RelativeTpSl = &v
}

// GetRequestId returns the RequestId field value
func (o *PositionRequestDTO) GetRequestId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.RequestId
}

// GetRequestIdOk returns a tuple with the RequestId field value
// and a boolean to check if the value has been set.
func (o *PositionRequestDTO) GetRequestIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RequestId, true
}

// SetRequestId sets field value
func (o *PositionRequestDTO) SetRequestId(v int64) {
	o.RequestId = v
}

// GetStopLoss returns the StopLoss field value
func (o *PositionRequestDTO) GetStopLoss() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.StopLoss
}

// GetStopLossOk returns a tuple with the StopLoss field value
// and a boolean to check if the value has been set.
func (o *PositionRequestDTO) GetStopLossOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StopLoss, true
}

// SetStopLoss sets field value
func (o *PositionRequestDTO) SetStopLoss(v float32) {
	o.StopLoss = v
}

// GetSymbol returns the Symbol field value
func (o *PositionRequestDTO) GetSymbol() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Symbol
}

// GetSymbolOk returns a tuple with the Symbol field value
// and a boolean to check if the value has been set.
func (o *PositionRequestDTO) GetSymbolOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Symbol, true
}

// SetSymbol sets field value
func (o *PositionRequestDTO) SetSymbol(v string) {
	o.Symbol = v
}

// GetTakeProfit returns the TakeProfit field value
func (o *PositionRequestDTO) GetTakeProfit() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.TakeProfit
}

// GetTakeProfitOk returns a tuple with the TakeProfit field value
// and a boolean to check if the value has been set.
func (o *PositionRequestDTO) GetTakeProfitOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TakeProfit, true
}

// SetTakeProfit sets field value
func (o *PositionRequestDTO) SetTakeProfit(v float32) {
	o.TakeProfit = v
}

// GetVolume returns the Volume field value
func (o *PositionRequestDTO) GetVolume() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Volume
}

// GetVolumeOk returns a tuple with the Volume field value
// and a boolean to check if the value has been set.
func (o *PositionRequestDTO) GetVolumeOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Volume, true
}

// SetVolume sets field value
func (o *PositionRequestDTO) SetVolume(v float32) {
	o.Volume = v
}

func (o PositionRequestDTO) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PositionRequestDTO) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Comment) {
		toSerialize["comment"] = o.Comment
	}
	if !IsNil(o.MagicNumber) {
		toSerialize["magicNumber"] = o.MagicNumber
	}
	toSerialize["openPrice"] = o.OpenPrice
	toSerialize["orderType"] = o.OrderType
	if !IsNil(o.RelativeTpSl) {
		toSerialize["relativeTpSl"] = o.RelativeTpSl
	}
	toSerialize["requestId"] = o.RequestId
	toSerialize["stopLoss"] = o.StopLoss
	toSerialize["symbol"] = o.Symbol
	toSerialize["takeProfit"] = o.TakeProfit
	toSerialize["volume"] = o.Volume
	return toSerialize, nil
}

func (o *PositionRequestDTO) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"openPrice",
		"orderType",
		"requestId",
		"stopLoss",
		"symbol",
		"takeProfit",
		"volume",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPositionRequestDTO := _PositionRequestDTO{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPositionRequestDTO)

	if err != nil {
		return err
	}

	*o = PositionRequestDTO(varPositionRequestDTO)

	return err
}

type NullablePositionRequestDTO struct {
	value *PositionRequestDTO
	isSet bool
}

func (v NullablePositionRequestDTO) Get() *PositionRequestDTO {
	return v.value
}

func (v *NullablePositionRequestDTO) Set(val *PositionRequestDTO) {
	v.value = val
	v.isSet = true
}

func (v NullablePositionRequestDTO) IsSet() bool {
	return v.isSet
}

func (v *NullablePositionRequestDTO) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePositionRequestDTO(val *PositionRequestDTO) *NullablePositionRequestDTO {
	return &NullablePositionRequestDTO{value: val, isSet: true}
}

func (v NullablePositionRequestDTO) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePositionRequestDTO) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
