/*
MetaCopier API

Explore the power of the MetaCopier API! Our RESTful API offers scalable and secure access to accounts, projects, and more. Get started quickly with authentication, explore endpoints, and access code samples in various languages.<br/><br/>All dates are in ISO 8601<br/><br/>This API is not designed for real-time communication purposes. For instance, continuously polling account information such as open positions every second is not recommended.<br/><br/>Our frontend uses this API, so you can look at the requests on our frontend for examples.

API version: 1.2.5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package metacopier

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// FeatureSettingDTO - Configure setting for the specific feature
type FeatureSettingDTO struct {
	FeatureApprovalDTO               *FeatureApprovalDTO
	FeatureBreakEvenDTO              *FeatureBreakEvenDTO
	FeatureCopierFilterDTO           *FeatureCopierFilterDTO
	FeatureDailyProfitTargetDTO      *FeatureDailyProfitTargetDTO
	FeatureDataCollectorDTO          *FeatureDataCollectorDTO
	FeatureDedicatedIpDTO            *FeatureDedicatedIpDTO
	FeatureDedicatedIpPoolDTO        *FeatureDedicatedIpPoolDTO
	FeatureDelayedExecutionDTO       *FeatureDelayedExecutionDTO
	FeatureExitSignalOverrideDTO     *FeatureExitSignalOverrideDTO
	FeatureFallbackSettingDTO        *FeatureFallbackSettingDTO
	FeatureHftModeDTO                *FeatureHftModeDTO
	FeatureKeepAliveTradeDTO         *FeatureKeepAliveTradeDTO
	FeatureLiveDelayDTO              *FeatureLiveDelayDTO
	FeatureMaintenanceWindowDTO      *FeatureMaintenanceWindowDTO
	FeatureMasanielloDTO             *FeatureMasanielloDTO
	FeatureMaxLotSizeDTO             *FeatureMaxLotSizeDTO
	FeatureMaxOpenPositionsDTO       *FeatureMaxOpenPositionsDTO
	FeatureMaximumLotDTO             *FeatureMaximumLotDTO
	FeatureMinimumHoldingTimeDTO     *FeatureMinimumHoldingTimeDTO
	FeatureMonthlyProfitTargetDTO    *FeatureMonthlyProfitTargetDTO
	FeatureMultiplierDTO             *FeatureMultiplierDTO
	FeatureMyHomeIpDTO               *FeatureMyHomeIpDTO
	FeatureOrderTypeFilterDTO        *FeatureOrderTypeFilterDTO
	FeaturePermittedSymbolsDTO       *FeaturePermittedSymbolsDTO
	FeatureProgressiveTradeSizingDTO *FeatureProgressiveTradeSizingDTO
	FeatureRiskPerTradeDTO           *FeatureRiskPerTradeDTO
	FeatureSignalFollowerDTO         *FeatureSignalFollowerDTO
	FeatureSignalProviderDTO         *FeatureSignalProviderDTO
	FeatureSkipPositionDTO           *FeatureSkipPositionDTO
	FeatureSocketDTO                 *FeatureSocketDTO
	FeatureTelegramNotificationDTO   *FeatureTelegramNotificationDTO
	FeatureTpSlManagementDTO         *FeatureTpSlManagementDTO
	FeatureTradeGuardrailsDTO        *FeatureTradeGuardrailsDTO
	FeatureTradingWindowsDTO         *FeatureTradingWindowsDTO
	FeatureTrailingStopDTO           *FeatureTrailingStopDTO
	FeatureWeeklyProfitTargetDTO     *FeatureWeeklyProfitTargetDTO
	FeatureWhiteLabelDTO             *FeatureWhiteLabelDTO
}

// FeatureApprovalDTOAsFeatureSettingDTO is a convenience function that returns FeatureApprovalDTO wrapped in FeatureSettingDTO
func FeatureApprovalDTOAsFeatureSettingDTO(v *FeatureApprovalDTO) FeatureSettingDTO {
	return FeatureSettingDTO{
		FeatureApprovalDTO: v,
	}
}

// FeatureBreakEvenDTOAsFeatureSettingDTO is a convenience function that returns FeatureBreakEvenDTO wrapped in FeatureSettingDTO
func FeatureBreakEvenDTOAsFeatureSettingDTO(v *FeatureBreakEvenDTO) FeatureSettingDTO {
	return FeatureSettingDTO{
		FeatureBreakEvenDTO: v,
	}
}

// FeatureCopierFilterDTOAsFeatureSettingDTO is a convenience function that returns FeatureCopierFilterDTO wrapped in FeatureSettingDTO
func FeatureCopierFilterDTOAsFeatureSettingDTO(v *FeatureCopierFilterDTO) FeatureSettingDTO {
	return FeatureSettingDTO{
		FeatureCopierFilterDTO: v,
	}
}

// FeatureDailyProfitTargetDTOAsFeatureSettingDTO is a convenience function that returns FeatureDailyProfitTargetDTO wrapped in FeatureSettingDTO
func FeatureDailyProfitTargetDTOAsFeatureSettingDTO(v *FeatureDailyProfitTargetDTO) FeatureSettingDTO {
	return FeatureSettingDTO{
		FeatureDailyProfitTargetDTO: v,
	}
}

// FeatureDataCollectorDTOAsFeatureSettingDTO is a convenience function that returns FeatureDataCollectorDTO wrapped in FeatureSettingDTO
func FeatureDataCollectorDTOAsFeatureSettingDTO(v *FeatureDataCollectorDTO) FeatureSettingDTO {
	return FeatureSettingDTO{
		FeatureDataCollectorDTO: v,
	}
}

// FeatureDedicatedIpDTOAsFeatureSettingDTO is a convenience function that returns FeatureDedicatedIpDTO wrapped in FeatureSettingDTO
func FeatureDedicatedIpDTOAsFeatureSettingDTO(v *FeatureDedicatedIpDTO) FeatureSettingDTO {
	return FeatureSettingDTO{
		FeatureDedicatedIpDTO: v,
	}
}

// FeatureDedicatedIpPoolDTOAsFeatureSettingDTO is a convenience function that returns FeatureDedicatedIpPoolDTO wrapped in FeatureSettingDTO
func FeatureDedicatedIpPoolDTOAsFeatureSettingDTO(v *FeatureDedicatedIpPoolDTO) FeatureSettingDTO {
	return FeatureSettingDTO{
		FeatureDedicatedIpPoolDTO: v,
	}
}

// FeatureDelayedExecutionDTOAsFeatureSettingDTO is a convenience function that returns FeatureDelayedExecutionDTO wrapped in FeatureSettingDTO
func FeatureDelayedExecutionDTOAsFeatureSettingDTO(v *FeatureDelayedExecutionDTO) FeatureSettingDTO {
	return FeatureSettingDTO{
		FeatureDelayedExecutionDTO: v,
	}
}

// FeatureExitSignalOverrideDTOAsFeatureSettingDTO is a convenience function that returns FeatureExitSignalOverrideDTO wrapped in FeatureSettingDTO
func FeatureExitSignalOverrideDTOAsFeatureSettingDTO(v *FeatureExitSignalOverrideDTO) FeatureSettingDTO {
	return FeatureSettingDTO{
		FeatureExitSignalOverrideDTO: v,
	}
}

// FeatureFallbackSettingDTOAsFeatureSettingDTO is a convenience function that returns FeatureFallbackSettingDTO wrapped in FeatureSettingDTO
func FeatureFallbackSettingDTOAsFeatureSettingDTO(v *FeatureFallbackSettingDTO) FeatureSettingDTO {
	return FeatureSettingDTO{
		FeatureFallbackSettingDTO: v,
	}
}

// FeatureHftModeDTOAsFeatureSettingDTO is a convenience function that returns FeatureHftModeDTO wrapped in FeatureSettingDTO
func FeatureHftModeDTOAsFeatureSettingDTO(v *FeatureHftModeDTO) FeatureSettingDTO {
	return FeatureSettingDTO{
		FeatureHftModeDTO: v,
	}
}

// FeatureKeepAliveTradeDTOAsFeatureSettingDTO is a convenience function that returns FeatureKeepAliveTradeDTO wrapped in FeatureSettingDTO
func FeatureKeepAliveTradeDTOAsFeatureSettingDTO(v *FeatureKeepAliveTradeDTO) FeatureSettingDTO {
	return FeatureSettingDTO{
		FeatureKeepAliveTradeDTO: v,
	}
}

// FeatureLiveDelayDTOAsFeatureSettingDTO is a convenience function that returns FeatureLiveDelayDTO wrapped in FeatureSettingDTO
func FeatureLiveDelayDTOAsFeatureSettingDTO(v *FeatureLiveDelayDTO) FeatureSettingDTO {
	return FeatureSettingDTO{
		FeatureLiveDelayDTO: v,
	}
}

// FeatureMaintenanceWindowDTOAsFeatureSettingDTO is a convenience function that returns FeatureMaintenanceWindowDTO wrapped in FeatureSettingDTO
func FeatureMaintenanceWindowDTOAsFeatureSettingDTO(v *FeatureMaintenanceWindowDTO) FeatureSettingDTO {
	return FeatureSettingDTO{
		FeatureMaintenanceWindowDTO: v,
	}
}

// FeatureMasanielloDTOAsFeatureSettingDTO is a convenience function that returns FeatureMasanielloDTO wrapped in FeatureSettingDTO
func FeatureMasanielloDTOAsFeatureSettingDTO(v *FeatureMasanielloDTO) FeatureSettingDTO {
	return FeatureSettingDTO{
		FeatureMasanielloDTO: v,
	}
}

// FeatureMaxLotSizeDTOAsFeatureSettingDTO is a convenience function that returns FeatureMaxLotSizeDTO wrapped in FeatureSettingDTO
func FeatureMaxLotSizeDTOAsFeatureSettingDTO(v *FeatureMaxLotSizeDTO) FeatureSettingDTO {
	return FeatureSettingDTO{
		FeatureMaxLotSizeDTO: v,
	}
}

// FeatureMaxOpenPositionsDTOAsFeatureSettingDTO is a convenience function that returns FeatureMaxOpenPositionsDTO wrapped in FeatureSettingDTO
func FeatureMaxOpenPositionsDTOAsFeatureSettingDTO(v *FeatureMaxOpenPositionsDTO) FeatureSettingDTO {
	return FeatureSettingDTO{
		FeatureMaxOpenPositionsDTO: v,
	}
}

// FeatureMaximumLotDTOAsFeatureSettingDTO is a convenience function that returns FeatureMaximumLotDTO wrapped in FeatureSettingDTO
func FeatureMaximumLotDTOAsFeatureSettingDTO(v *FeatureMaximumLotDTO) FeatureSettingDTO {
	return FeatureSettingDTO{
		FeatureMaximumLotDTO: v,
	}
}

// FeatureMinimumHoldingTimeDTOAsFeatureSettingDTO is a convenience function that returns FeatureMinimumHoldingTimeDTO wrapped in FeatureSettingDTO
func FeatureMinimumHoldingTimeDTOAsFeatureSettingDTO(v *FeatureMinimumHoldingTimeDTO) FeatureSettingDTO {
	return FeatureSettingDTO{
		FeatureMinimumHoldingTimeDTO: v,
	}
}

// FeatureMonthlyProfitTargetDTOAsFeatureSettingDTO is a convenience function that returns FeatureMonthlyProfitTargetDTO wrapped in FeatureSettingDTO
func FeatureMonthlyProfitTargetDTOAsFeatureSettingDTO(v *FeatureMonthlyProfitTargetDTO) FeatureSettingDTO {
	return FeatureSettingDTO{
		FeatureMonthlyProfitTargetDTO: v,
	}
}

// FeatureMultiplierDTOAsFeatureSettingDTO is a convenience function that returns FeatureMultiplierDTO wrapped in FeatureSettingDTO
func FeatureMultiplierDTOAsFeatureSettingDTO(v *FeatureMultiplierDTO) FeatureSettingDTO {
	return FeatureSettingDTO{
		FeatureMultiplierDTO: v,
	}
}

// FeatureMyHomeIpDTOAsFeatureSettingDTO is a convenience function that returns FeatureMyHomeIpDTO wrapped in FeatureSettingDTO
func FeatureMyHomeIpDTOAsFeatureSettingDTO(v *FeatureMyHomeIpDTO) FeatureSettingDTO {
	return FeatureSettingDTO{
		FeatureMyHomeIpDTO: v,
	}
}

// FeatureOrderTypeFilterDTOAsFeatureSettingDTO is a convenience function that returns FeatureOrderTypeFilterDTO wrapped in FeatureSettingDTO
func FeatureOrderTypeFilterDTOAsFeatureSettingDTO(v *FeatureOrderTypeFilterDTO) FeatureSettingDTO {
	return FeatureSettingDTO{
		FeatureOrderTypeFilterDTO: v,
	}
}

// FeaturePermittedSymbolsDTOAsFeatureSettingDTO is a convenience function that returns FeaturePermittedSymbolsDTO wrapped in FeatureSettingDTO
func FeaturePermittedSymbolsDTOAsFeatureSettingDTO(v *FeaturePermittedSymbolsDTO) FeatureSettingDTO {
	return FeatureSettingDTO{
		FeaturePermittedSymbolsDTO: v,
	}
}

// FeatureProgressiveTradeSizingDTOAsFeatureSettingDTO is a convenience function that returns FeatureProgressiveTradeSizingDTO wrapped in FeatureSettingDTO
func FeatureProgressiveTradeSizingDTOAsFeatureSettingDTO(v *FeatureProgressiveTradeSizingDTO) FeatureSettingDTO {
	return FeatureSettingDTO{
		FeatureProgressiveTradeSizingDTO: v,
	}
}

// FeatureRiskPerTradeDTOAsFeatureSettingDTO is a convenience function that returns FeatureRiskPerTradeDTO wrapped in FeatureSettingDTO
func FeatureRiskPerTradeDTOAsFeatureSettingDTO(v *FeatureRiskPerTradeDTO) FeatureSettingDTO {
	return FeatureSettingDTO{
		FeatureRiskPerTradeDTO: v,
	}
}

// FeatureSignalFollowerDTOAsFeatureSettingDTO is a convenience function that returns FeatureSignalFollowerDTO wrapped in FeatureSettingDTO
func FeatureSignalFollowerDTOAsFeatureSettingDTO(v *FeatureSignalFollowerDTO) FeatureSettingDTO {
	return FeatureSettingDTO{
		FeatureSignalFollowerDTO: v,
	}
}

// FeatureSignalProviderDTOAsFeatureSettingDTO is a convenience function that returns FeatureSignalProviderDTO wrapped in FeatureSettingDTO
func FeatureSignalProviderDTOAsFeatureSettingDTO(v *FeatureSignalProviderDTO) FeatureSettingDTO {
	return FeatureSettingDTO{
		FeatureSignalProviderDTO: v,
	}
}

// FeatureSkipPositionDTOAsFeatureSettingDTO is a convenience function that returns FeatureSkipPositionDTO wrapped in FeatureSettingDTO
func FeatureSkipPositionDTOAsFeatureSettingDTO(v *FeatureSkipPositionDTO) FeatureSettingDTO {
	return FeatureSettingDTO{
		FeatureSkipPositionDTO: v,
	}
}

// FeatureSocketDTOAsFeatureSettingDTO is a convenience function that returns FeatureSocketDTO wrapped in FeatureSettingDTO
func FeatureSocketDTOAsFeatureSettingDTO(v *FeatureSocketDTO) FeatureSettingDTO {
	return FeatureSettingDTO{
		FeatureSocketDTO: v,
	}
}

// FeatureTelegramNotificationDTOAsFeatureSettingDTO is a convenience function that returns FeatureTelegramNotificationDTO wrapped in FeatureSettingDTO
func FeatureTelegramNotificationDTOAsFeatureSettingDTO(v *FeatureTelegramNotificationDTO) FeatureSettingDTO {
	return FeatureSettingDTO{
		FeatureTelegramNotificationDTO: v,
	}
}

// FeatureTpSlManagementDTOAsFeatureSettingDTO is a convenience function that returns FeatureTpSlManagementDTO wrapped in FeatureSettingDTO
func FeatureTpSlManagementDTOAsFeatureSettingDTO(v *FeatureTpSlManagementDTO) FeatureSettingDTO {
	return FeatureSettingDTO{
		FeatureTpSlManagementDTO: v,
	}
}

// FeatureTradeGuardrailsDTOAsFeatureSettingDTO is a convenience function that returns FeatureTradeGuardrailsDTO wrapped in FeatureSettingDTO
func FeatureTradeGuardrailsDTOAsFeatureSettingDTO(v *FeatureTradeGuardrailsDTO) FeatureSettingDTO {
	return FeatureSettingDTO{
		FeatureTradeGuardrailsDTO: v,
	}
}

// FeatureTradingWindowsDTOAsFeatureSettingDTO is a convenience function that returns FeatureTradingWindowsDTO wrapped in FeatureSettingDTO
func FeatureTradingWindowsDTOAsFeatureSettingDTO(v *FeatureTradingWindowsDTO) FeatureSettingDTO {
	return FeatureSettingDTO{
		FeatureTradingWindowsDTO: v,
	}
}

// FeatureTrailingStopDTOAsFeatureSettingDTO is a convenience function that returns FeatureTrailingStopDTO wrapped in FeatureSettingDTO
func FeatureTrailingStopDTOAsFeatureSettingDTO(v *FeatureTrailingStopDTO) FeatureSettingDTO {
	return FeatureSettingDTO{
		FeatureTrailingStopDTO: v,
	}
}

// FeatureWeeklyProfitTargetDTOAsFeatureSettingDTO is a convenience function that returns FeatureWeeklyProfitTargetDTO wrapped in FeatureSettingDTO
func FeatureWeeklyProfitTargetDTOAsFeatureSettingDTO(v *FeatureWeeklyProfitTargetDTO) FeatureSettingDTO {
	return FeatureSettingDTO{
		FeatureWeeklyProfitTargetDTO: v,
	}
}

// FeatureWhiteLabelDTOAsFeatureSettingDTO is a convenience function that returns FeatureWhiteLabelDTO wrapped in FeatureSettingDTO
func FeatureWhiteLabelDTOAsFeatureSettingDTO(v *FeatureWhiteLabelDTO) FeatureSettingDTO {
	return FeatureSettingDTO{
		FeatureWhiteLabelDTO: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *FeatureSettingDTO) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into FeatureApprovalDTO
	err = newStrictDecoder(data).Decode(&dst.FeatureApprovalDTO)
	if err == nil {
		jsonFeatureApprovalDTO, _ := json.Marshal(dst.FeatureApprovalDTO)
		if string(jsonFeatureApprovalDTO) == "{}" { // empty struct
			dst.FeatureApprovalDTO = nil
		} else {
			if err = validator.Validate(dst.FeatureApprovalDTO); err != nil {
				dst.FeatureApprovalDTO = nil
			} else {
				match++
			}
		}
	} else {
		dst.FeatureApprovalDTO = nil
	}

	// try to unmarshal data into FeatureBreakEvenDTO
	err = newStrictDecoder(data).Decode(&dst.FeatureBreakEvenDTO)
	if err == nil {
		jsonFeatureBreakEvenDTO, _ := json.Marshal(dst.FeatureBreakEvenDTO)
		if string(jsonFeatureBreakEvenDTO) == "{}" { // empty struct
			dst.FeatureBreakEvenDTO = nil
		} else {
			if err = validator.Validate(dst.FeatureBreakEvenDTO); err != nil {
				dst.FeatureBreakEvenDTO = nil
			} else {
				match++
			}
		}
	} else {
		dst.FeatureBreakEvenDTO = nil
	}

	// try to unmarshal data into FeatureCopierFilterDTO
	err = newStrictDecoder(data).Decode(&dst.FeatureCopierFilterDTO)
	if err == nil {
		jsonFeatureCopierFilterDTO, _ := json.Marshal(dst.FeatureCopierFilterDTO)
		if string(jsonFeatureCopierFilterDTO) == "{}" { // empty struct
			dst.FeatureCopierFilterDTO = nil
		} else {
			if err = validator.Validate(dst.FeatureCopierFilterDTO); err != nil {
				dst.FeatureCopierFilterDTO = nil
			} else {
				match++
			}
		}
	} else {
		dst.FeatureCopierFilterDTO = nil
	}

	// try to unmarshal data into FeatureDailyProfitTargetDTO
	err = newStrictDecoder(data).Decode(&dst.FeatureDailyProfitTargetDTO)
	if err == nil {
		jsonFeatureDailyProfitTargetDTO, _ := json.Marshal(dst.FeatureDailyProfitTargetDTO)
		if string(jsonFeatureDailyProfitTargetDTO) == "{}" { // empty struct
			dst.FeatureDailyProfitTargetDTO = nil
		} else {
			if err = validator.Validate(dst.FeatureDailyProfitTargetDTO); err != nil {
				dst.FeatureDailyProfitTargetDTO = nil
			} else {
				match++
			}
		}
	} else {
		dst.FeatureDailyProfitTargetDTO = nil
	}

	// try to unmarshal data into FeatureDataCollectorDTO
	err = newStrictDecoder(data).Decode(&dst.FeatureDataCollectorDTO)
	if err == nil {
		jsonFeatureDataCollectorDTO, _ := json.Marshal(dst.FeatureDataCollectorDTO)
		if string(jsonFeatureDataCollectorDTO) == "{}" { // empty struct
			dst.FeatureDataCollectorDTO = nil
		} else {
			if err = validator.Validate(dst.FeatureDataCollectorDTO); err != nil {
				dst.FeatureDataCollectorDTO = nil
			} else {
				match++
			}
		}
	} else {
		dst.FeatureDataCollectorDTO = nil
	}

	// try to unmarshal data into FeatureDedicatedIpDTO
	err = newStrictDecoder(data).Decode(&dst.FeatureDedicatedIpDTO)
	if err == nil {
		jsonFeatureDedicatedIpDTO, _ := json.Marshal(dst.FeatureDedicatedIpDTO)
		if string(jsonFeatureDedicatedIpDTO) == "{}" { // empty struct
			dst.FeatureDedicatedIpDTO = nil
		} else {
			if err = validator.Validate(dst.FeatureDedicatedIpDTO); err != nil {
				dst.FeatureDedicatedIpDTO = nil
			} else {
				match++
			}
		}
	} else {
		dst.FeatureDedicatedIpDTO = nil
	}

	// try to unmarshal data into FeatureDedicatedIpPoolDTO
	err = newStrictDecoder(data).Decode(&dst.FeatureDedicatedIpPoolDTO)
	if err == nil {
		jsonFeatureDedicatedIpPoolDTO, _ := json.Marshal(dst.FeatureDedicatedIpPoolDTO)
		if string(jsonFeatureDedicatedIpPoolDTO) == "{}" { // empty struct
			dst.FeatureDedicatedIpPoolDTO = nil
		} else {
			if err = validator.Validate(dst.FeatureDedicatedIpPoolDTO); err != nil {
				dst.FeatureDedicatedIpPoolDTO = nil
			} else {
				match++
			}
		}
	} else {
		dst.FeatureDedicatedIpPoolDTO = nil
	}

	// try to unmarshal data into FeatureDelayedExecutionDTO
	err = newStrictDecoder(data).Decode(&dst.FeatureDelayedExecutionDTO)
	if err == nil {
		jsonFeatureDelayedExecutionDTO, _ := json.Marshal(dst.FeatureDelayedExecutionDTO)
		if string(jsonFeatureDelayedExecutionDTO) == "{}" { // empty struct
			dst.FeatureDelayedExecutionDTO = nil
		} else {
			if err = validator.Validate(dst.FeatureDelayedExecutionDTO); err != nil {
				dst.FeatureDelayedExecutionDTO = nil
			} else {
				match++
			}
		}
	} else {
		dst.FeatureDelayedExecutionDTO = nil
	}

	// try to unmarshal data into FeatureExitSignalOverrideDTO
	err = newStrictDecoder(data).Decode(&dst.FeatureExitSignalOverrideDTO)
	if err == nil {
		jsonFeatureExitSignalOverrideDTO, _ := json.Marshal(dst.FeatureExitSignalOverrideDTO)
		if string(jsonFeatureExitSignalOverrideDTO) == "{}" { // empty struct
			dst.FeatureExitSignalOverrideDTO = nil
		} else {
			if err = validator.Validate(dst.FeatureExitSignalOverrideDTO); err != nil {
				dst.FeatureExitSignalOverrideDTO = nil
			} else {
				match++
			}
		}
	} else {
		dst.FeatureExitSignalOverrideDTO = nil
	}

	// try to unmarshal data into FeatureFallbackSettingDTO
	err = newStrictDecoder(data).Decode(&dst.FeatureFallbackSettingDTO)
	if err == nil {
		jsonFeatureFallbackSettingDTO, _ := json.Marshal(dst.FeatureFallbackSettingDTO)
		if string(jsonFeatureFallbackSettingDTO) == "{}" { // empty struct
			dst.FeatureFallbackSettingDTO = nil
		} else {
			if err = validator.Validate(dst.FeatureFallbackSettingDTO); err != nil {
				dst.FeatureFallbackSettingDTO = nil
			} else {
				match++
			}
		}
	} else {
		dst.FeatureFallbackSettingDTO = nil
	}

	// try to unmarshal data into FeatureHftModeDTO
	err = newStrictDecoder(data).Decode(&dst.FeatureHftModeDTO)
	if err == nil {
		jsonFeatureHftModeDTO, _ := json.Marshal(dst.FeatureHftModeDTO)
		if string(jsonFeatureHftModeDTO) == "{}" { // empty struct
			dst.FeatureHftModeDTO = nil
		} else {
			if err = validator.Validate(dst.FeatureHftModeDTO); err != nil {
				dst.FeatureHftModeDTO = nil
			} else {
				match++
			}
		}
	} else {
		dst.FeatureHftModeDTO = nil
	}

	// try to unmarshal data into FeatureKeepAliveTradeDTO
	err = newStrictDecoder(data).Decode(&dst.FeatureKeepAliveTradeDTO)
	if err == nil {
		jsonFeatureKeepAliveTradeDTO, _ := json.Marshal(dst.FeatureKeepAliveTradeDTO)
		if string(jsonFeatureKeepAliveTradeDTO) == "{}" { // empty struct
			dst.FeatureKeepAliveTradeDTO = nil
		} else {
			if err = validator.Validate(dst.FeatureKeepAliveTradeDTO); err != nil {
				dst.FeatureKeepAliveTradeDTO = nil
			} else {
				match++
			}
		}
	} else {
		dst.FeatureKeepAliveTradeDTO = nil
	}

	// try to unmarshal data into FeatureLiveDelayDTO
	err = newStrictDecoder(data).Decode(&dst.FeatureLiveDelayDTO)
	if err == nil {
		jsonFeatureLiveDelayDTO, _ := json.Marshal(dst.FeatureLiveDelayDTO)
		if string(jsonFeatureLiveDelayDTO) == "{}" { // empty struct
			dst.FeatureLiveDelayDTO = nil
		} else {
			if err = validator.Validate(dst.FeatureLiveDelayDTO); err != nil {
				dst.FeatureLiveDelayDTO = nil
			} else {
				match++
			}
		}
	} else {
		dst.FeatureLiveDelayDTO = nil
	}

	// try to unmarshal data into FeatureMaintenanceWindowDTO
	err = newStrictDecoder(data).Decode(&dst.FeatureMaintenanceWindowDTO)
	if err == nil {
		jsonFeatureMaintenanceWindowDTO, _ := json.Marshal(dst.FeatureMaintenanceWindowDTO)
		if string(jsonFeatureMaintenanceWindowDTO) == "{}" { // empty struct
			dst.FeatureMaintenanceWindowDTO = nil
		} else {
			if err = validator.Validate(dst.FeatureMaintenanceWindowDTO); err != nil {
				dst.FeatureMaintenanceWindowDTO = nil
			} else {
				match++
			}
		}
	} else {
		dst.FeatureMaintenanceWindowDTO = nil
	}

	// try to unmarshal data into FeatureMasanielloDTO
	err = newStrictDecoder(data).Decode(&dst.FeatureMasanielloDTO)
	if err == nil {
		jsonFeatureMasanielloDTO, _ := json.Marshal(dst.FeatureMasanielloDTO)
		if string(jsonFeatureMasanielloDTO) == "{}" { // empty struct
			dst.FeatureMasanielloDTO = nil
		} else {
			if err = validator.Validate(dst.FeatureMasanielloDTO); err != nil {
				dst.FeatureMasanielloDTO = nil
			} else {
				match++
			}
		}
	} else {
		dst.FeatureMasanielloDTO = nil
	}

	// try to unmarshal data into FeatureMaxLotSizeDTO
	err = newStrictDecoder(data).Decode(&dst.FeatureMaxLotSizeDTO)
	if err == nil {
		jsonFeatureMaxLotSizeDTO, _ := json.Marshal(dst.FeatureMaxLotSizeDTO)
		if string(jsonFeatureMaxLotSizeDTO) == "{}" { // empty struct
			dst.FeatureMaxLotSizeDTO = nil
		} else {
			if err = validator.Validate(dst.FeatureMaxLotSizeDTO); err != nil {
				dst.FeatureMaxLotSizeDTO = nil
			} else {
				match++
			}
		}
	} else {
		dst.FeatureMaxLotSizeDTO = nil
	}

	// try to unmarshal data into FeatureMaxOpenPositionsDTO
	err = newStrictDecoder(data).Decode(&dst.FeatureMaxOpenPositionsDTO)
	if err == nil {
		jsonFeatureMaxOpenPositionsDTO, _ := json.Marshal(dst.FeatureMaxOpenPositionsDTO)
		if string(jsonFeatureMaxOpenPositionsDTO) == "{}" { // empty struct
			dst.FeatureMaxOpenPositionsDTO = nil
		} else {
			if err = validator.Validate(dst.FeatureMaxOpenPositionsDTO); err != nil {
				dst.FeatureMaxOpenPositionsDTO = nil
			} else {
				match++
			}
		}
	} else {
		dst.FeatureMaxOpenPositionsDTO = nil
	}

	// try to unmarshal data into FeatureMaximumLotDTO
	err = newStrictDecoder(data).Decode(&dst.FeatureMaximumLotDTO)
	if err == nil {
		jsonFeatureMaximumLotDTO, _ := json.Marshal(dst.FeatureMaximumLotDTO)
		if string(jsonFeatureMaximumLotDTO) == "{}" { // empty struct
			dst.FeatureMaximumLotDTO = nil
		} else {
			if err = validator.Validate(dst.FeatureMaximumLotDTO); err != nil {
				dst.FeatureMaximumLotDTO = nil
			} else {
				match++
			}
		}
	} else {
		dst.FeatureMaximumLotDTO = nil
	}

	// try to unmarshal data into FeatureMinimumHoldingTimeDTO
	err = newStrictDecoder(data).Decode(&dst.FeatureMinimumHoldingTimeDTO)
	if err == nil {
		jsonFeatureMinimumHoldingTimeDTO, _ := json.Marshal(dst.FeatureMinimumHoldingTimeDTO)
		if string(jsonFeatureMinimumHoldingTimeDTO) == "{}" { // empty struct
			dst.FeatureMinimumHoldingTimeDTO = nil
		} else {
			if err = validator.Validate(dst.FeatureMinimumHoldingTimeDTO); err != nil {
				dst.FeatureMinimumHoldingTimeDTO = nil
			} else {
				match++
			}
		}
	} else {
		dst.FeatureMinimumHoldingTimeDTO = nil
	}

	// try to unmarshal data into FeatureMonthlyProfitTargetDTO
	err = newStrictDecoder(data).Decode(&dst.FeatureMonthlyProfitTargetDTO)
	if err == nil {
		jsonFeatureMonthlyProfitTargetDTO, _ := json.Marshal(dst.FeatureMonthlyProfitTargetDTO)
		if string(jsonFeatureMonthlyProfitTargetDTO) == "{}" { // empty struct
			dst.FeatureMonthlyProfitTargetDTO = nil
		} else {
			if err = validator.Validate(dst.FeatureMonthlyProfitTargetDTO); err != nil {
				dst.FeatureMonthlyProfitTargetDTO = nil
			} else {
				match++
			}
		}
	} else {
		dst.FeatureMonthlyProfitTargetDTO = nil
	}

	// try to unmarshal data into FeatureMultiplierDTO
	err = newStrictDecoder(data).Decode(&dst.FeatureMultiplierDTO)
	if err == nil {
		jsonFeatureMultiplierDTO, _ := json.Marshal(dst.FeatureMultiplierDTO)
		if string(jsonFeatureMultiplierDTO) == "{}" { // empty struct
			dst.FeatureMultiplierDTO = nil
		} else {
			if err = validator.Validate(dst.FeatureMultiplierDTO); err != nil {
				dst.FeatureMultiplierDTO = nil
			} else {
				match++
			}
		}
	} else {
		dst.FeatureMultiplierDTO = nil
	}

	// try to unmarshal data into FeatureMyHomeIpDTO
	err = newStrictDecoder(data).Decode(&dst.FeatureMyHomeIpDTO)
	if err == nil {
		jsonFeatureMyHomeIpDTO, _ := json.Marshal(dst.FeatureMyHomeIpDTO)
		if string(jsonFeatureMyHomeIpDTO) == "{}" { // empty struct
			dst.FeatureMyHomeIpDTO = nil
		} else {
			if err = validator.Validate(dst.FeatureMyHomeIpDTO); err != nil {
				dst.FeatureMyHomeIpDTO = nil
			} else {
				match++
			}
		}
	} else {
		dst.FeatureMyHomeIpDTO = nil
	}

	// try to unmarshal data into FeatureOrderTypeFilterDTO
	err = newStrictDecoder(data).Decode(&dst.FeatureOrderTypeFilterDTO)
	if err == nil {
		jsonFeatureOrderTypeFilterDTO, _ := json.Marshal(dst.FeatureOrderTypeFilterDTO)
		if string(jsonFeatureOrderTypeFilterDTO) == "{}" { // empty struct
			dst.FeatureOrderTypeFilterDTO = nil
		} else {
			if err = validator.Validate(dst.FeatureOrderTypeFilterDTO); err != nil {
				dst.FeatureOrderTypeFilterDTO = nil
			} else {
				match++
			}
		}
	} else {
		dst.FeatureOrderTypeFilterDTO = nil
	}

	// try to unmarshal data into FeaturePermittedSymbolsDTO
	err = newStrictDecoder(data).Decode(&dst.FeaturePermittedSymbolsDTO)
	if err == nil {
		jsonFeaturePermittedSymbolsDTO, _ := json.Marshal(dst.FeaturePermittedSymbolsDTO)
		if string(jsonFeaturePermittedSymbolsDTO) == "{}" { // empty struct
			dst.FeaturePermittedSymbolsDTO = nil
		} else {
			if err = validator.Validate(dst.FeaturePermittedSymbolsDTO); err != nil {
				dst.FeaturePermittedSymbolsDTO = nil
			} else {
				match++
			}
		}
	} else {
		dst.FeaturePermittedSymbolsDTO = nil
	}

	// try to unmarshal data into FeatureProgressiveTradeSizingDTO
	err = newStrictDecoder(data).Decode(&dst.FeatureProgressiveTradeSizingDTO)
	if err == nil {
		jsonFeatureProgressiveTradeSizingDTO, _ := json.Marshal(dst.FeatureProgressiveTradeSizingDTO)
		if string(jsonFeatureProgressiveTradeSizingDTO) == "{}" { // empty struct
			dst.FeatureProgressiveTradeSizingDTO = nil
		} else {
			if err = validator.Validate(dst.FeatureProgressiveTradeSizingDTO); err != nil {
				dst.FeatureProgressiveTradeSizingDTO = nil
			} else {
				match++
			}
		}
	} else {
		dst.FeatureProgressiveTradeSizingDTO = nil
	}

	// try to unmarshal data into FeatureRiskPerTradeDTO
	err = newStrictDecoder(data).Decode(&dst.FeatureRiskPerTradeDTO)
	if err == nil {
		jsonFeatureRiskPerTradeDTO, _ := json.Marshal(dst.FeatureRiskPerTradeDTO)
		if string(jsonFeatureRiskPerTradeDTO) == "{}" { // empty struct
			dst.FeatureRiskPerTradeDTO = nil
		} else {
			if err = validator.Validate(dst.FeatureRiskPerTradeDTO); err != nil {
				dst.FeatureRiskPerTradeDTO = nil
			} else {
				match++
			}
		}
	} else {
		dst.FeatureRiskPerTradeDTO = nil
	}

	// try to unmarshal data into FeatureSignalFollowerDTO
	err = newStrictDecoder(data).Decode(&dst.FeatureSignalFollowerDTO)
	if err == nil {
		jsonFeatureSignalFollowerDTO, _ := json.Marshal(dst.FeatureSignalFollowerDTO)
		if string(jsonFeatureSignalFollowerDTO) == "{}" { // empty struct
			dst.FeatureSignalFollowerDTO = nil
		} else {
			if err = validator.Validate(dst.FeatureSignalFollowerDTO); err != nil {
				dst.FeatureSignalFollowerDTO = nil
			} else {
				match++
			}
		}
	} else {
		dst.FeatureSignalFollowerDTO = nil
	}

	// try to unmarshal data into FeatureSignalProviderDTO
	err = newStrictDecoder(data).Decode(&dst.FeatureSignalProviderDTO)
	if err == nil {
		jsonFeatureSignalProviderDTO, _ := json.Marshal(dst.FeatureSignalProviderDTO)
		if string(jsonFeatureSignalProviderDTO) == "{}" { // empty struct
			dst.FeatureSignalProviderDTO = nil
		} else {
			if err = validator.Validate(dst.FeatureSignalProviderDTO); err != nil {
				dst.FeatureSignalProviderDTO = nil
			} else {
				match++
			}
		}
	} else {
		dst.FeatureSignalProviderDTO = nil
	}

	// try to unmarshal data into FeatureSkipPositionDTO
	err = newStrictDecoder(data).Decode(&dst.FeatureSkipPositionDTO)
	if err == nil {
		jsonFeatureSkipPositionDTO, _ := json.Marshal(dst.FeatureSkipPositionDTO)
		if string(jsonFeatureSkipPositionDTO) == "{}" { // empty struct
			dst.FeatureSkipPositionDTO = nil
		} else {
			if err = validator.Validate(dst.FeatureSkipPositionDTO); err != nil {
				dst.FeatureSkipPositionDTO = nil
			} else {
				match++
			}
		}
	} else {
		dst.FeatureSkipPositionDTO = nil
	}

	// try to unmarshal data into FeatureSocketDTO
	err = newStrictDecoder(data).Decode(&dst.FeatureSocketDTO)
	if err == nil {
		jsonFeatureSocketDTO, _ := json.Marshal(dst.FeatureSocketDTO)
		if string(jsonFeatureSocketDTO) == "{}" { // empty struct
			dst.FeatureSocketDTO = nil
		} else {
			if err = validator.Validate(dst.FeatureSocketDTO); err != nil {
				dst.FeatureSocketDTO = nil
			} else {
				match++
			}
		}
	} else {
		dst.FeatureSocketDTO = nil
	}

	// try to unmarshal data into FeatureTelegramNotificationDTO
	err = newStrictDecoder(data).Decode(&dst.FeatureTelegramNotificationDTO)
	if err == nil {
		jsonFeatureTelegramNotificationDTO, _ := json.Marshal(dst.FeatureTelegramNotificationDTO)
		if string(jsonFeatureTelegramNotificationDTO) == "{}" { // empty struct
			dst.FeatureTelegramNotificationDTO = nil
		} else {
			if err = validator.Validate(dst.FeatureTelegramNotificationDTO); err != nil {
				dst.FeatureTelegramNotificationDTO = nil
			} else {
				match++
			}
		}
	} else {
		dst.FeatureTelegramNotificationDTO = nil
	}

	// try to unmarshal data into FeatureTpSlManagementDTO
	err = newStrictDecoder(data).Decode(&dst.FeatureTpSlManagementDTO)
	if err == nil {
		jsonFeatureTpSlManagementDTO, _ := json.Marshal(dst.FeatureTpSlManagementDTO)
		if string(jsonFeatureTpSlManagementDTO) == "{}" { // empty struct
			dst.FeatureTpSlManagementDTO = nil
		} else {
			if err = validator.Validate(dst.FeatureTpSlManagementDTO); err != nil {
				dst.FeatureTpSlManagementDTO = nil
			} else {
				match++
			}
		}
	} else {
		dst.FeatureTpSlManagementDTO = nil
	}

	// try to unmarshal data into FeatureTradeGuardrailsDTO
	err = newStrictDecoder(data).Decode(&dst.FeatureTradeGuardrailsDTO)
	if err == nil {
		jsonFeatureTradeGuardrailsDTO, _ := json.Marshal(dst.FeatureTradeGuardrailsDTO)
		if string(jsonFeatureTradeGuardrailsDTO) == "{}" { // empty struct
			dst.FeatureTradeGuardrailsDTO = nil
		} else {
			if err = validator.Validate(dst.FeatureTradeGuardrailsDTO); err != nil {
				dst.FeatureTradeGuardrailsDTO = nil
			} else {
				match++
			}
		}
	} else {
		dst.FeatureTradeGuardrailsDTO = nil
	}

	// try to unmarshal data into FeatureTradingWindowsDTO
	err = newStrictDecoder(data).Decode(&dst.FeatureTradingWindowsDTO)
	if err == nil {
		jsonFeatureTradingWindowsDTO, _ := json.Marshal(dst.FeatureTradingWindowsDTO)
		if string(jsonFeatureTradingWindowsDTO) == "{}" { // empty struct
			dst.FeatureTradingWindowsDTO = nil
		} else {
			if err = validator.Validate(dst.FeatureTradingWindowsDTO); err != nil {
				dst.FeatureTradingWindowsDTO = nil
			} else {
				match++
			}
		}
	} else {
		dst.FeatureTradingWindowsDTO = nil
	}

	// try to unmarshal data into FeatureTrailingStopDTO
	err = newStrictDecoder(data).Decode(&dst.FeatureTrailingStopDTO)
	if err == nil {
		jsonFeatureTrailingStopDTO, _ := json.Marshal(dst.FeatureTrailingStopDTO)
		if string(jsonFeatureTrailingStopDTO) == "{}" { // empty struct
			dst.FeatureTrailingStopDTO = nil
		} else {
			if err = validator.Validate(dst.FeatureTrailingStopDTO); err != nil {
				dst.FeatureTrailingStopDTO = nil
			} else {
				match++
			}
		}
	} else {
		dst.FeatureTrailingStopDTO = nil
	}

	// try to unmarshal data into FeatureWeeklyProfitTargetDTO
	err = newStrictDecoder(data).Decode(&dst.FeatureWeeklyProfitTargetDTO)
	if err == nil {
		jsonFeatureWeeklyProfitTargetDTO, _ := json.Marshal(dst.FeatureWeeklyProfitTargetDTO)
		if string(jsonFeatureWeeklyProfitTargetDTO) == "{}" { // empty struct
			dst.FeatureWeeklyProfitTargetDTO = nil
		} else {
			if err = validator.Validate(dst.FeatureWeeklyProfitTargetDTO); err != nil {
				dst.FeatureWeeklyProfitTargetDTO = nil
			} else {
				match++
			}
		}
	} else {
		dst.FeatureWeeklyProfitTargetDTO = nil
	}

	// try to unmarshal data into FeatureWhiteLabelDTO
	err = newStrictDecoder(data).Decode(&dst.FeatureWhiteLabelDTO)
	if err == nil {
		jsonFeatureWhiteLabelDTO, _ := json.Marshal(dst.FeatureWhiteLabelDTO)
		if string(jsonFeatureWhiteLabelDTO) == "{}" { // empty struct
			dst.FeatureWhiteLabelDTO = nil
		} else {
			if err = validator.Validate(dst.FeatureWhiteLabelDTO); err != nil {
				dst.FeatureWhiteLabelDTO = nil
			} else {
				match++
			}
		}
	} else {
		dst.FeatureWhiteLabelDTO = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.FeatureApprovalDTO = nil
		dst.FeatureBreakEvenDTO = nil
		dst.FeatureCopierFilterDTO = nil
		dst.FeatureDailyProfitTargetDTO = nil
		dst.FeatureDataCollectorDTO = nil
		dst.FeatureDedicatedIpDTO = nil
		dst.FeatureDedicatedIpPoolDTO = nil
		dst.FeatureDelayedExecutionDTO = nil
		dst.FeatureExitSignalOverrideDTO = nil
		dst.FeatureFallbackSettingDTO = nil
		dst.FeatureHftModeDTO = nil
		dst.FeatureKeepAliveTradeDTO = nil
		dst.FeatureLiveDelayDTO = nil
		dst.FeatureMaintenanceWindowDTO = nil
		dst.FeatureMasanielloDTO = nil
		dst.FeatureMaxLotSizeDTO = nil
		dst.FeatureMaxOpenPositionsDTO = nil
		dst.FeatureMaximumLotDTO = nil
		dst.FeatureMinimumHoldingTimeDTO = nil
		dst.FeatureMonthlyProfitTargetDTO = nil
		dst.FeatureMultiplierDTO = nil
		dst.FeatureMyHomeIpDTO = nil
		dst.FeatureOrderTypeFilterDTO = nil
		dst.FeaturePermittedSymbolsDTO = nil
		dst.FeatureProgressiveTradeSizingDTO = nil
		dst.FeatureRiskPerTradeDTO = nil
		dst.FeatureSignalFollowerDTO = nil
		dst.FeatureSignalProviderDTO = nil
		dst.FeatureSkipPositionDTO = nil
		dst.FeatureSocketDTO = nil
		dst.FeatureTelegramNotificationDTO = nil
		dst.FeatureTpSlManagementDTO = nil
		dst.FeatureTradeGuardrailsDTO = nil
		dst.FeatureTradingWindowsDTO = nil
		dst.FeatureTrailingStopDTO = nil
		dst.FeatureWeeklyProfitTargetDTO = nil
		dst.FeatureWhiteLabelDTO = nil

		return fmt.Errorf("data matches more than one schema in oneOf(FeatureSettingDTO)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(FeatureSettingDTO)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src FeatureSettingDTO) MarshalJSON() ([]byte, error) {
	if src.FeatureApprovalDTO != nil {
		return json.Marshal(&src.FeatureApprovalDTO)
	}

	if src.FeatureBreakEvenDTO != nil {
		return json.Marshal(&src.FeatureBreakEvenDTO)
	}

	if src.FeatureCopierFilterDTO != nil {
		return json.Marshal(&src.FeatureCopierFilterDTO)
	}

	if src.FeatureDailyProfitTargetDTO != nil {
		return json.Marshal(&src.FeatureDailyProfitTargetDTO)
	}

	if src.FeatureDataCollectorDTO != nil {
		return json.Marshal(&src.FeatureDataCollectorDTO)
	}

	if src.FeatureDedicatedIpDTO != nil {
		return json.Marshal(&src.FeatureDedicatedIpDTO)
	}

	if src.FeatureDedicatedIpPoolDTO != nil {
		return json.Marshal(&src.FeatureDedicatedIpPoolDTO)
	}

	if src.FeatureDelayedExecutionDTO != nil {
		return json.Marshal(&src.FeatureDelayedExecutionDTO)
	}

	if src.FeatureExitSignalOverrideDTO != nil {
		return json.Marshal(&src.FeatureExitSignalOverrideDTO)
	}

	if src.FeatureFallbackSettingDTO != nil {
		return json.Marshal(&src.FeatureFallbackSettingDTO)
	}

	if src.FeatureHftModeDTO != nil {
		return json.Marshal(&src.FeatureHftModeDTO)
	}

	if src.FeatureKeepAliveTradeDTO != nil {
		return json.Marshal(&src.FeatureKeepAliveTradeDTO)
	}

	if src.FeatureLiveDelayDTO != nil {
		return json.Marshal(&src.FeatureLiveDelayDTO)
	}

	if src.FeatureMaintenanceWindowDTO != nil {
		return json.Marshal(&src.FeatureMaintenanceWindowDTO)
	}

	if src.FeatureMasanielloDTO != nil {
		return json.Marshal(&src.FeatureMasanielloDTO)
	}

	if src.FeatureMaxLotSizeDTO != nil {
		return json.Marshal(&src.FeatureMaxLotSizeDTO)
	}

	if src.FeatureMaxOpenPositionsDTO != nil {
		return json.Marshal(&src.FeatureMaxOpenPositionsDTO)
	}

	if src.FeatureMaximumLotDTO != nil {
		return json.Marshal(&src.FeatureMaximumLotDTO)
	}

	if src.FeatureMinimumHoldingTimeDTO != nil {
		return json.Marshal(&src.FeatureMinimumHoldingTimeDTO)
	}

	if src.FeatureMonthlyProfitTargetDTO != nil {
		return json.Marshal(&src.FeatureMonthlyProfitTargetDTO)
	}

	if src.FeatureMultiplierDTO != nil {
		return json.Marshal(&src.FeatureMultiplierDTO)
	}

	if src.FeatureMyHomeIpDTO != nil {
		return json.Marshal(&src.FeatureMyHomeIpDTO)
	}

	if src.FeatureOrderTypeFilterDTO != nil {
		return json.Marshal(&src.FeatureOrderTypeFilterDTO)
	}

	if src.FeaturePermittedSymbolsDTO != nil {
		return json.Marshal(&src.FeaturePermittedSymbolsDTO)
	}

	if src.FeatureProgressiveTradeSizingDTO != nil {
		return json.Marshal(&src.FeatureProgressiveTradeSizingDTO)
	}

	if src.FeatureRiskPerTradeDTO != nil {
		return json.Marshal(&src.FeatureRiskPerTradeDTO)
	}

	if src.FeatureSignalFollowerDTO != nil {
		return json.Marshal(&src.FeatureSignalFollowerDTO)
	}

	if src.FeatureSignalProviderDTO != nil {
		return json.Marshal(&src.FeatureSignalProviderDTO)
	}

	if src.FeatureSkipPositionDTO != nil {
		return json.Marshal(&src.FeatureSkipPositionDTO)
	}

	if src.FeatureSocketDTO != nil {
		return json.Marshal(&src.FeatureSocketDTO)
	}

	if src.FeatureTelegramNotificationDTO != nil {
		return json.Marshal(&src.FeatureTelegramNotificationDTO)
	}

	if src.FeatureTpSlManagementDTO != nil {
		return json.Marshal(&src.FeatureTpSlManagementDTO)
	}

	if src.FeatureTradeGuardrailsDTO != nil {
		return json.Marshal(&src.FeatureTradeGuardrailsDTO)
	}

	if src.FeatureTradingWindowsDTO != nil {
		return json.Marshal(&src.FeatureTradingWindowsDTO)
	}

	if src.FeatureTrailingStopDTO != nil {
		return json.Marshal(&src.FeatureTrailingStopDTO)
	}

	if src.FeatureWeeklyProfitTargetDTO != nil {
		return json.Marshal(&src.FeatureWeeklyProfitTargetDTO)
	}

	if src.FeatureWhiteLabelDTO != nil {
		return json.Marshal(&src.FeatureWhiteLabelDTO)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *FeatureSettingDTO) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.FeatureApprovalDTO != nil {
		return obj.FeatureApprovalDTO
	}

	if obj.FeatureBreakEvenDTO != nil {
		return obj.FeatureBreakEvenDTO
	}

	if obj.FeatureCopierFilterDTO != nil {
		return obj.FeatureCopierFilterDTO
	}

	if obj.FeatureDailyProfitTargetDTO != nil {
		return obj.FeatureDailyProfitTargetDTO
	}

	if obj.FeatureDataCollectorDTO != nil {
		return obj.FeatureDataCollectorDTO
	}

	if obj.FeatureDedicatedIpDTO != nil {
		return obj.FeatureDedicatedIpDTO
	}

	if obj.FeatureDedicatedIpPoolDTO != nil {
		return obj.FeatureDedicatedIpPoolDTO
	}

	if obj.FeatureDelayedExecutionDTO != nil {
		return obj.FeatureDelayedExecutionDTO
	}

	if obj.FeatureExitSignalOverrideDTO != nil {
		return obj.FeatureExitSignalOverrideDTO
	}

	if obj.FeatureFallbackSettingDTO != nil {
		return obj.FeatureFallbackSettingDTO
	}

	if obj.FeatureHftModeDTO != nil {
		return obj.FeatureHftModeDTO
	}

	if obj.FeatureKeepAliveTradeDTO != nil {
		return obj.FeatureKeepAliveTradeDTO
	}

	if obj.FeatureLiveDelayDTO != nil {
		return obj.FeatureLiveDelayDTO
	}

	if obj.FeatureMaintenanceWindowDTO != nil {
		return obj.FeatureMaintenanceWindowDTO
	}

	if obj.FeatureMasanielloDTO != nil {
		return obj.FeatureMasanielloDTO
	}

	if obj.FeatureMaxLotSizeDTO != nil {
		return obj.FeatureMaxLotSizeDTO
	}

	if obj.FeatureMaxOpenPositionsDTO != nil {
		return obj.FeatureMaxOpenPositionsDTO
	}

	if obj.FeatureMaximumLotDTO != nil {
		return obj.FeatureMaximumLotDTO
	}

	if obj.FeatureMinimumHoldingTimeDTO != nil {
		return obj.FeatureMinimumHoldingTimeDTO
	}

	if obj.FeatureMonthlyProfitTargetDTO != nil {
		return obj.FeatureMonthlyProfitTargetDTO
	}

	if obj.FeatureMultiplierDTO != nil {
		return obj.FeatureMultiplierDTO
	}

	if obj.FeatureMyHomeIpDTO != nil {
		return obj.FeatureMyHomeIpDTO
	}

	if obj.FeatureOrderTypeFilterDTO != nil {
		return obj.FeatureOrderTypeFilterDTO
	}

	if obj.FeaturePermittedSymbolsDTO != nil {
		return obj.FeaturePermittedSymbolsDTO
	}

	if obj.FeatureProgressiveTradeSizingDTO != nil {
		return obj.FeatureProgressiveTradeSizingDTO
	}

	if obj.FeatureRiskPerTradeDTO != nil {
		return obj.FeatureRiskPerTradeDTO
	}

	if obj.FeatureSignalFollowerDTO != nil {
		return obj.FeatureSignalFollowerDTO
	}

	if obj.FeatureSignalProviderDTO != nil {
		return obj.FeatureSignalProviderDTO
	}

	if obj.FeatureSkipPositionDTO != nil {
		return obj.FeatureSkipPositionDTO
	}

	if obj.FeatureSocketDTO != nil {
		return obj.FeatureSocketDTO
	}

	if obj.FeatureTelegramNotificationDTO != nil {
		return obj.FeatureTelegramNotificationDTO
	}

	if obj.FeatureTpSlManagementDTO != nil {
		return obj.FeatureTpSlManagementDTO
	}

	if obj.FeatureTradeGuardrailsDTO != nil {
		return obj.FeatureTradeGuardrailsDTO
	}

	if obj.FeatureTradingWindowsDTO != nil {
		return obj.FeatureTradingWindowsDTO
	}

	if obj.FeatureTrailingStopDTO != nil {
		return obj.FeatureTrailingStopDTO
	}

	if obj.FeatureWeeklyProfitTargetDTO != nil {
		return obj.FeatureWeeklyProfitTargetDTO
	}

	if obj.FeatureWhiteLabelDTO != nil {
		return obj.FeatureWhiteLabelDTO
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj FeatureSettingDTO) GetActualInstanceValue() interface{} {
	if obj.FeatureApprovalDTO != nil {
		return *obj.FeatureApprovalDTO
	}

	if obj.FeatureBreakEvenDTO != nil {
		return *obj.FeatureBreakEvenDTO
	}

	if obj.FeatureCopierFilterDTO != nil {
		return *obj.FeatureCopierFilterDTO
	}

	if obj.FeatureDailyProfitTargetDTO != nil {
		return *obj.FeatureDailyProfitTargetDTO
	}

	if obj.FeatureDataCollectorDTO != nil {
		return *obj.FeatureDataCollectorDTO
	}

	if obj.FeatureDedicatedIpDTO != nil {
		return *obj.FeatureDedicatedIpDTO
	}

	if obj.FeatureDedicatedIpPoolDTO != nil {
		return *obj.FeatureDedicatedIpPoolDTO
	}

	if obj.FeatureDelayedExecutionDTO != nil {
		return *obj.FeatureDelayedExecutionDTO
	}

	if obj.FeatureExitSignalOverrideDTO != nil {
		return *obj.FeatureExitSignalOverrideDTO
	}

	if obj.FeatureFallbackSettingDTO != nil {
		return *obj.FeatureFallbackSettingDTO
	}

	if obj.FeatureHftModeDTO != nil {
		return *obj.FeatureHftModeDTO
	}

	if obj.FeatureKeepAliveTradeDTO != nil {
		return *obj.FeatureKeepAliveTradeDTO
	}

	if obj.FeatureLiveDelayDTO != nil {
		return *obj.FeatureLiveDelayDTO
	}

	if obj.FeatureMaintenanceWindowDTO != nil {
		return *obj.FeatureMaintenanceWindowDTO
	}

	if obj.FeatureMasanielloDTO != nil {
		return *obj.FeatureMasanielloDTO
	}

	if obj.FeatureMaxLotSizeDTO != nil {
		return *obj.FeatureMaxLotSizeDTO
	}

	if obj.FeatureMaxOpenPositionsDTO != nil {
		return *obj.FeatureMaxOpenPositionsDTO
	}

	if obj.FeatureMaximumLotDTO != nil {
		return *obj.FeatureMaximumLotDTO
	}

	if obj.FeatureMinimumHoldingTimeDTO != nil {
		return *obj.FeatureMinimumHoldingTimeDTO
	}

	if obj.FeatureMonthlyProfitTargetDTO != nil {
		return *obj.FeatureMonthlyProfitTargetDTO
	}

	if obj.FeatureMultiplierDTO != nil {
		return *obj.FeatureMultiplierDTO
	}

	if obj.FeatureMyHomeIpDTO != nil {
		return *obj.FeatureMyHomeIpDTO
	}

	if obj.FeatureOrderTypeFilterDTO != nil {
		return *obj.FeatureOrderTypeFilterDTO
	}

	if obj.FeaturePermittedSymbolsDTO != nil {
		return *obj.FeaturePermittedSymbolsDTO
	}

	if obj.FeatureProgressiveTradeSizingDTO != nil {
		return *obj.FeatureProgressiveTradeSizingDTO
	}

	if obj.FeatureRiskPerTradeDTO != nil {
		return *obj.FeatureRiskPerTradeDTO
	}

	if obj.FeatureSignalFollowerDTO != nil {
		return *obj.FeatureSignalFollowerDTO
	}

	if obj.FeatureSignalProviderDTO != nil {
		return *obj.FeatureSignalProviderDTO
	}

	if obj.FeatureSkipPositionDTO != nil {
		return *obj.FeatureSkipPositionDTO
	}

	if obj.FeatureSocketDTO != nil {
		return *obj.FeatureSocketDTO
	}

	if obj.FeatureTelegramNotificationDTO != nil {
		return *obj.FeatureTelegramNotificationDTO
	}

	if obj.FeatureTpSlManagementDTO != nil {
		return *obj.FeatureTpSlManagementDTO
	}

	if obj.FeatureTradeGuardrailsDTO != nil {
		return *obj.FeatureTradeGuardrailsDTO
	}

	if obj.FeatureTradingWindowsDTO != nil {
		return *obj.FeatureTradingWindowsDTO
	}

	if obj.FeatureTrailingStopDTO != nil {
		return *obj.FeatureTrailingStopDTO
	}

	if obj.FeatureWeeklyProfitTargetDTO != nil {
		return *obj.FeatureWeeklyProfitTargetDTO
	}

	if obj.FeatureWhiteLabelDTO != nil {
		return *obj.FeatureWhiteLabelDTO
	}

	// all schemas are nil
	return nil
}

type NullableFeatureSettingDTO struct {
	value *FeatureSettingDTO
	isSet bool
}

func (v NullableFeatureSettingDTO) Get() *FeatureSettingDTO {
	return v.value
}

func (v *NullableFeatureSettingDTO) Set(val *FeatureSettingDTO) {
	v.value = val
	v.isSet = true
}

func (v NullableFeatureSettingDTO) IsSet() bool {
	return v.isSet
}

func (v *NullableFeatureSettingDTO) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFeatureSettingDTO(val *FeatureSettingDTO) *NullableFeatureSettingDTO {
	return &NullableFeatureSettingDTO{value: val, isSet: true}
}

func (v NullableFeatureSettingDTO) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFeatureSettingDTO) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
