/*
MetaCopier API

Explore the power of the MetaCopier API! Our RESTful API offers scalable and secure access to accounts, projects, and more. Get started quickly with authentication, explore endpoints, and access code samples in various languages.<br/><br/>All dates are in ISO 8601<br/><br/>This API is not designed for real-time communication purposes. For instance, continuously polling account information such as open positions every second is not recommended.<br/><br/>Our frontend uses this API, so you can look at the requests on our frontend for examples.

API version: 1.2.5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package metacopier

import (
	"encoding/json"
	"time"
)

// checks if the PositionDTO type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PositionDTO{}

// PositionDTO List of historical positions relevant to the account's performance as of the recorded date.
type PositionDTO struct {
	// Original time string from the broker
	BrokerTimeClose *string `json:"brokerTimeClose,omitempty"`
	// Original time string from the broker
	BrokerTimeOpen *string  `json:"brokerTimeOpen,omitempty"`
	ClosePrice     *float32 `json:"closePrice,omitempty"`
	// ISO 8601
	CloseTime   *time.Time `json:"closeTime,omitempty"`
	Comment     *string    `json:"comment,omitempty"`
	Commission  *float32   `json:"commission,omitempty"`
	DealType    *string    `json:"dealType,omitempty"`
	Id          *string    `json:"id,omitempty"`
	MagicNumber *string    `json:"magicNumber,omitempty"`
	NetProfit   *float32   `json:"netProfit,omitempty"`
	OpenPrice   *float32   `json:"openPrice,omitempty"`
	// ISO 8601
	OpenTime   *time.Time `json:"openTime,omitempty"`
	OrderType  *string    `json:"orderType,omitempty"`
	PlacedType *string    `json:"placedType,omitempty"`
	Profit     *float32   `json:"profit,omitempty"`
	RequestId  *string    `json:"requestId,omitempty"`
	State      *string    `json:"state,omitempty"`
	StopLoss   *float32   `json:"stopLoss,omitempty"`
	Swap       *float32   `json:"swap,omitempty"`
	Symbol     *string    `json:"symbol,omitempty"`
	TakeProfit *float32   `json:"takeProfit,omitempty"`
	Volume     *float32   `json:"volume,omitempty"`
}

// NewPositionDTO instantiates a new PositionDTO object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPositionDTO() *PositionDTO {
	this := PositionDTO{}
	return &this
}

// NewPositionDTOWithDefaults instantiates a new PositionDTO object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPositionDTOWithDefaults() *PositionDTO {
	this := PositionDTO{}
	return &this
}

// GetBrokerTimeClose returns the BrokerTimeClose field value if set, zero value otherwise.
func (o *PositionDTO) GetBrokerTimeClose() string {
	if o == nil || IsNil(o.BrokerTimeClose) {
		var ret string
		return ret
	}
	return *o.BrokerTimeClose
}

// GetBrokerTimeCloseOk returns a tuple with the BrokerTimeClose field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PositionDTO) GetBrokerTimeCloseOk() (*string, bool) {
	if o == nil || IsNil(o.BrokerTimeClose) {
		return nil, false
	}
	return o.BrokerTimeClose, true
}

// HasBrokerTimeClose returns a boolean if a field has been set.
func (o *PositionDTO) HasBrokerTimeClose() bool {
	if o != nil && !IsNil(o.BrokerTimeClose) {
		return true
	}

	return false
}

// SetBrokerTimeClose gets a reference to the given string and assigns it to the BrokerTimeClose field.
func (o *PositionDTO) SetBrokerTimeClose(v string) {
	o.BrokerTimeClose = &v
}

// GetBrokerTimeOpen returns the BrokerTimeOpen field value if set, zero value otherwise.
func (o *PositionDTO) GetBrokerTimeOpen() string {
	if o == nil || IsNil(o.BrokerTimeOpen) {
		var ret string
		return ret
	}
	return *o.BrokerTimeOpen
}

// GetBrokerTimeOpenOk returns a tuple with the BrokerTimeOpen field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PositionDTO) GetBrokerTimeOpenOk() (*string, bool) {
	if o == nil || IsNil(o.BrokerTimeOpen) {
		return nil, false
	}
	return o.BrokerTimeOpen, true
}

// HasBrokerTimeOpen returns a boolean if a field has been set.
func (o *PositionDTO) HasBrokerTimeOpen() bool {
	if o != nil && !IsNil(o.BrokerTimeOpen) {
		return true
	}

	return false
}

// SetBrokerTimeOpen gets a reference to the given string and assigns it to the BrokerTimeOpen field.
func (o *PositionDTO) SetBrokerTimeOpen(v string) {
	o.BrokerTimeOpen = &v
}

// GetClosePrice returns the ClosePrice field value if set, zero value otherwise.
func (o *PositionDTO) GetClosePrice() float32 {
	if o == nil || IsNil(o.ClosePrice) {
		var ret float32
		return ret
	}
	return *o.ClosePrice
}

// GetClosePriceOk returns a tuple with the ClosePrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PositionDTO) GetClosePriceOk() (*float32, bool) {
	if o == nil || IsNil(o.ClosePrice) {
		return nil, false
	}
	return o.ClosePrice, true
}

// HasClosePrice returns a boolean if a field has been set.
func (o *PositionDTO) HasClosePrice() bool {
	if o != nil && !IsNil(o.ClosePrice) {
		return true
	}

	return false
}

// SetClosePrice gets a reference to the given float32 and assigns it to the ClosePrice field.
func (o *PositionDTO) SetClosePrice(v float32) {
	o.ClosePrice = &v
}

// GetCloseTime returns the CloseTime field value if set, zero value otherwise.
func (o *PositionDTO) GetCloseTime() time.Time {
	if o == nil || IsNil(o.CloseTime) {
		var ret time.Time
		return ret
	}
	return *o.CloseTime
}

// GetCloseTimeOk returns a tuple with the CloseTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PositionDTO) GetCloseTimeOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CloseTime) {
		return nil, false
	}
	return o.CloseTime, true
}

// HasCloseTime returns a boolean if a field has been set.
func (o *PositionDTO) HasCloseTime() bool {
	if o != nil && !IsNil(o.CloseTime) {
		return true
	}

	return false
}

// SetCloseTime gets a reference to the given time.Time and assigns it to the CloseTime field.
func (o *PositionDTO) SetCloseTime(v time.Time) {
	o.CloseTime = &v
}

// GetComment returns the Comment field value if set, zero value otherwise.
func (o *PositionDTO) GetComment() string {
	if o == nil || IsNil(o.Comment) {
		var ret string
		return ret
	}
	return *o.Comment
}

// GetCommentOk returns a tuple with the Comment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PositionDTO) GetCommentOk() (*string, bool) {
	if o == nil || IsNil(o.Comment) {
		return nil, false
	}
	return o.Comment, true
}

// HasComment returns a boolean if a field has been set.
func (o *PositionDTO) HasComment() bool {
	if o != nil && !IsNil(o.Comment) {
		return true
	}

	return false
}

// SetComment gets a reference to the given string and assigns it to the Comment field.
func (o *PositionDTO) SetComment(v string) {
	o.Comment = &v
}

// GetCommission returns the Commission field value if set, zero value otherwise.
func (o *PositionDTO) GetCommission() float32 {
	if o == nil || IsNil(o.Commission) {
		var ret float32
		return ret
	}
	return *o.Commission
}

// GetCommissionOk returns a tuple with the Commission field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PositionDTO) GetCommissionOk() (*float32, bool) {
	if o == nil || IsNil(o.Commission) {
		return nil, false
	}
	return o.Commission, true
}

// HasCommission returns a boolean if a field has been set.
func (o *PositionDTO) HasCommission() bool {
	if o != nil && !IsNil(o.Commission) {
		return true
	}

	return false
}

// SetCommission gets a reference to the given float32 and assigns it to the Commission field.
func (o *PositionDTO) SetCommission(v float32) {
	o.Commission = &v
}

// GetDealType returns the DealType field value if set, zero value otherwise.
func (o *PositionDTO) GetDealType() string {
	if o == nil || IsNil(o.DealType) {
		var ret string
		return ret
	}
	return *o.DealType
}

// GetDealTypeOk returns a tuple with the DealType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PositionDTO) GetDealTypeOk() (*string, bool) {
	if o == nil || IsNil(o.DealType) {
		return nil, false
	}
	return o.DealType, true
}

// HasDealType returns a boolean if a field has been set.
func (o *PositionDTO) HasDealType() bool {
	if o != nil && !IsNil(o.DealType) {
		return true
	}

	return false
}

// SetDealType gets a reference to the given string and assigns it to the DealType field.
func (o *PositionDTO) SetDealType(v string) {
	o.DealType = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *PositionDTO) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PositionDTO) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *PositionDTO) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *PositionDTO) SetId(v string) {
	o.Id = &v
}

// GetMagicNumber returns the MagicNumber field value if set, zero value otherwise.
func (o *PositionDTO) GetMagicNumber() string {
	if o == nil || IsNil(o.MagicNumber) {
		var ret string
		return ret
	}
	return *o.MagicNumber
}

// GetMagicNumberOk returns a tuple with the MagicNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PositionDTO) GetMagicNumberOk() (*string, bool) {
	if o == nil || IsNil(o.MagicNumber) {
		return nil, false
	}
	return o.MagicNumber, true
}

// HasMagicNumber returns a boolean if a field has been set.
func (o *PositionDTO) HasMagicNumber() bool {
	if o != nil && !IsNil(o.MagicNumber) {
		return true
	}

	return false
}

// SetMagicNumber gets a reference to the given string and assigns it to the MagicNumber field.
func (o *PositionDTO) SetMagicNumber(v string) {
	o.MagicNumber = &v
}

// GetNetProfit returns the NetProfit field value if set, zero value otherwise.
func (o *PositionDTO) GetNetProfit() float32 {
	if o == nil || IsNil(o.NetProfit) {
		var ret float32
		return ret
	}
	return *o.NetProfit
}

// GetNetProfitOk returns a tuple with the NetProfit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PositionDTO) GetNetProfitOk() (*float32, bool) {
	if o == nil || IsNil(o.NetProfit) {
		return nil, false
	}
	return o.NetProfit, true
}

// HasNetProfit returns a boolean if a field has been set.
func (o *PositionDTO) HasNetProfit() bool {
	if o != nil && !IsNil(o.NetProfit) {
		return true
	}

	return false
}

// SetNetProfit gets a reference to the given float32 and assigns it to the NetProfit field.
func (o *PositionDTO) SetNetProfit(v float32) {
	o.NetProfit = &v
}

// GetOpenPrice returns the OpenPrice field value if set, zero value otherwise.
func (o *PositionDTO) GetOpenPrice() float32 {
	if o == nil || IsNil(o.OpenPrice) {
		var ret float32
		return ret
	}
	return *o.OpenPrice
}

// GetOpenPriceOk returns a tuple with the OpenPrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PositionDTO) GetOpenPriceOk() (*float32, bool) {
	if o == nil || IsNil(o.OpenPrice) {
		return nil, false
	}
	return o.OpenPrice, true
}

// HasOpenPrice returns a boolean if a field has been set.
func (o *PositionDTO) HasOpenPrice() bool {
	if o != nil && !IsNil(o.OpenPrice) {
		return true
	}

	return false
}

// SetOpenPrice gets a reference to the given float32 and assigns it to the OpenPrice field.
func (o *PositionDTO) SetOpenPrice(v float32) {
	o.OpenPrice = &v
}

// GetOpenTime returns the OpenTime field value if set, zero value otherwise.
func (o *PositionDTO) GetOpenTime() time.Time {
	if o == nil || IsNil(o.OpenTime) {
		var ret time.Time
		return ret
	}
	return *o.OpenTime
}

// GetOpenTimeOk returns a tuple with the OpenTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PositionDTO) GetOpenTimeOk() (*time.Time, bool) {
	if o == nil || IsNil(o.OpenTime) {
		return nil, false
	}
	return o.OpenTime, true
}

// HasOpenTime returns a boolean if a field has been set.
func (o *PositionDTO) HasOpenTime() bool {
	if o != nil && !IsNil(o.OpenTime) {
		return true
	}

	return false
}

// SetOpenTime gets a reference to the given time.Time and assigns it to the OpenTime field.
func (o *PositionDTO) SetOpenTime(v time.Time) {
	o.OpenTime = &v
}

// GetOrderType returns the OrderType field value if set, zero value otherwise.
func (o *PositionDTO) GetOrderType() string {
	if o == nil || IsNil(o.OrderType) {
		var ret string
		return ret
	}
	return *o.OrderType
}

// GetOrderTypeOk returns a tuple with the OrderType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PositionDTO) GetOrderTypeOk() (*string, bool) {
	if o == nil || IsNil(o.OrderType) {
		return nil, false
	}
	return o.OrderType, true
}

// HasOrderType returns a boolean if a field has been set.
func (o *PositionDTO) HasOrderType() bool {
	if o != nil && !IsNil(o.OrderType) {
		return true
	}

	return false
}

// SetOrderType gets a reference to the given string and assigns it to the OrderType field.
func (o *PositionDTO) SetOrderType(v string) {
	o.OrderType = &v
}

// GetPlacedType returns the PlacedType field value if set, zero value otherwise.
func (o *PositionDTO) GetPlacedType() string {
	if o == nil || IsNil(o.PlacedType) {
		var ret string
		return ret
	}
	return *o.PlacedType
}

// GetPlacedTypeOk returns a tuple with the PlacedType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PositionDTO) GetPlacedTypeOk() (*string, bool) {
	if o == nil || IsNil(o.PlacedType) {
		return nil, false
	}
	return o.PlacedType, true
}

// HasPlacedType returns a boolean if a field has been set.
func (o *PositionDTO) HasPlacedType() bool {
	if o != nil && !IsNil(o.PlacedType) {
		return true
	}

	return false
}

// SetPlacedType gets a reference to the given string and assigns it to the PlacedType field.
func (o *PositionDTO) SetPlacedType(v string) {
	o.PlacedType = &v
}

// GetProfit returns the Profit field value if set, zero value otherwise.
func (o *PositionDTO) GetProfit() float32 {
	if o == nil || IsNil(o.Profit) {
		var ret float32
		return ret
	}
	return *o.Profit
}

// GetProfitOk returns a tuple with the Profit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PositionDTO) GetProfitOk() (*float32, bool) {
	if o == nil || IsNil(o.Profit) {
		return nil, false
	}
	return o.Profit, true
}

// HasProfit returns a boolean if a field has been set.
func (o *PositionDTO) HasProfit() bool {
	if o != nil && !IsNil(o.Profit) {
		return true
	}

	return false
}

// SetProfit gets a reference to the given float32 and assigns it to the Profit field.
func (o *PositionDTO) SetProfit(v float32) {
	o.Profit = &v
}

// GetRequestId returns the RequestId field value if set, zero value otherwise.
func (o *PositionDTO) GetRequestId() string {
	if o == nil || IsNil(o.RequestId) {
		var ret string
		return ret
	}
	return *o.RequestId
}

// GetRequestIdOk returns a tuple with the RequestId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PositionDTO) GetRequestIdOk() (*string, bool) {
	if o == nil || IsNil(o.RequestId) {
		return nil, false
	}
	return o.RequestId, true
}

// HasRequestId returns a boolean if a field has been set.
func (o *PositionDTO) HasRequestId() bool {
	if o != nil && !IsNil(o.RequestId) {
		return true
	}

	return false
}

// SetRequestId gets a reference to the given string and assigns it to the RequestId field.
func (o *PositionDTO) SetRequestId(v string) {
	o.RequestId = &v
}

// GetState returns the State field value if set, zero value otherwise.
func (o *PositionDTO) GetState() string {
	if o == nil || IsNil(o.State) {
		var ret string
		return ret
	}
	return *o.State
}

// GetStateOk returns a tuple with the State field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PositionDTO) GetStateOk() (*string, bool) {
	if o == nil || IsNil(o.State) {
		return nil, false
	}
	return o.State, true
}

// HasState returns a boolean if a field has been set.
func (o *PositionDTO) HasState() bool {
	if o != nil && !IsNil(o.State) {
		return true
	}

	return false
}

// SetState gets a reference to the given string and assigns it to the State field.
func (o *PositionDTO) SetState(v string) {
	o.State = &v
}

// GetStopLoss returns the StopLoss field value if set, zero value otherwise.
func (o *PositionDTO) GetStopLoss() float32 {
	if o == nil || IsNil(o.StopLoss) {
		var ret float32
		return ret
	}
	return *o.StopLoss
}

// GetStopLossOk returns a tuple with the StopLoss field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PositionDTO) GetStopLossOk() (*float32, bool) {
	if o == nil || IsNil(o.StopLoss) {
		return nil, false
	}
	return o.StopLoss, true
}

// HasStopLoss returns a boolean if a field has been set.
func (o *PositionDTO) HasStopLoss() bool {
	if o != nil && !IsNil(o.StopLoss) {
		return true
	}

	return false
}

// SetStopLoss gets a reference to the given float32 and assigns it to the StopLoss field.
func (o *PositionDTO) SetStopLoss(v float32) {
	o.StopLoss = &v
}

// GetSwap returns the Swap field value if set, zero value otherwise.
func (o *PositionDTO) GetSwap() float32 {
	if o == nil || IsNil(o.Swap) {
		var ret float32
		return ret
	}
	return *o.Swap
}

// GetSwapOk returns a tuple with the Swap field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PositionDTO) GetSwapOk() (*float32, bool) {
	if o == nil || IsNil(o.Swap) {
		return nil, false
	}
	return o.Swap, true
}

// HasSwap returns a boolean if a field has been set.
func (o *PositionDTO) HasSwap() bool {
	if o != nil && !IsNil(o.Swap) {
		return true
	}

	return false
}

// SetSwap gets a reference to the given float32 and assigns it to the Swap field.
func (o *PositionDTO) SetSwap(v float32) {
	o.Swap = &v
}

// GetSymbol returns the Symbol field value if set, zero value otherwise.
func (o *PositionDTO) GetSymbol() string {
	if o == nil || IsNil(o.Symbol) {
		var ret string
		return ret
	}
	return *o.Symbol
}

// GetSymbolOk returns a tuple with the Symbol field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PositionDTO) GetSymbolOk() (*string, bool) {
	if o == nil || IsNil(o.Symbol) {
		return nil, false
	}
	return o.Symbol, true
}

// HasSymbol returns a boolean if a field has been set.
func (o *PositionDTO) HasSymbol() bool {
	if o != nil && !IsNil(o.Symbol) {
		return true
	}

	return false
}

// SetSymbol gets a reference to the given string and assigns it to the Symbol field.
func (o *PositionDTO) SetSymbol(v string) {
	o.Symbol = &v
}

// GetTakeProfit returns the TakeProfit field value if set, zero value otherwise.
func (o *PositionDTO) GetTakeProfit() float32 {
	if o == nil || IsNil(o.TakeProfit) {
		var ret float32
		return ret
	}
	return *o.TakeProfit
}

// GetTakeProfitOk returns a tuple with the TakeProfit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PositionDTO) GetTakeProfitOk() (*float32, bool) {
	if o == nil || IsNil(o.TakeProfit) {
		return nil, false
	}
	return o.TakeProfit, true
}

// HasTakeProfit returns a boolean if a field has been set.
func (o *PositionDTO) HasTakeProfit() bool {
	if o != nil && !IsNil(o.TakeProfit) {
		return true
	}

	return false
}

// SetTakeProfit gets a reference to the given float32 and assigns it to the TakeProfit field.
func (o *PositionDTO) SetTakeProfit(v float32) {
	o.TakeProfit = &v
}

// GetVolume returns the Volume field value if set, zero value otherwise.
func (o *PositionDTO) GetVolume() float32 {
	if o == nil || IsNil(o.Volume) {
		var ret float32
		return ret
	}
	return *o.Volume
}

// GetVolumeOk returns a tuple with the Volume field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PositionDTO) GetVolumeOk() (*float32, bool) {
	if o == nil || IsNil(o.Volume) {
		return nil, false
	}
	return o.Volume, true
}

// HasVolume returns a boolean if a field has been set.
func (o *PositionDTO) HasVolume() bool {
	if o != nil && !IsNil(o.Volume) {
		return true
	}

	return false
}

// SetVolume gets a reference to the given float32 and assigns it to the Volume field.
func (o *PositionDTO) SetVolume(v float32) {
	o.Volume = &v
}

func (o PositionDTO) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PositionDTO) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.BrokerTimeClose) {
		toSerialize["brokerTimeClose"] = o.BrokerTimeClose
	}
	if !IsNil(o.BrokerTimeOpen) {
		toSerialize["brokerTimeOpen"] = o.BrokerTimeOpen
	}
	if !IsNil(o.ClosePrice) {
		toSerialize["closePrice"] = o.ClosePrice
	}
	if !IsNil(o.CloseTime) {
		toSerialize["closeTime"] = o.CloseTime
	}
	if !IsNil(o.Comment) {
		toSerialize["comment"] = o.Comment
	}
	if !IsNil(o.Commission) {
		toSerialize["commission"] = o.Commission
	}
	if !IsNil(o.DealType) {
		toSerialize["dealType"] = o.DealType
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.MagicNumber) {
		toSerialize["magicNumber"] = o.MagicNumber
	}
	if !IsNil(o.NetProfit) {
		toSerialize["netProfit"] = o.NetProfit
	}
	if !IsNil(o.OpenPrice) {
		toSerialize["openPrice"] = o.OpenPrice
	}
	if !IsNil(o.OpenTime) {
		toSerialize["openTime"] = o.OpenTime
	}
	if !IsNil(o.OrderType) {
		toSerialize["orderType"] = o.OrderType
	}
	if !IsNil(o.PlacedType) {
		toSerialize["placedType"] = o.PlacedType
	}
	if !IsNil(o.Profit) {
		toSerialize["profit"] = o.Profit
	}
	if !IsNil(o.RequestId) {
		toSerialize["requestId"] = o.RequestId
	}
	if !IsNil(o.State) {
		toSerialize["state"] = o.State
	}
	if !IsNil(o.StopLoss) {
		toSerialize["stopLoss"] = o.StopLoss
	}
	if !IsNil(o.Swap) {
		toSerialize["swap"] = o.Swap
	}
	if !IsNil(o.Symbol) {
		toSerialize["symbol"] = o.Symbol
	}
	if !IsNil(o.TakeProfit) {
		toSerialize["takeProfit"] = o.TakeProfit
	}
	if !IsNil(o.Volume) {
		toSerialize["volume"] = o.Volume
	}
	return toSerialize, nil
}

type NullablePositionDTO struct {
	value *PositionDTO
	isSet bool
}

func (v NullablePositionDTO) Get() *PositionDTO {
	return v.value
}

func (v *NullablePositionDTO) Set(val *PositionDTO) {
	v.value = val
	v.isSet = true
}

func (v NullablePositionDTO) IsSet() bool {
	return v.isSet
}

func (v *NullablePositionDTO) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePositionDTO(val *PositionDTO) *NullablePositionDTO {
	return &NullablePositionDTO{value: val, isSet: true}
}

func (v NullablePositionDTO) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePositionDTO) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
