/*
MetaCopier API

Explore the power of the MetaCopier API! Our RESTful API offers scalable and secure access to accounts, projects, and more. Get started quickly with authentication, explore endpoints, and access code samples in various languages.<br/><br/>All dates are in ISO 8601<br/><br/>This API is not designed for real-time communication purposes. For instance, continuously polling account information such as open positions every second is not recommended.<br/><br/>Our frontend uses this API, so you can look at the requests on our frontend for examples.

API version: 1.2.5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package metacopier

import (
	"encoding/json"
)

// checks if the FeatureProgressiveTradeSizingDTO type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FeatureProgressiveTradeSizingDTO{}

// FeatureProgressiveTradeSizingDTO DTO for progressive trade sizing feature (copier) (PRO)
type FeatureProgressiveTradeSizingDTO struct {
	// Defines the loss percentage threshold required to activate the feature. For instance, if set to 1%, the system will trigger the multiplier if a trade closes with a loss greater than 1% of the account balance. The default is 0%, meaning any negative trade will activate the feature.
	LastLossGreaterThanInPercentage *float32 `json:"lastLossGreaterThanInPercentage,omitempty"`
	// Limits the maximum number of consecutive times the trade volume can be increased after successive losses. For example, if set to 3, the trade volume will only be increased up to 3 times before being capped.
	LimitLevels *int32 `json:"limitLevels,omitempty"`
	// Defines the number of days to consider when evaluating past trades. For example, if set to 5, the system will look back at trades opened by the copier over the last 5 days to determine if the most recent trade closed with a loss.
	LookBackInDays *int32 `json:"lookBackInDays,omitempty"`
	// Specifies the multiplier to apply when increasing trade volume after a loss. The default multiplier is 2.000, meaning the volume of the next trade will be doubled after a loss.
	Multiplier *float32 `json:"multiplier,omitempty"`
}

// NewFeatureProgressiveTradeSizingDTO instantiates a new FeatureProgressiveTradeSizingDTO object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFeatureProgressiveTradeSizingDTO() *FeatureProgressiveTradeSizingDTO {
	this := FeatureProgressiveTradeSizingDTO{}
	var lastLossGreaterThanInPercentage float32 = 0
	this.LastLossGreaterThanInPercentage = &lastLossGreaterThanInPercentage
	var limitLevels int32 = 3
	this.LimitLevels = &limitLevels
	var lookBackInDays int32 = 5
	this.LookBackInDays = &lookBackInDays
	var multiplier float32 = 2.0
	this.Multiplier = &multiplier
	return &this
}

// NewFeatureProgressiveTradeSizingDTOWithDefaults instantiates a new FeatureProgressiveTradeSizingDTO object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFeatureProgressiveTradeSizingDTOWithDefaults() *FeatureProgressiveTradeSizingDTO {
	this := FeatureProgressiveTradeSizingDTO{}
	var lastLossGreaterThanInPercentage float32 = 0
	this.LastLossGreaterThanInPercentage = &lastLossGreaterThanInPercentage
	var limitLevels int32 = 3
	this.LimitLevels = &limitLevels
	var lookBackInDays int32 = 5
	this.LookBackInDays = &lookBackInDays
	var multiplier float32 = 2.0
	this.Multiplier = &multiplier
	return &this
}

// GetLastLossGreaterThanInPercentage returns the LastLossGreaterThanInPercentage field value if set, zero value otherwise.
func (o *FeatureProgressiveTradeSizingDTO) GetLastLossGreaterThanInPercentage() float32 {
	if o == nil || IsNil(o.LastLossGreaterThanInPercentage) {
		var ret float32
		return ret
	}
	return *o.LastLossGreaterThanInPercentage
}

// GetLastLossGreaterThanInPercentageOk returns a tuple with the LastLossGreaterThanInPercentage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FeatureProgressiveTradeSizingDTO) GetLastLossGreaterThanInPercentageOk() (*float32, bool) {
	if o == nil || IsNil(o.LastLossGreaterThanInPercentage) {
		return nil, false
	}
	return o.LastLossGreaterThanInPercentage, true
}

// HasLastLossGreaterThanInPercentage returns a boolean if a field has been set.
func (o *FeatureProgressiveTradeSizingDTO) HasLastLossGreaterThanInPercentage() bool {
	if o != nil && !IsNil(o.LastLossGreaterThanInPercentage) {
		return true
	}

	return false
}

// SetLastLossGreaterThanInPercentage gets a reference to the given float32 and assigns it to the LastLossGreaterThanInPercentage field.
func (o *FeatureProgressiveTradeSizingDTO) SetLastLossGreaterThanInPercentage(v float32) {
	o.LastLossGreaterThanInPercentage = &v
}

// GetLimitLevels returns the LimitLevels field value if set, zero value otherwise.
func (o *FeatureProgressiveTradeSizingDTO) GetLimitLevels() int32 {
	if o == nil || IsNil(o.LimitLevels) {
		var ret int32
		return ret
	}
	return *o.LimitLevels
}

// GetLimitLevelsOk returns a tuple with the LimitLevels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FeatureProgressiveTradeSizingDTO) GetLimitLevelsOk() (*int32, bool) {
	if o == nil || IsNil(o.LimitLevels) {
		return nil, false
	}
	return o.LimitLevels, true
}

// HasLimitLevels returns a boolean if a field has been set.
func (o *FeatureProgressiveTradeSizingDTO) HasLimitLevels() bool {
	if o != nil && !IsNil(o.LimitLevels) {
		return true
	}

	return false
}

// SetLimitLevels gets a reference to the given int32 and assigns it to the LimitLevels field.
func (o *FeatureProgressiveTradeSizingDTO) SetLimitLevels(v int32) {
	o.LimitLevels = &v
}

// GetLookBackInDays returns the LookBackInDays field value if set, zero value otherwise.
func (o *FeatureProgressiveTradeSizingDTO) GetLookBackInDays() int32 {
	if o == nil || IsNil(o.LookBackInDays) {
		var ret int32
		return ret
	}
	return *o.LookBackInDays
}

// GetLookBackInDaysOk returns a tuple with the LookBackInDays field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FeatureProgressiveTradeSizingDTO) GetLookBackInDaysOk() (*int32, bool) {
	if o == nil || IsNil(o.LookBackInDays) {
		return nil, false
	}
	return o.LookBackInDays, true
}

// HasLookBackInDays returns a boolean if a field has been set.
func (o *FeatureProgressiveTradeSizingDTO) HasLookBackInDays() bool {
	if o != nil && !IsNil(o.LookBackInDays) {
		return true
	}

	return false
}

// SetLookBackInDays gets a reference to the given int32 and assigns it to the LookBackInDays field.
func (o *FeatureProgressiveTradeSizingDTO) SetLookBackInDays(v int32) {
	o.LookBackInDays = &v
}

// GetMultiplier returns the Multiplier field value if set, zero value otherwise.
func (o *FeatureProgressiveTradeSizingDTO) GetMultiplier() float32 {
	if o == nil || IsNil(o.Multiplier) {
		var ret float32
		return ret
	}
	return *o.Multiplier
}

// GetMultiplierOk returns a tuple with the Multiplier field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FeatureProgressiveTradeSizingDTO) GetMultiplierOk() (*float32, bool) {
	if o == nil || IsNil(o.Multiplier) {
		return nil, false
	}
	return o.Multiplier, true
}

// HasMultiplier returns a boolean if a field has been set.
func (o *FeatureProgressiveTradeSizingDTO) HasMultiplier() bool {
	if o != nil && !IsNil(o.Multiplier) {
		return true
	}

	return false
}

// SetMultiplier gets a reference to the given float32 and assigns it to the Multiplier field.
func (o *FeatureProgressiveTradeSizingDTO) SetMultiplier(v float32) {
	o.Multiplier = &v
}

func (o FeatureProgressiveTradeSizingDTO) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FeatureProgressiveTradeSizingDTO) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.LastLossGreaterThanInPercentage) {
		toSerialize["lastLossGreaterThanInPercentage"] = o.LastLossGreaterThanInPercentage
	}
	if !IsNil(o.LimitLevels) {
		toSerialize["limitLevels"] = o.LimitLevels
	}
	if !IsNil(o.LookBackInDays) {
		toSerialize["lookBackInDays"] = o.LookBackInDays
	}
	if !IsNil(o.Multiplier) {
		toSerialize["multiplier"] = o.Multiplier
	}
	return toSerialize, nil
}

type NullableFeatureProgressiveTradeSizingDTO struct {
	value *FeatureProgressiveTradeSizingDTO
	isSet bool
}

func (v NullableFeatureProgressiveTradeSizingDTO) Get() *FeatureProgressiveTradeSizingDTO {
	return v.value
}

func (v *NullableFeatureProgressiveTradeSizingDTO) Set(val *FeatureProgressiveTradeSizingDTO) {
	v.value = val
	v.isSet = true
}

func (v NullableFeatureProgressiveTradeSizingDTO) IsSet() bool {
	return v.isSet
}

func (v *NullableFeatureProgressiveTradeSizingDTO) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFeatureProgressiveTradeSizingDTO(val *FeatureProgressiveTradeSizingDTO) *NullableFeatureProgressiveTradeSizingDTO {
	return &NullableFeatureProgressiveTradeSizingDTO{value: val, isSet: true}
}

func (v NullableFeatureProgressiveTradeSizingDTO) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFeatureProgressiveTradeSizingDTO) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
