/*
MetaCopier API

Explore the power of the MetaCopier API! Our RESTful API offers scalable and secure access to accounts, projects, and more. Get started quickly with authentication, explore endpoints, and access code samples in various languages.<br/><br/>All dates are in ISO 8601<br/><br/>This API is not designed for real-time communication purposes. For instance, continuously polling account information such as open positions every second is not recommended.<br/><br/>Our frontend uses this API, so you can look at the requests on our frontend for examples.

API version: 1.2.5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package metacopier

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the TelegramNotificationDTO type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TelegramNotificationDTO{}

// TelegramNotificationDTO List of telegram notifications
type TelegramNotificationDTO struct {
	// Only the account IDs listed here will receive notifications
	AccountIds   []string           `json:"accountIds,omitempty"`
	AliasMapping *map[string]string `json:"aliasMapping,omitempty"`
	LogLevel     LogTypeDTO         `json:"logLevel"`
	// Use alias instead of UUID for identification
	UseAlias *bool `json:"useAlias,omitempty"`
	// Enter the Telegram username (e.g. @john98734)
	Username string `json:"username"`
}

type _TelegramNotificationDTO TelegramNotificationDTO

// NewTelegramNotificationDTO instantiates a new TelegramNotificationDTO object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTelegramNotificationDTO(logLevel LogTypeDTO, username string) *TelegramNotificationDTO {
	this := TelegramNotificationDTO{}
	this.LogLevel = logLevel
	this.Username = username
	return &this
}

// NewTelegramNotificationDTOWithDefaults instantiates a new TelegramNotificationDTO object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTelegramNotificationDTOWithDefaults() *TelegramNotificationDTO {
	this := TelegramNotificationDTO{}
	return &this
}

// GetAccountIds returns the AccountIds field value if set, zero value otherwise.
func (o *TelegramNotificationDTO) GetAccountIds() []string {
	if o == nil || IsNil(o.AccountIds) {
		var ret []string
		return ret
	}
	return o.AccountIds
}

// GetAccountIdsOk returns a tuple with the AccountIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TelegramNotificationDTO) GetAccountIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.AccountIds) {
		return nil, false
	}
	return o.AccountIds, true
}

// HasAccountIds returns a boolean if a field has been set.
func (o *TelegramNotificationDTO) HasAccountIds() bool {
	if o != nil && !IsNil(o.AccountIds) {
		return true
	}

	return false
}

// SetAccountIds gets a reference to the given []string and assigns it to the AccountIds field.
func (o *TelegramNotificationDTO) SetAccountIds(v []string) {
	o.AccountIds = v
}

// GetAliasMapping returns the AliasMapping field value if set, zero value otherwise.
func (o *TelegramNotificationDTO) GetAliasMapping() map[string]string {
	if o == nil || IsNil(o.AliasMapping) {
		var ret map[string]string
		return ret
	}
	return *o.AliasMapping
}

// GetAliasMappingOk returns a tuple with the AliasMapping field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TelegramNotificationDTO) GetAliasMappingOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.AliasMapping) {
		return nil, false
	}
	return o.AliasMapping, true
}

// HasAliasMapping returns a boolean if a field has been set.
func (o *TelegramNotificationDTO) HasAliasMapping() bool {
	if o != nil && !IsNil(o.AliasMapping) {
		return true
	}

	return false
}

// SetAliasMapping gets a reference to the given map[string]string and assigns it to the AliasMapping field.
func (o *TelegramNotificationDTO) SetAliasMapping(v map[string]string) {
	o.AliasMapping = &v
}

// GetLogLevel returns the LogLevel field value
func (o *TelegramNotificationDTO) GetLogLevel() LogTypeDTO {
	if o == nil {
		var ret LogTypeDTO
		return ret
	}

	return o.LogLevel
}

// GetLogLevelOk returns a tuple with the LogLevel field value
// and a boolean to check if the value has been set.
func (o *TelegramNotificationDTO) GetLogLevelOk() (*LogTypeDTO, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LogLevel, true
}

// SetLogLevel sets field value
func (o *TelegramNotificationDTO) SetLogLevel(v LogTypeDTO) {
	o.LogLevel = v
}

// GetUseAlias returns the UseAlias field value if set, zero value otherwise.
func (o *TelegramNotificationDTO) GetUseAlias() bool {
	if o == nil || IsNil(o.UseAlias) {
		var ret bool
		return ret
	}
	return *o.UseAlias
}

// GetUseAliasOk returns a tuple with the UseAlias field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TelegramNotificationDTO) GetUseAliasOk() (*bool, bool) {
	if o == nil || IsNil(o.UseAlias) {
		return nil, false
	}
	return o.UseAlias, true
}

// HasUseAlias returns a boolean if a field has been set.
func (o *TelegramNotificationDTO) HasUseAlias() bool {
	if o != nil && !IsNil(o.UseAlias) {
		return true
	}

	return false
}

// SetUseAlias gets a reference to the given bool and assigns it to the UseAlias field.
func (o *TelegramNotificationDTO) SetUseAlias(v bool) {
	o.UseAlias = &v
}

// GetUsername returns the Username field value
func (o *TelegramNotificationDTO) GetUsername() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Username
}

// GetUsernameOk returns a tuple with the Username field value
// and a boolean to check if the value has been set.
func (o *TelegramNotificationDTO) GetUsernameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Username, true
}

// SetUsername sets field value
func (o *TelegramNotificationDTO) SetUsername(v string) {
	o.Username = v
}

func (o TelegramNotificationDTO) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TelegramNotificationDTO) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AccountIds) {
		toSerialize["accountIds"] = o.AccountIds
	}
	if !IsNil(o.AliasMapping) {
		toSerialize["aliasMapping"] = o.AliasMapping
	}
	toSerialize["logLevel"] = o.LogLevel
	if !IsNil(o.UseAlias) {
		toSerialize["useAlias"] = o.UseAlias
	}
	toSerialize["username"] = o.Username
	return toSerialize, nil
}

func (o *TelegramNotificationDTO) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"logLevel",
		"username",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTelegramNotificationDTO := _TelegramNotificationDTO{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTelegramNotificationDTO)

	if err != nil {
		return err
	}

	*o = TelegramNotificationDTO(varTelegramNotificationDTO)

	return err
}

type NullableTelegramNotificationDTO struct {
	value *TelegramNotificationDTO
	isSet bool
}

func (v NullableTelegramNotificationDTO) Get() *TelegramNotificationDTO {
	return v.value
}

func (v *NullableTelegramNotificationDTO) Set(val *TelegramNotificationDTO) {
	v.value = val
	v.isSet = true
}

func (v NullableTelegramNotificationDTO) IsSet() bool {
	return v.isSet
}

func (v *NullableTelegramNotificationDTO) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTelegramNotificationDTO(val *TelegramNotificationDTO) *NullableTelegramNotificationDTO {
	return &NullableTelegramNotificationDTO{value: val, isSet: true}
}

func (v NullableTelegramNotificationDTO) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTelegramNotificationDTO) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
