/*
MetaCopier API

Explore the power of the MetaCopier API! Our RESTful API offers scalable and secure access to accounts, projects, and more. Get started quickly with authentication, explore endpoints, and access code samples in various languages.<br/><br/>All dates are in ISO 8601<br/><br/>This API is not designed for real-time communication purposes. For instance, continuously polling account information such as open positions every second is not recommended.<br/><br/>Our frontend uses this API, so you can look at the requests on our frontend for examples.

API version: 1.2.5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package metacopier

import (
	"encoding/json"
	"fmt"
)

// checks if the FeatureSignalFollowerDTO type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FeatureSignalFollowerDTO{}

// FeatureSignalFollowerDTO DTO for signal follower feature (account)
type FeatureSignalFollowerDTO struct {
	// Specifies if the copier is active.
	Active *bool      `json:"active,omitempty"`
	Copier *CopierDTO `json:"copier,omitempty"`
	// Indicates whether this copier is in monitor-only mode. When true, the copier monitors the source account and manages existing open positions (can close, modify them) but will not copy any new trades. When false, the copier operates in normal copying mode.
	MonitorOnly *bool `json:"monitorOnly,omitempty"`
	// Indicates that the signal provider is available to the follower.
	SignalProviderAvailable *bool `json:"signalProviderAvailable,omitempty"`
	// Unique identifier (id of FeatureSignalProviderDTO) for the associated signal provider that the follower is linked to.
	SignalProviderId string `json:"signalProviderId"`
	// Name of the signal provider.
	SignalProviderName *string `json:"signalProviderName,omitempty"`
	// Specifies whether the follower is suspended (the copier is deactivated). This setting can only be changed by the signal provider and cannot be overridden by the follower.
	Suspended            *bool `json:"suspended,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _FeatureSignalFollowerDTO FeatureSignalFollowerDTO

// NewFeatureSignalFollowerDTO instantiates a new FeatureSignalFollowerDTO object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFeatureSignalFollowerDTO(signalProviderId string) *FeatureSignalFollowerDTO {
	this := FeatureSignalFollowerDTO{}
	var active bool = true
	this.Active = &active
	var monitorOnly bool = false
	this.MonitorOnly = &monitorOnly
	this.SignalProviderId = signalProviderId
	var suspended bool = false
	this.Suspended = &suspended
	return &this
}

// NewFeatureSignalFollowerDTOWithDefaults instantiates a new FeatureSignalFollowerDTO object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFeatureSignalFollowerDTOWithDefaults() *FeatureSignalFollowerDTO {
	this := FeatureSignalFollowerDTO{}
	var active bool = true
	this.Active = &active
	var monitorOnly bool = false
	this.MonitorOnly = &monitorOnly
	var suspended bool = false
	this.Suspended = &suspended
	return &this
}

// GetActive returns the Active field value if set, zero value otherwise.
func (o *FeatureSignalFollowerDTO) GetActive() bool {
	if o == nil || IsNil(o.Active) {
		var ret bool
		return ret
	}
	return *o.Active
}

// GetActiveOk returns a tuple with the Active field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FeatureSignalFollowerDTO) GetActiveOk() (*bool, bool) {
	if o == nil || IsNil(o.Active) {
		return nil, false
	}
	return o.Active, true
}

// HasActive returns a boolean if a field has been set.
func (o *FeatureSignalFollowerDTO) HasActive() bool {
	if o != nil && !IsNil(o.Active) {
		return true
	}

	return false
}

// SetActive gets a reference to the given bool and assigns it to the Active field.
func (o *FeatureSignalFollowerDTO) SetActive(v bool) {
	o.Active = &v
}

// GetCopier returns the Copier field value if set, zero value otherwise.
func (o *FeatureSignalFollowerDTO) GetCopier() CopierDTO {
	if o == nil || IsNil(o.Copier) {
		var ret CopierDTO
		return ret
	}
	return *o.Copier
}

// GetCopierOk returns a tuple with the Copier field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FeatureSignalFollowerDTO) GetCopierOk() (*CopierDTO, bool) {
	if o == nil || IsNil(o.Copier) {
		return nil, false
	}
	return o.Copier, true
}

// HasCopier returns a boolean if a field has been set.
func (o *FeatureSignalFollowerDTO) HasCopier() bool {
	if o != nil && !IsNil(o.Copier) {
		return true
	}

	return false
}

// SetCopier gets a reference to the given CopierDTO and assigns it to the Copier field.
func (o *FeatureSignalFollowerDTO) SetCopier(v CopierDTO) {
	o.Copier = &v
}

// GetMonitorOnly returns the MonitorOnly field value if set, zero value otherwise.
func (o *FeatureSignalFollowerDTO) GetMonitorOnly() bool {
	if o == nil || IsNil(o.MonitorOnly) {
		var ret bool
		return ret
	}
	return *o.MonitorOnly
}

// GetMonitorOnlyOk returns a tuple with the MonitorOnly field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FeatureSignalFollowerDTO) GetMonitorOnlyOk() (*bool, bool) {
	if o == nil || IsNil(o.MonitorOnly) {
		return nil, false
	}
	return o.MonitorOnly, true
}

// HasMonitorOnly returns a boolean if a field has been set.
func (o *FeatureSignalFollowerDTO) HasMonitorOnly() bool {
	if o != nil && !IsNil(o.MonitorOnly) {
		return true
	}

	return false
}

// SetMonitorOnly gets a reference to the given bool and assigns it to the MonitorOnly field.
func (o *FeatureSignalFollowerDTO) SetMonitorOnly(v bool) {
	o.MonitorOnly = &v
}

// GetSignalProviderAvailable returns the SignalProviderAvailable field value if set, zero value otherwise.
func (o *FeatureSignalFollowerDTO) GetSignalProviderAvailable() bool {
	if o == nil || IsNil(o.SignalProviderAvailable) {
		var ret bool
		return ret
	}
	return *o.SignalProviderAvailable
}

// GetSignalProviderAvailableOk returns a tuple with the SignalProviderAvailable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FeatureSignalFollowerDTO) GetSignalProviderAvailableOk() (*bool, bool) {
	if o == nil || IsNil(o.SignalProviderAvailable) {
		return nil, false
	}
	return o.SignalProviderAvailable, true
}

// HasSignalProviderAvailable returns a boolean if a field has been set.
func (o *FeatureSignalFollowerDTO) HasSignalProviderAvailable() bool {
	if o != nil && !IsNil(o.SignalProviderAvailable) {
		return true
	}

	return false
}

// SetSignalProviderAvailable gets a reference to the given bool and assigns it to the SignalProviderAvailable field.
func (o *FeatureSignalFollowerDTO) SetSignalProviderAvailable(v bool) {
	o.SignalProviderAvailable = &v
}

// GetSignalProviderId returns the SignalProviderId field value
func (o *FeatureSignalFollowerDTO) GetSignalProviderId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SignalProviderId
}

// GetSignalProviderIdOk returns a tuple with the SignalProviderId field value
// and a boolean to check if the value has been set.
func (o *FeatureSignalFollowerDTO) GetSignalProviderIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SignalProviderId, true
}

// SetSignalProviderId sets field value
func (o *FeatureSignalFollowerDTO) SetSignalProviderId(v string) {
	o.SignalProviderId = v
}

// GetSignalProviderName returns the SignalProviderName field value if set, zero value otherwise.
func (o *FeatureSignalFollowerDTO) GetSignalProviderName() string {
	if o == nil || IsNil(o.SignalProviderName) {
		var ret string
		return ret
	}
	return *o.SignalProviderName
}

// GetSignalProviderNameOk returns a tuple with the SignalProviderName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FeatureSignalFollowerDTO) GetSignalProviderNameOk() (*string, bool) {
	if o == nil || IsNil(o.SignalProviderName) {
		return nil, false
	}
	return o.SignalProviderName, true
}

// HasSignalProviderName returns a boolean if a field has been set.
func (o *FeatureSignalFollowerDTO) HasSignalProviderName() bool {
	if o != nil && !IsNil(o.SignalProviderName) {
		return true
	}

	return false
}

// SetSignalProviderName gets a reference to the given string and assigns it to the SignalProviderName field.
func (o *FeatureSignalFollowerDTO) SetSignalProviderName(v string) {
	o.SignalProviderName = &v
}

// GetSuspended returns the Suspended field value if set, zero value otherwise.
func (o *FeatureSignalFollowerDTO) GetSuspended() bool {
	if o == nil || IsNil(o.Suspended) {
		var ret bool
		return ret
	}
	return *o.Suspended
}

// GetSuspendedOk returns a tuple with the Suspended field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FeatureSignalFollowerDTO) GetSuspendedOk() (*bool, bool) {
	if o == nil || IsNil(o.Suspended) {
		return nil, false
	}
	return o.Suspended, true
}

// HasSuspended returns a boolean if a field has been set.
func (o *FeatureSignalFollowerDTO) HasSuspended() bool {
	if o != nil && !IsNil(o.Suspended) {
		return true
	}

	return false
}

// SetSuspended gets a reference to the given bool and assigns it to the Suspended field.
func (o *FeatureSignalFollowerDTO) SetSuspended(v bool) {
	o.Suspended = &v
}

func (o FeatureSignalFollowerDTO) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FeatureSignalFollowerDTO) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Active) {
		toSerialize["active"] = o.Active
	}
	if !IsNil(o.Copier) {
		toSerialize["copier"] = o.Copier
	}
	if !IsNil(o.MonitorOnly) {
		toSerialize["monitorOnly"] = o.MonitorOnly
	}
	if !IsNil(o.SignalProviderAvailable) {
		toSerialize["signalProviderAvailable"] = o.SignalProviderAvailable
	}
	toSerialize["signalProviderId"] = o.SignalProviderId
	if !IsNil(o.SignalProviderName) {
		toSerialize["signalProviderName"] = o.SignalProviderName
	}
	if !IsNil(o.Suspended) {
		toSerialize["suspended"] = o.Suspended
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *FeatureSignalFollowerDTO) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"signalProviderId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFeatureSignalFollowerDTO := _FeatureSignalFollowerDTO{}

	err = json.Unmarshal(data, &varFeatureSignalFollowerDTO)

	if err != nil {
		return err
	}

	*o = FeatureSignalFollowerDTO(varFeatureSignalFollowerDTO)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "active")
		delete(additionalProperties, "copier")
		delete(additionalProperties, "monitorOnly")
		delete(additionalProperties, "signalProviderAvailable")
		delete(additionalProperties, "signalProviderId")
		delete(additionalProperties, "signalProviderName")
		delete(additionalProperties, "suspended")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableFeatureSignalFollowerDTO struct {
	value *FeatureSignalFollowerDTO
	isSet bool
}

func (v NullableFeatureSignalFollowerDTO) Get() *FeatureSignalFollowerDTO {
	return v.value
}

func (v *NullableFeatureSignalFollowerDTO) Set(val *FeatureSignalFollowerDTO) {
	v.value = val
	v.isSet = true
}

func (v NullableFeatureSignalFollowerDTO) IsSet() bool {
	return v.isSet
}

func (v *NullableFeatureSignalFollowerDTO) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFeatureSignalFollowerDTO(val *FeatureSignalFollowerDTO) *NullableFeatureSignalFollowerDTO {
	return &NullableFeatureSignalFollowerDTO{value: val, isSet: true}
}

func (v NullableFeatureSignalFollowerDTO) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFeatureSignalFollowerDTO) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
