/*
MetaCopier API

Explore the power of the MetaCopier API! Our RESTful API offers scalable and secure access to accounts, projects, and more. Get started quickly with authentication, explore endpoints, and access code samples in various languages.<br/><br/>All dates are in ISO 8601<br/><br/>This API is not designed for real-time communication purposes. For instance, continuously polling account information such as open positions every second is not recommended.<br/><br/>Our frontend uses this API, so you can look at the requests on our frontend for examples.

API version: 1.2.5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package metacopier

import (
	"encoding/json"
	"fmt"
)

// checks if the RiskTypeDTO type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RiskTypeDTO{}

// RiskTypeDTO     You have to set it during resource creation, after that, it is only read-only.     You have only to set the id, e.g. 4 for actual drawdown.     1: Daily, 2: Weekly, 3: Monthly, 4: Actual, 5: Equity-equity daily, 6: Equity-equity weekly, 7: Equity-equity monthly, 8: Smart reference daily,     9: Smart reference weekly, 10: Smart reference monthly.      When you set a daily risk limit of 0.5 (50%), it means that if the ratio of the balance     at a specific timepoint (see resetTime) to equity reaches 50%, the copy trading will be     paused, and if specified, all trades will be closed (see closeAllOpenPositions).      The limit reference type depends on the selected risk type:     • Balance-based limits use the balance as reference.     • Equity-based limits use the equity as reference.     • Smart limits use the greater of balance and equity as reference.      Example: {id: 1}
type RiskTypeDTO struct {
	Id                   int32   `json:"id"`
	Name                 *string `json:"name,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _RiskTypeDTO RiskTypeDTO

// NewRiskTypeDTO instantiates a new RiskTypeDTO object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRiskTypeDTO(id int32) *RiskTypeDTO {
	this := RiskTypeDTO{}
	this.Id = id
	return &this
}

// NewRiskTypeDTOWithDefaults instantiates a new RiskTypeDTO object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRiskTypeDTOWithDefaults() *RiskTypeDTO {
	this := RiskTypeDTO{}
	return &this
}

// GetId returns the Id field value
func (o *RiskTypeDTO) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *RiskTypeDTO) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *RiskTypeDTO) SetId(v int32) {
	o.Id = v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *RiskTypeDTO) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RiskTypeDTO) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *RiskTypeDTO) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *RiskTypeDTO) SetName(v string) {
	o.Name = &v
}

func (o RiskTypeDTO) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RiskTypeDTO) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *RiskTypeDTO) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRiskTypeDTO := _RiskTypeDTO{}

	err = json.Unmarshal(data, &varRiskTypeDTO)

	if err != nil {
		return err
	}

	*o = RiskTypeDTO(varRiskTypeDTO)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "name")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableRiskTypeDTO struct {
	value *RiskTypeDTO
	isSet bool
}

func (v NullableRiskTypeDTO) Get() *RiskTypeDTO {
	return v.value
}

func (v *NullableRiskTypeDTO) Set(val *RiskTypeDTO) {
	v.value = val
	v.isSet = true
}

func (v NullableRiskTypeDTO) IsSet() bool {
	return v.isSet
}

func (v *NullableRiskTypeDTO) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRiskTypeDTO(val *RiskTypeDTO) *NullableRiskTypeDTO {
	return &NullableRiskTypeDTO{value: val, isSet: true}
}

func (v NullableRiskTypeDTO) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRiskTypeDTO) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
